// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AIGatewayModelServiceConfigInitParameters struct {

	// Inference table configuration for payload logging
	InferenceTable *ConfigInferenceTableInitParameters `json:"inferenceTable,omitempty" tf:"inference_table,omitempty"`

	// Rate limits applied to requests routed through this model service
	RateLimits []AIGatewayModelServiceConfigRateLimitsInitParameters `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Routing configuration: destinations and fallback
	Routing *RoutingInitParameters `json:"routing,omitempty" tf:"routing,omitempty"`
}

type AIGatewayModelServiceConfigObservation struct {

	// Inference table configuration for payload logging
	InferenceTable *ConfigInferenceTableObservation `json:"inferenceTable,omitempty" tf:"inference_table,omitempty"`

	// Rate limits applied to requests routed through this model service
	RateLimits []AIGatewayModelServiceConfigRateLimitsObservation `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Routing configuration: destinations and fallback
	Routing *RoutingObservation `json:"routing,omitempty" tf:"routing,omitempty"`
}

type AIGatewayModelServiceConfigParameters struct {

	// Inference table configuration for payload logging
	// +kubebuilder:validation:Optional
	InferenceTable *ConfigInferenceTableParameters `json:"inferenceTable,omitempty" tf:"inference_table,omitempty"`

	// Rate limits applied to requests routed through this model service
	// +kubebuilder:validation:Optional
	RateLimits []AIGatewayModelServiceConfigRateLimitsParameters `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Routing configuration: destinations and fallback
	// +kubebuilder:validation:Optional
	Routing *RoutingParameters `json:"routing,omitempty" tf:"routing,omitempty"`
}

type AIGatewayModelServiceConfigRateLimitsInitParameters struct {

	// Scope of the rate limit. Depending on this value, the limit applies to a
	// principal, the service as a whole, or each user by default. Possible values are: RATE_LIMIT_KEY_SERVICE, RATE_LIMIT_KEY_SERVICE_PRINCIPAL, RATE_LIMIT_KEY_USER, RATE_LIMIT_KEY_USER_DEFAULT, RATE_LIMIT_KEY_USER_GROUP
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Principal this limit applies to: user email, group name, or service
	// principal application ID. Required when key applies to a user, group, or
	// service principal; otherwise it must be unset
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Renewal period. Possible values are: RATE_LIMIT_RENEWAL_PERIOD_HOUR, RATE_LIMIT_RENEWAL_PERIOD_MINUTE
	RenewalPeriod *string `json:"renewalPeriod,omitempty" tf:"renewal_period,omitempty"`

	// Maximum requests allowed in one renewal period. Leave unset for no request
	// limit. Set to 0 to deny all requests
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`

	// Maximum tokens allowed in one renewal period. Leave unset for no token
	// limit. Set to 0 to deny all requests
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type AIGatewayModelServiceConfigRateLimitsObservation struct {

	// Scope of the rate limit. Depending on this value, the limit applies to a
	// principal, the service as a whole, or each user by default. Possible values are: RATE_LIMIT_KEY_SERVICE, RATE_LIMIT_KEY_SERVICE_PRINCIPAL, RATE_LIMIT_KEY_USER, RATE_LIMIT_KEY_USER_DEFAULT, RATE_LIMIT_KEY_USER_GROUP
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Principal this limit applies to: user email, group name, or service
	// principal application ID. Required when key applies to a user, group, or
	// service principal; otherwise it must be unset
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Renewal period. Possible values are: RATE_LIMIT_RENEWAL_PERIOD_HOUR, RATE_LIMIT_RENEWAL_PERIOD_MINUTE
	RenewalPeriod *string `json:"renewalPeriod,omitempty" tf:"renewal_period,omitempty"`

	// Maximum requests allowed in one renewal period. Leave unset for no request
	// limit. Set to 0 to deny all requests
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`

	// Maximum tokens allowed in one renewal period. Leave unset for no token
	// limit. Set to 0 to deny all requests
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type AIGatewayModelServiceConfigRateLimitsParameters struct {

	// Scope of the rate limit. Depending on this value, the limit applies to a
	// principal, the service as a whole, or each user by default. Possible values are: RATE_LIMIT_KEY_SERVICE, RATE_LIMIT_KEY_SERVICE_PRINCIPAL, RATE_LIMIT_KEY_USER, RATE_LIMIT_KEY_USER_DEFAULT, RATE_LIMIT_KEY_USER_GROUP
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// Principal this limit applies to: user email, group name, or service
	// principal application ID. Required when key applies to a user, group, or
	// service principal; otherwise it must be unset
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Renewal period. Possible values are: RATE_LIMIT_RENEWAL_PERIOD_HOUR, RATE_LIMIT_RENEWAL_PERIOD_MINUTE
	// +kubebuilder:validation:Optional
	RenewalPeriod *string `json:"renewalPeriod" tf:"renewal_period,omitempty"`

	// Maximum requests allowed in one renewal period. Leave unset for no request
	// limit. Set to 0 to deny all requests
	// +kubebuilder:validation:Optional
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`

	// Maximum tokens allowed in one renewal period. Leave unset for no token
	// limit. Set to 0 to deny all requests
	// +kubebuilder:validation:Optional
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type AIGatewayModelServiceInitParameters struct {

	// User-provided description
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Destinations, routing, rate limits, and payload logging configuration.
	// Required on Create. On Update, provide this field when update_mask
	// contains config or one of its subpaths
	Config *AIGatewayModelServiceConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// Name for the model service, e.g. "my_model_service"
	ModelServiceID *string `json:"modelServiceId,omitempty" tf:"model_service_id,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *AIGatewayModelServiceProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type AIGatewayModelServiceObservation struct {

	// User-provided description
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Destinations, routing, rate limits, and payload logging configuration.
	// Required on Create. On Update, provide this field when update_mask
	// contains config or one of its subpaths
	Config *AIGatewayModelServiceConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// Time the model service was created
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Creator identity
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Owner of the model service
	EffectiveOwner *string `json:"effectiveOwner,omitempty" tf:"effective_owner,omitempty"`

	// Optimistic concurrency token returned on every read. To make an Update or
	// Delete conditional, pass the last-read value in that request's etag
	// field. In REST responses, this value is a base64 string; URL-encode it when
	// setting the etag query parameter
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Metastore hosting the model service
	MetastoreID *string `json:"metastoreId,omitempty" tf:"metastore_id,omitempty"`

	// Name for the model service, e.g. "my_model_service"
	ModelServiceID *string `json:"modelServiceId,omitempty" tf:"model_service_id,omitempty"`

	// User-facing label for this destination, used in routing references
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *AIGatewayModelServiceProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// API types supported across this service's destinations, such as
	// openai/v1/chat/completions, openai/v1/embeddings, and
	// mlflow/v1/chat/completions. Derived from the backing models and providers
	// at read time
	// +listType=set
	SupportedAPITypes []*string `json:"supportedApiTypes,omitempty" tf:"supported_api_types,omitempty"`

	// Time the model service was last modified
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`

	// Identity of the last updater
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`
}

type AIGatewayModelServiceParameters struct {

	// User-provided description
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Destinations, routing, rate limits, and payload logging configuration.
	// Required on Create. On Update, provide this field when update_mask
	// contains config or one of its subpaths
	// +kubebuilder:validation:Optional
	Config *AIGatewayModelServiceConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// Name for the model service, e.g. "my_model_service"
	// +kubebuilder:validation:Optional
	ModelServiceID *string `json:"modelServiceId,omitempty" tf:"model_service_id,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *AIGatewayModelServiceProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type AIGatewayModelServiceProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type AIGatewayModelServiceProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type AIGatewayModelServiceProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ConfigInferenceTableInitParameters struct {

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Prefix used to form the inference table's registered name. AI Gateway
	// appends _payload; for example, table_name_prefix = "orders" creates
	// orders_payload. If unset, the prefix defaults to the service name. Read
	// table from the response for the resulting resource name. After the
	// inference table is created, this field cannot be changed
	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type ConfigInferenceTableObservation struct {

	// Whether the referenced inference table has been deleted. The configuration
	// remains visible so you can identify the broken dependency. Payload logging
	// cannot continue until the table is restored or the configuration is updated
	IsDeleted *bool `json:"isDeleted,omitempty" tf:"is_deleted,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Resolved UC table for payload logs.
	// Format: tables/{catalog}.{schema}.{table}
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Prefix used to form the inference table's registered name. AI Gateway
	// appends _payload; for example, table_name_prefix = "orders" creates
	// orders_payload. If unset, the prefix defaults to the service name. Read
	// table from the response for the resulting resource name. After the
	// inference table is created, this field cannot be changed
	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type ConfigInferenceTableParameters struct {

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent" tf:"parent,omitempty"`

	// Prefix used to form the inference table's registered name. AI Gateway
	// appends _payload; for example, table_name_prefix = "orders" creates
	// orders_payload. If unset, the prefix defaults to the service name. Read
	// table from the response for the resulting resource name. After the
	// inference table is created, this field cannot be changed
	// +kubebuilder:validation:Optional
	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type DestinationsExternalModelConfigInitParameters struct {

	// Resource name of the governed ModelProviderService that owns provider
	// auth and provider-specific configuration. The referenced
	// ModelProviderService also carries the provider type, so this message
	// does not surface it directly.
	// Format: model-provider-services/{catalog}.{schema}.{model_provider_service}.
	// Each {...} component is capped at 255 characters individually
	ModelProviderService *string `json:"modelProviderService,omitempty" tf:"model_provider_service,omitempty"`

	// Routing target for the destination: the provider-side model selected from
	// the referenced ModelProviderService's targets catalog, plus the unified
	// API types the platform should translate to/from at request time
	Target *ExternalModelConfigTargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type DestinationsExternalModelConfigObservation struct {

	// Resource name of the governed ModelProviderService that owns provider
	// auth and provider-specific configuration. The referenced
	// ModelProviderService also carries the provider type, so this message
	// does not surface it directly.
	// Format: model-provider-services/{catalog}.{schema}.{model_provider_service}.
	// Each {...} component is capped at 255 characters individually
	ModelProviderService *string `json:"modelProviderService,omitempty" tf:"model_provider_service,omitempty"`

	// Routing target for the destination: the provider-side model selected from
	// the referenced ModelProviderService's targets catalog, plus the unified
	// API types the platform should translate to/from at request time
	Target *ExternalModelConfigTargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type DestinationsExternalModelConfigParameters struct {

	// Resource name of the governed ModelProviderService that owns provider
	// auth and provider-specific configuration. The referenced
	// ModelProviderService also carries the provider type, so this message
	// does not surface it directly.
	// Format: model-provider-services/{catalog}.{schema}.{model_provider_service}.
	// Each {...} component is capped at 255 characters individually
	// +kubebuilder:validation:Optional
	ModelProviderService *string `json:"modelProviderService" tf:"model_provider_service,omitempty"`

	// Routing target for the destination: the provider-side model selected from
	// the referenced ModelProviderService's targets catalog, plus the unified
	// API types the platform should translate to/from at request time
	// +kubebuilder:validation:Optional
	Target *ExternalModelConfigTargetParameters `json:"target" tf:"target,omitempty"`
}

type DestinationsInitParameters struct {

	// Backing-model category. Provide the matching type-specific configuration
	// and leave the other type-specific configurations unset. Possible values are: DESTINATION_TYPE_EXTERNAL_FOUNDATION_MODEL, DESTINATION_TYPE_PAY_PER_TOKEN_FOUNDATION_MODEL, DESTINATION_TYPE_PROVISIONED_THROUGHPUT_FOUNDATION_MODEL
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// Configuration for an external model reached through a model provider service
	ExternalModelConfig *ExternalModelConfigInitParameters `json:"externalModelConfig,omitempty" tf:"external_model_config,omitempty"`

	// User-facing label for this destination, used in routing references
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configuration for a pay-per-token Databricks foundation model
	PayPerTokenConfig *PayPerTokenConfigInitParameters `json:"payPerTokenConfig,omitempty" tf:"pay_per_token_config,omitempty"`

	// Configuration for a provisioned-throughput Databricks foundation model
	ProvisionedThroughputConfig *ProvisionedThroughputConfigInitParameters `json:"provisionedThroughputConfig,omitempty" tf:"provisioned_throughput_config,omitempty"`

	// Percentage of primary traffic sent to this destination, from 0 to 100.
	// Required when there is more than one primary destination, in which case the
	// primary percentages must sum to 100; a single primary destination receives
	// all traffic. Fallback destinations are ordered and do not use this field
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type DestinationsObservation struct {

	// Backing-model category. Provide the matching type-specific configuration
	// and leave the other type-specific configurations unset. Possible values are: DESTINATION_TYPE_EXTERNAL_FOUNDATION_MODEL, DESTINATION_TYPE_PAY_PER_TOKEN_FOUNDATION_MODEL, DESTINATION_TYPE_PROVISIONED_THROUGHPUT_FOUNDATION_MODEL
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// Configuration for an external model reached through a model provider service
	ExternalModelConfig *ExternalModelConfigObservation `json:"externalModelConfig,omitempty" tf:"external_model_config,omitempty"`

	// Whether the referenced inference table has been deleted. The configuration
	// remains visible so you can identify the broken dependency. Payload logging
	// cannot continue until the table is restored or the configuration is updated
	IsDeleted *bool `json:"isDeleted,omitempty" tf:"is_deleted,omitempty"`

	// User-facing label for this destination, used in routing references
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configuration for a pay-per-token Databricks foundation model
	PayPerTokenConfig *PayPerTokenConfigObservation `json:"payPerTokenConfig,omitempty" tf:"pay_per_token_config,omitempty"`

	// Configuration for a provisioned-throughput Databricks foundation model
	ProvisionedThroughputConfig *ProvisionedThroughputConfigObservation `json:"provisionedThroughputConfig,omitempty" tf:"provisioned_throughput_config,omitempty"`

	// Percentage of primary traffic sent to this destination, from 0 to 100.
	// Required when there is more than one primary destination, in which case the
	// primary percentages must sum to 100; a single primary destination receives
	// all traffic. Fallback destinations are ordered and do not use this field
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type DestinationsParameters struct {

	// Backing-model category. Provide the matching type-specific configuration
	// and leave the other type-specific configurations unset. Possible values are: DESTINATION_TYPE_EXTERNAL_FOUNDATION_MODEL, DESTINATION_TYPE_PAY_PER_TOKEN_FOUNDATION_MODEL, DESTINATION_TYPE_PROVISIONED_THROUGHPUT_FOUNDATION_MODEL
	// +kubebuilder:validation:Optional
	DestinationType *string `json:"destinationType" tf:"destination_type,omitempty"`

	// Configuration for an external model reached through a model provider service
	// +kubebuilder:validation:Optional
	ExternalModelConfig *ExternalModelConfigParameters `json:"externalModelConfig,omitempty" tf:"external_model_config,omitempty"`

	// User-facing label for this destination, used in routing references
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Configuration for a pay-per-token Databricks foundation model
	// +kubebuilder:validation:Optional
	PayPerTokenConfig *PayPerTokenConfigParameters `json:"payPerTokenConfig,omitempty" tf:"pay_per_token_config,omitempty"`

	// Configuration for a provisioned-throughput Databricks foundation model
	// +kubebuilder:validation:Optional
	ProvisionedThroughputConfig *ProvisionedThroughputConfigParameters `json:"provisionedThroughputConfig,omitempty" tf:"provisioned_throughput_config,omitempty"`

	// Percentage of primary traffic sent to this destination, from 0 to 100.
	// Required when there is more than one primary destination, in which case the
	// primary percentages must sum to 100; a single primary destination receives
	// all traffic. Fallback destinations are ordered and do not use this field
	// +kubebuilder:validation:Optional
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type DestinationsPayPerTokenConfigInitParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`
}

type DestinationsPayPerTokenConfigObservation struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`
}

type DestinationsPayPerTokenConfigParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	// +kubebuilder:validation:Optional
	Model *string `json:"model" tf:"model,omitempty"`
}

type DestinationsProvisionedThroughputConfigInitParameters struct {

	// Name of the backing Model Serving endpoint serving the provisioned-
	// throughput foundation model, in the form serving-endpoints/{name}. The
	// same Unity Catalog model can be served on multiple Model Serving endpoints
	// with different throughput, regions, or configurations. The caller selects
	// the endpoint to which this destination routes. The endpoint must exist at
	// create time
	ModelServingEndpoint *string `json:"modelServingEndpoint,omitempty" tf:"model_serving_endpoint,omitempty"`
}

type DestinationsProvisionedThroughputConfigObservation struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// Name of the backing Model Serving endpoint serving the provisioned-
	// throughput foundation model, in the form serving-endpoints/{name}. The
	// same Unity Catalog model can be served on multiple Model Serving endpoints
	// with different throughput, regions, or configurations. The caller selects
	// the endpoint to which this destination routes. The endpoint must exist at
	// create time
	ModelServingEndpoint *string `json:"modelServingEndpoint,omitempty" tf:"model_serving_endpoint,omitempty"`
}

type DestinationsProvisionedThroughputConfigParameters struct {

	// Name of the backing Model Serving endpoint serving the provisioned-
	// throughput foundation model, in the form serving-endpoints/{name}. The
	// same Unity Catalog model can be served on multiple Model Serving endpoints
	// with different throughput, regions, or configurations. The caller selects
	// the endpoint to which this destination routes. The endpoint must exist at
	// create time
	// +kubebuilder:validation:Optional
	ModelServingEndpoint *string `json:"modelServingEndpoint" tf:"model_serving_endpoint,omitempty"`
}

type ExternalModelConfigInitParameters struct {

	// Resource name of the governed ModelProviderService that owns provider
	// auth and provider-specific configuration. The referenced
	// ModelProviderService also carries the provider type, so this message
	// does not surface it directly.
	// Format: model-provider-services/{catalog}.{schema}.{model_provider_service}.
	// Each {...} component is capped at 255 characters individually
	ModelProviderService *string `json:"modelProviderService,omitempty" tf:"model_provider_service,omitempty"`

	// Routing target for the destination: the provider-side model selected from
	// the referenced ModelProviderService's targets catalog, plus the unified
	// API types the platform should translate to/from at request time
	Target *TargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type ExternalModelConfigObservation struct {

	// Resource name of the governed ModelProviderService that owns provider
	// auth and provider-specific configuration. The referenced
	// ModelProviderService also carries the provider type, so this message
	// does not surface it directly.
	// Format: model-provider-services/{catalog}.{schema}.{model_provider_service}.
	// Each {...} component is capped at 255 characters individually
	ModelProviderService *string `json:"modelProviderService,omitempty" tf:"model_provider_service,omitempty"`

	// Routing target for the destination: the provider-side model selected from
	// the referenced ModelProviderService's targets catalog, plus the unified
	// API types the platform should translate to/from at request time
	Target *TargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type ExternalModelConfigParameters struct {

	// Resource name of the governed ModelProviderService that owns provider
	// auth and provider-specific configuration. The referenced
	// ModelProviderService also carries the provider type, so this message
	// does not surface it directly.
	// Format: model-provider-services/{catalog}.{schema}.{model_provider_service}.
	// Each {...} component is capped at 255 characters individually
	// +kubebuilder:validation:Optional
	ModelProviderService *string `json:"modelProviderService" tf:"model_provider_service,omitempty"`

	// Routing target for the destination: the provider-side model selected from
	// the referenced ModelProviderService's targets catalog, plus the unified
	// API types the platform should translate to/from at request time
	// +kubebuilder:validation:Optional
	Target *TargetParameters `json:"target" tf:"target,omitempty"`
}

type ExternalModelConfigTargetInitParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// Provider-native API types supported by this model, such as
	// openai/v1/chat/completions. At least one value is required. AI Gateway
	// uses these values to translate requests and responses. At most 64 entries
	// of 256 characters each are allowed
	NativeAPITypes []*string `json:"nativeApiTypes,omitempty" tf:"native_api_types,omitempty"`
}

type ExternalModelConfigTargetObservation struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// Provider-native API types supported by this model, such as
	// openai/v1/chat/completions. At least one value is required. AI Gateway
	// uses these values to translate requests and responses. At most 64 entries
	// of 256 characters each are allowed
	NativeAPITypes []*string `json:"nativeApiTypes,omitempty" tf:"native_api_types,omitempty"`
}

type ExternalModelConfigTargetParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	// +kubebuilder:validation:Optional
	Model *string `json:"model" tf:"model,omitempty"`

	// Provider-native API types supported by this model, such as
	// openai/v1/chat/completions. At least one value is required. AI Gateway
	// uses these values to translate requests and responses. At most 64 entries
	// of 256 characters each are allowed
	// +kubebuilder:validation:Optional
	NativeAPITypes []*string `json:"nativeApiTypes,omitempty" tf:"native_api_types,omitempty"`
}

type FallbackDestinationsInitParameters struct {

	// Backing-model category. Provide the matching type-specific configuration
	// and leave the other type-specific configurations unset. Possible values are: DESTINATION_TYPE_EXTERNAL_FOUNDATION_MODEL, DESTINATION_TYPE_PAY_PER_TOKEN_FOUNDATION_MODEL, DESTINATION_TYPE_PROVISIONED_THROUGHPUT_FOUNDATION_MODEL
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// Configuration for an external model reached through a model provider service
	ExternalModelConfig *DestinationsExternalModelConfigInitParameters `json:"externalModelConfig,omitempty" tf:"external_model_config,omitempty"`

	// User-facing label for this destination, used in routing references
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configuration for a pay-per-token Databricks foundation model
	PayPerTokenConfig *DestinationsPayPerTokenConfigInitParameters `json:"payPerTokenConfig,omitempty" tf:"pay_per_token_config,omitempty"`

	// Configuration for a provisioned-throughput Databricks foundation model
	ProvisionedThroughputConfig *DestinationsProvisionedThroughputConfigInitParameters `json:"provisionedThroughputConfig,omitempty" tf:"provisioned_throughput_config,omitempty"`

	// Percentage of primary traffic sent to this destination, from 0 to 100.
	// Required when there is more than one primary destination, in which case the
	// primary percentages must sum to 100; a single primary destination receives
	// all traffic. Fallback destinations are ordered and do not use this field
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type FallbackDestinationsObservation struct {

	// Backing-model category. Provide the matching type-specific configuration
	// and leave the other type-specific configurations unset. Possible values are: DESTINATION_TYPE_EXTERNAL_FOUNDATION_MODEL, DESTINATION_TYPE_PAY_PER_TOKEN_FOUNDATION_MODEL, DESTINATION_TYPE_PROVISIONED_THROUGHPUT_FOUNDATION_MODEL
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// Configuration for an external model reached through a model provider service
	ExternalModelConfig *DestinationsExternalModelConfigObservation `json:"externalModelConfig,omitempty" tf:"external_model_config,omitempty"`

	// Whether the referenced inference table has been deleted. The configuration
	// remains visible so you can identify the broken dependency. Payload logging
	// cannot continue until the table is restored or the configuration is updated
	IsDeleted *bool `json:"isDeleted,omitempty" tf:"is_deleted,omitempty"`

	// User-facing label for this destination, used in routing references
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configuration for a pay-per-token Databricks foundation model
	PayPerTokenConfig *DestinationsPayPerTokenConfigObservation `json:"payPerTokenConfig,omitempty" tf:"pay_per_token_config,omitempty"`

	// Configuration for a provisioned-throughput Databricks foundation model
	ProvisionedThroughputConfig *DestinationsProvisionedThroughputConfigObservation `json:"provisionedThroughputConfig,omitempty" tf:"provisioned_throughput_config,omitempty"`

	// Percentage of primary traffic sent to this destination, from 0 to 100.
	// Required when there is more than one primary destination, in which case the
	// primary percentages must sum to 100; a single primary destination receives
	// all traffic. Fallback destinations are ordered and do not use this field
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type FallbackDestinationsParameters struct {

	// Backing-model category. Provide the matching type-specific configuration
	// and leave the other type-specific configurations unset. Possible values are: DESTINATION_TYPE_EXTERNAL_FOUNDATION_MODEL, DESTINATION_TYPE_PAY_PER_TOKEN_FOUNDATION_MODEL, DESTINATION_TYPE_PROVISIONED_THROUGHPUT_FOUNDATION_MODEL
	// +kubebuilder:validation:Optional
	DestinationType *string `json:"destinationType" tf:"destination_type,omitempty"`

	// Configuration for an external model reached through a model provider service
	// +kubebuilder:validation:Optional
	ExternalModelConfig *DestinationsExternalModelConfigParameters `json:"externalModelConfig,omitempty" tf:"external_model_config,omitempty"`

	// User-facing label for this destination, used in routing references
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Configuration for a pay-per-token Databricks foundation model
	// +kubebuilder:validation:Optional
	PayPerTokenConfig *DestinationsPayPerTokenConfigParameters `json:"payPerTokenConfig,omitempty" tf:"pay_per_token_config,omitempty"`

	// Configuration for a provisioned-throughput Databricks foundation model
	// +kubebuilder:validation:Optional
	ProvisionedThroughputConfig *DestinationsProvisionedThroughputConfigParameters `json:"provisionedThroughputConfig,omitempty" tf:"provisioned_throughput_config,omitempty"`

	// Percentage of primary traffic sent to this destination, from 0 to 100.
	// Required when there is more than one primary destination, in which case the
	// primary percentages must sum to 100; a single primary destination receives
	// all traffic. Fallback destinations are ordered and do not use this field
	// +kubebuilder:validation:Optional
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type FallbackInitParameters struct {

	// Fallback destinations, tried in the listed order. At most 5 are allowed
	Destinations []FallbackDestinationsInitParameters `json:"destinations,omitempty" tf:"destinations,omitempty"`
}

type FallbackObservation struct {

	// Fallback destinations, tried in the listed order. At most 5 are allowed
	Destinations []FallbackDestinationsObservation `json:"destinations,omitempty" tf:"destinations,omitempty"`
}

type FallbackParameters struct {

	// Fallback destinations, tried in the listed order. At most 5 are allowed
	// +kubebuilder:validation:Optional
	Destinations []FallbackDestinationsParameters `json:"destinations,omitempty" tf:"destinations,omitempty"`
}

type PayPerTokenConfigInitParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`
}

type PayPerTokenConfigObservation struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`
}

type PayPerTokenConfigParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	// +kubebuilder:validation:Optional
	Model *string `json:"model" tf:"model,omitempty"`
}

type ProvisionedThroughputConfigInitParameters struct {

	// Name of the backing Model Serving endpoint serving the provisioned-
	// throughput foundation model, in the form serving-endpoints/{name}. The
	// same Unity Catalog model can be served on multiple Model Serving endpoints
	// with different throughput, regions, or configurations. The caller selects
	// the endpoint to which this destination routes. The endpoint must exist at
	// create time
	ModelServingEndpoint *string `json:"modelServingEndpoint,omitempty" tf:"model_serving_endpoint,omitempty"`
}

type ProvisionedThroughputConfigObservation struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// Name of the backing Model Serving endpoint serving the provisioned-
	// throughput foundation model, in the form serving-endpoints/{name}. The
	// same Unity Catalog model can be served on multiple Model Serving endpoints
	// with different throughput, regions, or configurations. The caller selects
	// the endpoint to which this destination routes. The endpoint must exist at
	// create time
	ModelServingEndpoint *string `json:"modelServingEndpoint,omitempty" tf:"model_serving_endpoint,omitempty"`
}

type ProvisionedThroughputConfigParameters struct {

	// Name of the backing Model Serving endpoint serving the provisioned-
	// throughput foundation model, in the form serving-endpoints/{name}. The
	// same Unity Catalog model can be served on multiple Model Serving endpoints
	// with different throughput, regions, or configurations. The caller selects
	// the endpoint to which this destination routes. The endpoint must exist at
	// create time
	// +kubebuilder:validation:Optional
	ModelServingEndpoint *string `json:"modelServingEndpoint" tf:"model_serving_endpoint,omitempty"`
}

type RoutingInitParameters struct {

	// Fallback destinations, tried in the listed order. At most 5 are allowed
	Destinations []DestinationsInitParameters `json:"destinations,omitempty" tf:"destinations,omitempty"`

	// Fallback routing applied after a primary destination fails. Fallback
	// destinations are tried in the listed order
	Fallback *FallbackInitParameters `json:"fallback,omitempty" tf:"fallback,omitempty"`
}

type RoutingObservation struct {

	// Fallback destinations, tried in the listed order. At most 5 are allowed
	Destinations []DestinationsObservation `json:"destinations,omitempty" tf:"destinations,omitempty"`

	// Fallback routing applied after a primary destination fails. Fallback
	// destinations are tried in the listed order
	Fallback *FallbackObservation `json:"fallback,omitempty" tf:"fallback,omitempty"`
}

type RoutingParameters struct {

	// Fallback destinations, tried in the listed order. At most 5 are allowed
	// +kubebuilder:validation:Optional
	Destinations []DestinationsParameters `json:"destinations,omitempty" tf:"destinations,omitempty"`

	// Fallback routing applied after a primary destination fails. Fallback
	// destinations are tried in the listed order
	// +kubebuilder:validation:Optional
	Fallback *FallbackParameters `json:"fallback,omitempty" tf:"fallback,omitempty"`
}

type TargetInitParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// Provider-native API types supported by this model, such as
	// openai/v1/chat/completions. At least one value is required. AI Gateway
	// uses these values to translate requests and responses. At most 64 entries
	// of 256 characters each are allowed
	NativeAPITypes []*string `json:"nativeApiTypes,omitempty" tf:"native_api_types,omitempty"`
}

type TargetObservation struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// Provider-native API types supported by this model, such as
	// openai/v1/chat/completions. At least one value is required. AI Gateway
	// uses these values to translate requests and responses. At most 64 entries
	// of 256 characters each are allowed
	NativeAPITypes []*string `json:"nativeApiTypes,omitempty" tf:"native_api_types,omitempty"`
}

type TargetParameters struct {

	// Provider-side model identifier, such as gpt-5 or claude-opus-4-7.
	// This identifies a model at the upstream provider; it is not a Unity
	// Catalog model resource
	// +kubebuilder:validation:Optional
	Model *string `json:"model" tf:"model,omitempty"`

	// Provider-native API types supported by this model, such as
	// openai/v1/chat/completions. At least one value is required. AI Gateway
	// uses these values to translate requests and responses. At most 64 entries
	// of 256 characters each are allowed
	// +kubebuilder:validation:Optional
	NativeAPITypes []*string `json:"nativeApiTypes,omitempty" tf:"native_api_types,omitempty"`
}

// AIGatewayModelServiceSpec defines the desired state of AIGatewayModelService
type AIGatewayModelServiceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AIGatewayModelServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AIGatewayModelServiceInitParameters `json:"initProvider,omitempty"`
}

// AIGatewayModelServiceStatus defines the observed state of AIGatewayModelService.
type AIGatewayModelServiceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AIGatewayModelServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AIGatewayModelService is the Schema for the AIGatewayModelServices API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type AIGatewayModelService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.modelServiceId) || (has(self.initProvider) && has(self.initProvider.modelServiceId))",message="spec.forProvider.modelServiceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parent) || (has(self.initProvider) && has(self.initProvider.parent))",message="spec.forProvider.parent is a required parameter"
	Spec   AIGatewayModelServiceSpec   `json:"spec"`
	Status AIGatewayModelServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AIGatewayModelServiceList contains a list of AIGatewayModelServices
type AIGatewayModelServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIGatewayModelService `json:"items"`
}

// Repository type metadata.
var (
	AIGatewayModelService_Kind             = "AIGatewayModelService"
	AIGatewayModelService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AIGatewayModelService_Kind}.String()
	AIGatewayModelService_KindAPIVersion   = AIGatewayModelService_Kind + "." + CRDGroupVersion.String()
	AIGatewayModelService_GroupVersionKind = CRDGroupVersion.WithKind(AIGatewayModelService_Kind)
)

func init() {
	SchemeBuilder.Register(&AIGatewayModelService{}, &AIGatewayModelServiceList{})
}
