// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AuthConfigInitParameters struct {
	MtlsConfig *MtlsConfigInitParameters `json:"mtlsConfig,omitempty" tf:"mtls_config,omitempty"`

	UcServiceCredentialName *string `json:"ucServiceCredentialName,omitempty" tf:"uc_service_credential_name,omitempty"`
}

type AuthConfigObservation struct {
	MtlsConfig *MtlsConfigObservation `json:"mtlsConfig,omitempty" tf:"mtls_config,omitempty"`

	UcServiceCredentialName *string `json:"ucServiceCredentialName,omitempty" tf:"uc_service_credential_name,omitempty"`
}

type AuthConfigParameters struct {

	// +kubebuilder:validation:Optional
	MtlsConfig *MtlsConfigParameters `json:"mtlsConfig,omitempty" tf:"mtls_config,omitempty"`

	// +kubebuilder:validation:Optional
	UcServiceCredentialName *string `json:"ucServiceCredentialName,omitempty" tf:"uc_service_credential_name,omitempty"`
}

type BackfillSourceDeltaTableSourceInitParameters struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type BackfillSourceDeltaTableSourceObservation struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type BackfillSourceDeltaTableSourceParameters struct {

	// +kubebuilder:validation:Optional
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	// +kubebuilder:validation:Optional
	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	// +kubebuilder:validation:Optional
	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName" tf:"full_name,omitempty"`

	// +kubebuilder:validation:Optional
	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	// +kubebuilder:validation:Optional
	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type BackfillSourceInitParameters struct {
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`

	DeltaTableSource *BackfillSourceDeltaTableSourceInitParameters `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`
}

type BackfillSourceObservation struct {
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`

	DeltaTableSource *BackfillSourceDeltaTableSourceObservation `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`
}

type BackfillSourceParameters struct {

	// +kubebuilder:validation:Optional
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`

	// +kubebuilder:validation:Optional
	DeltaTableSource *BackfillSourceDeltaTableSourceParameters `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`
}

type FeatureEngineeringKafkaConfigInitParameters struct {
	AuthConfig *AuthConfigInitParameters `json:"authConfig,omitempty" tf:"auth_config,omitempty"`

	BackfillSource *BackfillSourceInitParameters `json:"backfillSource,omitempty" tf:"backfill_source,omitempty"`

	BootstrapServers *string `json:"bootstrapServers,omitempty" tf:"bootstrap_servers,omitempty"`

	// +mapType=granular
	ExtraOptions map[string]*string `json:"extraOptions,omitempty" tf:"extra_options,omitempty"`

	IngestionConfig *IngestionConfigInitParameters `json:"ingestionConfig,omitempty" tf:"ingestion_config,omitempty"`

	KeySchema *KeySchemaInitParameters `json:"keySchema,omitempty" tf:"key_schema,omitempty"`

	ProviderConfig *FeatureEngineeringKafkaConfigProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	SubscriptionMode *SubscriptionModeInitParameters `json:"subscriptionMode,omitempty" tf:"subscription_mode,omitempty"`

	ValueSchema *ValueSchemaInitParameters `json:"valueSchema,omitempty" tf:"value_schema,omitempty"`
}

type FeatureEngineeringKafkaConfigObservation struct {
	AuthConfig *AuthConfigObservation `json:"authConfig,omitempty" tf:"auth_config,omitempty"`

	BackfillSource *BackfillSourceObservation `json:"backfillSource,omitempty" tf:"backfill_source,omitempty"`

	BootstrapServers *string `json:"bootstrapServers,omitempty" tf:"bootstrap_servers,omitempty"`

	// +mapType=granular
	ExtraOptions map[string]*string `json:"extraOptions,omitempty" tf:"extra_options,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IngestionConfig *IngestionConfigObservation `json:"ingestionConfig,omitempty" tf:"ingestion_config,omitempty"`

	KeySchema *KeySchemaObservation `json:"keySchema,omitempty" tf:"key_schema,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ProviderConfig *FeatureEngineeringKafkaConfigProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	SubscriptionMode *SubscriptionModeObservation `json:"subscriptionMode,omitempty" tf:"subscription_mode,omitempty"`

	ValueSchema *ValueSchemaObservation `json:"valueSchema,omitempty" tf:"value_schema,omitempty"`
}

type FeatureEngineeringKafkaConfigParameters struct {

	// +kubebuilder:validation:Optional
	AuthConfig *AuthConfigParameters `json:"authConfig,omitempty" tf:"auth_config,omitempty"`

	// +kubebuilder:validation:Optional
	BackfillSource *BackfillSourceParameters `json:"backfillSource,omitempty" tf:"backfill_source,omitempty"`

	// +kubebuilder:validation:Optional
	BootstrapServers *string `json:"bootstrapServers,omitempty" tf:"bootstrap_servers,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	ExtraOptions map[string]*string `json:"extraOptions,omitempty" tf:"extra_options,omitempty"`

	// +kubebuilder:validation:Optional
	IngestionConfig *IngestionConfigParameters `json:"ingestionConfig,omitempty" tf:"ingestion_config,omitempty"`

	// +kubebuilder:validation:Optional
	KeySchema *KeySchemaParameters `json:"keySchema,omitempty" tf:"key_schema,omitempty"`

	// +kubebuilder:validation:Optional
	ProviderConfig *FeatureEngineeringKafkaConfigProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// +kubebuilder:validation:Optional
	SubscriptionMode *SubscriptionModeParameters `json:"subscriptionMode,omitempty" tf:"subscription_mode,omitempty"`

	// +kubebuilder:validation:Optional
	ValueSchema *ValueSchemaParameters `json:"valueSchema,omitempty" tf:"value_schema,omitempty"`
}

type FeatureEngineeringKafkaConfigProviderConfigInitParameters struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type FeatureEngineeringKafkaConfigProviderConfigObservation struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type FeatureEngineeringKafkaConfigProviderConfigParameters struct {

	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type IngestionConfigBackfillSourceDeltaTableSourceInitParameters struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type IngestionConfigBackfillSourceDeltaTableSourceObservation struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type IngestionConfigBackfillSourceDeltaTableSourceParameters struct {

	// +kubebuilder:validation:Optional
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	// +kubebuilder:validation:Optional
	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	// +kubebuilder:validation:Optional
	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName" tf:"full_name,omitempty"`

	// +kubebuilder:validation:Optional
	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	// +kubebuilder:validation:Optional
	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type IngestionConfigBackfillSourceInitParameters struct {
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`

	DeltaTableSource *IngestionConfigBackfillSourceDeltaTableSourceInitParameters `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`
}

type IngestionConfigBackfillSourceObservation struct {
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`

	DeltaTableSource *IngestionConfigBackfillSourceDeltaTableSourceObservation `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`
}

type IngestionConfigBackfillSourceParameters struct {

	// +kubebuilder:validation:Optional
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`

	// +kubebuilder:validation:Optional
	DeltaTableSource *IngestionConfigBackfillSourceDeltaTableSourceParameters `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`
}

type IngestionConfigInitParameters struct {
	BackfillSource *IngestionConfigBackfillSourceInitParameters `json:"backfillSource,omitempty" tf:"backfill_source,omitempty"`

	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	DeduplicationColumns []*string `json:"deduplicationColumns,omitempty" tf:"deduplication_columns,omitempty"`

	IngestionDestination *IngestionDestinationInitParameters `json:"ingestionDestination,omitempty" tf:"ingestion_destination,omitempty"`

	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type IngestionConfigObservation struct {
	BackfillJobID *float64 `json:"backfillJobId,omitempty" tf:"backfill_job_id,omitempty"`

	BackfillSource *IngestionConfigBackfillSourceObservation `json:"backfillSource,omitempty" tf:"backfill_source,omitempty"`

	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	DeduplicationColumns []*string `json:"deduplicationColumns,omitempty" tf:"deduplication_columns,omitempty"`

	IngestionDestination *IngestionDestinationObservation `json:"ingestionDestination,omitempty" tf:"ingestion_destination,omitempty"`

	IngestionJobID *float64 `json:"ingestionJobId,omitempty" tf:"ingestion_job_id,omitempty"`

	IngestionPipelineID *string `json:"ingestionPipelineId,omitempty" tf:"ingestion_pipeline_id,omitempty"`

	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type IngestionConfigParameters struct {

	// +kubebuilder:validation:Optional
	BackfillSource *IngestionConfigBackfillSourceParameters `json:"backfillSource,omitempty" tf:"backfill_source,omitempty"`

	// +kubebuilder:validation:Optional
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	// +kubebuilder:validation:Optional
	DeduplicationColumns []*string `json:"deduplicationColumns,omitempty" tf:"deduplication_columns,omitempty"`

	// +kubebuilder:validation:Optional
	IngestionDestination *IngestionDestinationParameters `json:"ingestionDestination" tf:"ingestion_destination,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type IngestionDestinationInitParameters struct {
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`
}

type IngestionDestinationObservation struct {
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`
}

type IngestionDestinationParameters struct {

	// +kubebuilder:validation:Optional
	DeltaTableName *string `json:"deltaTableName,omitempty" tf:"delta_table_name,omitempty"`
}

type KeyPasswordRefInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type KeyPasswordRefObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type KeyPasswordRefParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope" tf:"scope,omitempty"`
}

type KeySchemaInitParameters struct {
	AvroSchema *string `json:"avroSchema,omitempty" tf:"avro_schema,omitempty"`

	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	ProtoSchema *ProtoSchemaInitParameters `json:"protoSchema,omitempty" tf:"proto_schema,omitempty"`
}

type KeySchemaObservation struct {
	AvroSchema *string `json:"avroSchema,omitempty" tf:"avro_schema,omitempty"`

	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	ProtoSchema *ProtoSchemaObservation `json:"protoSchema,omitempty" tf:"proto_schema,omitempty"`
}

type KeySchemaParameters struct {

	// +kubebuilder:validation:Optional
	AvroSchema *string `json:"avroSchema,omitempty" tf:"avro_schema,omitempty"`

	// +kubebuilder:validation:Optional
	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	// +kubebuilder:validation:Optional
	ProtoSchema *ProtoSchemaParameters `json:"protoSchema,omitempty" tf:"proto_schema,omitempty"`
}

type KeystorePasswordRefInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type KeystorePasswordRefObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type KeystorePasswordRefParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope" tf:"scope,omitempty"`
}

type MtlsConfigInitParameters struct {
	DisableHostnameVerification *bool `json:"disableHostnameVerification,omitempty" tf:"disable_hostname_verification,omitempty"`

	KeyPasswordRef *KeyPasswordRefInitParameters `json:"keyPasswordRef,omitempty" tf:"key_password_ref,omitempty"`

	KeystoreLocation *string `json:"keystoreLocation,omitempty" tf:"keystore_location,omitempty"`

	KeystorePasswordRef *KeystorePasswordRefInitParameters `json:"keystorePasswordRef,omitempty" tf:"keystore_password_ref,omitempty"`

	TruststoreLocation *string `json:"truststoreLocation,omitempty" tf:"truststore_location,omitempty"`

	TruststorePasswordRef *TruststorePasswordRefInitParameters `json:"truststorePasswordRef,omitempty" tf:"truststore_password_ref,omitempty"`
}

type MtlsConfigObservation struct {
	DisableHostnameVerification *bool `json:"disableHostnameVerification,omitempty" tf:"disable_hostname_verification,omitempty"`

	KeyPasswordRef *KeyPasswordRefObservation `json:"keyPasswordRef,omitempty" tf:"key_password_ref,omitempty"`

	KeystoreLocation *string `json:"keystoreLocation,omitempty" tf:"keystore_location,omitempty"`

	KeystorePasswordRef *KeystorePasswordRefObservation `json:"keystorePasswordRef,omitempty" tf:"keystore_password_ref,omitempty"`

	TruststoreLocation *string `json:"truststoreLocation,omitempty" tf:"truststore_location,omitempty"`

	TruststorePasswordRef *TruststorePasswordRefObservation `json:"truststorePasswordRef,omitempty" tf:"truststore_password_ref,omitempty"`
}

type MtlsConfigParameters struct {

	// +kubebuilder:validation:Optional
	DisableHostnameVerification *bool `json:"disableHostnameVerification,omitempty" tf:"disable_hostname_verification,omitempty"`

	// +kubebuilder:validation:Optional
	KeyPasswordRef *KeyPasswordRefParameters `json:"keyPasswordRef" tf:"key_password_ref,omitempty"`

	// +kubebuilder:validation:Optional
	KeystoreLocation *string `json:"keystoreLocation" tf:"keystore_location,omitempty"`

	// +kubebuilder:validation:Optional
	KeystorePasswordRef *KeystorePasswordRefParameters `json:"keystorePasswordRef" tf:"keystore_password_ref,omitempty"`

	// +kubebuilder:validation:Optional
	TruststoreLocation *string `json:"truststoreLocation" tf:"truststore_location,omitempty"`

	// +kubebuilder:validation:Optional
	TruststorePasswordRef *TruststorePasswordRefParameters `json:"truststorePasswordRef" tf:"truststore_password_ref,omitempty"`
}

type ProtoSchemaInitParameters struct {
	MessageName *string `json:"messageName,omitempty" tf:"message_name,omitempty"`

	SchemaText *string `json:"schemaText,omitempty" tf:"schema_text,omitempty"`
}

type ProtoSchemaObservation struct {
	MessageName *string `json:"messageName,omitempty" tf:"message_name,omitempty"`

	SchemaText *string `json:"schemaText,omitempty" tf:"schema_text,omitempty"`
}

type ProtoSchemaParameters struct {

	// +kubebuilder:validation:Optional
	MessageName *string `json:"messageName" tf:"message_name,omitempty"`

	// +kubebuilder:validation:Optional
	SchemaText *string `json:"schemaText" tf:"schema_text,omitempty"`
}

type SubscriptionModeInitParameters struct {
	Assign *string `json:"assign,omitempty" tf:"assign,omitempty"`

	Subscribe *string `json:"subscribe,omitempty" tf:"subscribe,omitempty"`

	SubscribePattern *string `json:"subscribePattern,omitempty" tf:"subscribe_pattern,omitempty"`
}

type SubscriptionModeObservation struct {
	Assign *string `json:"assign,omitempty" tf:"assign,omitempty"`

	Subscribe *string `json:"subscribe,omitempty" tf:"subscribe,omitempty"`

	SubscribePattern *string `json:"subscribePattern,omitempty" tf:"subscribe_pattern,omitempty"`
}

type SubscriptionModeParameters struct {

	// +kubebuilder:validation:Optional
	Assign *string `json:"assign,omitempty" tf:"assign,omitempty"`

	// +kubebuilder:validation:Optional
	Subscribe *string `json:"subscribe,omitempty" tf:"subscribe,omitempty"`

	// +kubebuilder:validation:Optional
	SubscribePattern *string `json:"subscribePattern,omitempty" tf:"subscribe_pattern,omitempty"`
}

type TruststorePasswordRefInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TruststorePasswordRefObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TruststorePasswordRefParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope" tf:"scope,omitempty"`
}

type ValueSchemaInitParameters struct {
	AvroSchema *string `json:"avroSchema,omitempty" tf:"avro_schema,omitempty"`

	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	ProtoSchema *ValueSchemaProtoSchemaInitParameters `json:"protoSchema,omitempty" tf:"proto_schema,omitempty"`
}

type ValueSchemaObservation struct {
	AvroSchema *string `json:"avroSchema,omitempty" tf:"avro_schema,omitempty"`

	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	ProtoSchema *ValueSchemaProtoSchemaObservation `json:"protoSchema,omitempty" tf:"proto_schema,omitempty"`
}

type ValueSchemaParameters struct {

	// +kubebuilder:validation:Optional
	AvroSchema *string `json:"avroSchema,omitempty" tf:"avro_schema,omitempty"`

	// +kubebuilder:validation:Optional
	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	// +kubebuilder:validation:Optional
	ProtoSchema *ValueSchemaProtoSchemaParameters `json:"protoSchema,omitempty" tf:"proto_schema,omitempty"`
}

type ValueSchemaProtoSchemaInitParameters struct {
	MessageName *string `json:"messageName,omitempty" tf:"message_name,omitempty"`

	SchemaText *string `json:"schemaText,omitempty" tf:"schema_text,omitempty"`
}

type ValueSchemaProtoSchemaObservation struct {
	MessageName *string `json:"messageName,omitempty" tf:"message_name,omitempty"`

	SchemaText *string `json:"schemaText,omitempty" tf:"schema_text,omitempty"`
}

type ValueSchemaProtoSchemaParameters struct {

	// +kubebuilder:validation:Optional
	MessageName *string `json:"messageName" tf:"message_name,omitempty"`

	// +kubebuilder:validation:Optional
	SchemaText *string `json:"schemaText" tf:"schema_text,omitempty"`
}

// FeatureEngineeringKafkaConfigSpec defines the desired state of FeatureEngineeringKafkaConfig
type FeatureEngineeringKafkaConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeatureEngineeringKafkaConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureEngineeringKafkaConfigInitParameters `json:"initProvider,omitempty"`
}

// FeatureEngineeringKafkaConfigStatus defines the observed state of FeatureEngineeringKafkaConfig.
type FeatureEngineeringKafkaConfigStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FeatureEngineeringKafkaConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureEngineeringKafkaConfig is the Schema for the FeatureEngineeringKafkaConfigs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type FeatureEngineeringKafkaConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authConfig) || (has(self.initProvider) && has(self.initProvider.authConfig))",message="spec.forProvider.authConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bootstrapServers) || (has(self.initProvider) && has(self.initProvider.bootstrapServers))",message="spec.forProvider.bootstrapServers is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subscriptionMode) || (has(self.initProvider) && has(self.initProvider.subscriptionMode))",message="spec.forProvider.subscriptionMode is a required parameter"
	Spec   FeatureEngineeringKafkaConfigSpec   `json:"spec"`
	Status FeatureEngineeringKafkaConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureEngineeringKafkaConfigList contains a list of FeatureEngineeringKafkaConfigs
type FeatureEngineeringKafkaConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureEngineeringKafkaConfig `json:"items"`
}

// Repository type metadata.
var (
	FeatureEngineeringKafkaConfig_Kind             = "FeatureEngineeringKafkaConfig"
	FeatureEngineeringKafkaConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureEngineeringKafkaConfig_Kind}.String()
	FeatureEngineeringKafkaConfig_KindAPIVersion   = FeatureEngineeringKafkaConfig_Kind + "." + CRDGroupVersion.String()
	FeatureEngineeringKafkaConfig_GroupVersionKind = CRDGroupVersion.WithKind(FeatureEngineeringKafkaConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureEngineeringKafkaConfig{}, &FeatureEngineeringKafkaConfigList{})
}
