// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this FeatureEngineeringFeature.
func (mg *FeatureEngineeringFeature) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this FeatureEngineeringKafkaConfig.
func (mg *FeatureEngineeringKafkaConfig) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this FeatureEngineeringMaterializedFeature.
func (mg *FeatureEngineeringMaterializedFeature) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this MaterializedFeaturesFeatureTag.
func (mg *MaterializedFeaturesFeatureTag) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetProviderConfigReference of this MlflowExperiment.
func (mg *MlflowExperiment) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this MlflowExperiment.
func (mg *MlflowExperiment) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetProviderConfigReference of this MlflowExperiment.
func (mg *MlflowExperiment) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this MlflowExperiment.
func (mg *MlflowExperiment) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetProviderConfigReference of this MlflowModel.
func (mg *MlflowModel) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this MlflowModel.
func (mg *MlflowModel) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetProviderConfigReference of this MlflowModel.
func (mg *MlflowModel) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this MlflowModel.
func (mg *MlflowModel) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetProviderConfigReference of this MlflowWebhook.
func (mg *MlflowWebhook) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this MlflowWebhook.
func (mg *MlflowWebhook) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetProviderConfigReference of this MlflowWebhook.
func (mg *MlflowWebhook) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this MlflowWebhook.
func (mg *MlflowWebhook) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
