// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package namespaced

import (
	"github.com/buzz-IT/provider-databricks/config/namespaced/access_control_rule_set"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_federation_policy"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_iam_direct_group_member_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_iam_group_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_iam_service_principal_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_iam_user_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_iam_workspace_assignment_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_network_policy"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_setting_user_preference_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/account_setting_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/ai_gateway_mcp_service"
	"github.com/buzz-IT/provider-databricks/config/namespaced/ai_gateway_model_provider_service"
	"github.com/buzz-IT/provider-databricks/config/namespaced/ai_gateway_model_service"
	"github.com/buzz-IT/provider-databricks/config/namespaced/ai_search_endpoint"
	"github.com/buzz-IT/provider-databricks/config/namespaced/ai_search_index"
	"github.com/buzz-IT/provider-databricks/config/namespaced/aibi_dashboard_embedding_access_policy_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/aibi_dashboard_embedding_approved_domains_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/alert"
	"github.com/buzz-IT/provider-databricks/config/namespaced/alert_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/app"
	"github.com/buzz-IT/provider-databricks/config/namespaced/app_space"
	"github.com/buzz-IT/provider-databricks/config/namespaced/apps_settings_custom_template"
	"github.com/buzz-IT/provider-databricks/config/namespaced/artifact_allowlist"
	"github.com/buzz-IT/provider-databricks/config/namespaced/automatic_cluster_update_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/automatic_cluster_update_workspace_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/aws_s3_mount"
	"github.com/buzz-IT/provider-databricks/config/namespaced/azure_adls_gen1_mount"
	"github.com/buzz-IT/provider-databricks/config/namespaced/azure_adls_gen2_mount"
	"github.com/buzz-IT/provider-databricks/config/namespaced/azure_blob_mount"
	"github.com/buzz-IT/provider-databricks/config/namespaced/budget"
	"github.com/buzz-IT/provider-databricks/config/namespaced/budget_policy"
	"github.com/buzz-IT/provider-databricks/config/namespaced/catalog"
	"github.com/buzz-IT/provider-databricks/config/namespaced/catalog_workspace_binding"
	"github.com/buzz-IT/provider-databricks/config/namespaced/cluster"
	"github.com/buzz-IT/provider-databricks/config/namespaced/cluster_policy"
	"github.com/buzz-IT/provider-databricks/config/namespaced/compliance_security_profile_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/compliance_security_profile_workspace_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/connection"
	"github.com/buzz-IT/provider-databricks/config/namespaced/credential"
	"github.com/buzz-IT/provider-databricks/config/namespaced/custom_app_integration"
	"github.com/buzz-IT/provider-databricks/config/namespaced/dashboard"
	"github.com/buzz-IT/provider-databricks/config/namespaced/data_classification_catalog_config"
	"github.com/buzz-IT/provider-databricks/config/namespaced/data_quality_monitor"
	"github.com/buzz-IT/provider-databricks/config/namespaced/data_quality_refresh"
	"github.com/buzz-IT/provider-databricks/config/namespaced/database_database_catalog"
	"github.com/buzz-IT/provider-databricks/config/namespaced/database_instance"
	"github.com/buzz-IT/provider-databricks/config/namespaced/database_synced_database_table"
	"github.com/buzz-IT/provider-databricks/config/namespaced/dbfs_file"
	"github.com/buzz-IT/provider-databricks/config/namespaced/default_namespace_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/directory"
	"github.com/buzz-IT/provider-databricks/config/namespaced/disable_legacy_access_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/disable_legacy_dbfs_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/disable_legacy_features_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/disaster_recovery_failover_group"
	"github.com/buzz-IT/provider-databricks/config/namespaced/disaster_recovery_stable_url"
	"github.com/buzz-IT/provider-databricks/config/namespaced/domain"
	"github.com/buzz-IT/provider-databricks/config/namespaced/endpoint"
	"github.com/buzz-IT/provider-databricks/config/namespaced/enhanced_security_monitoring_workspace_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/entitlements"
	"github.com/buzz-IT/provider-databricks/config/namespaced/entity_tag_assignment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/environments_default_workspace_base_environment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/environments_workspace_base_environment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/external_location"
	"github.com/buzz-IT/provider-databricks/config/namespaced/external_metadata"
	"github.com/buzz-IT/provider-databricks/config/namespaced/feature_engineering_feature"
	"github.com/buzz-IT/provider-databricks/config/namespaced/feature_engineering_kafka_config"
	"github.com/buzz-IT/provider-databricks/config/namespaced/feature_engineering_materialized_feature"
	"github.com/buzz-IT/provider-databricks/config/namespaced/file"
	"github.com/buzz-IT/provider-databricks/config/namespaced/git_credential"
	"github.com/buzz-IT/provider-databricks/config/namespaced/global_init_script"
	"github.com/buzz-IT/provider-databricks/config/namespaced/grant"
	"github.com/buzz-IT/provider-databricks/config/namespaced/grants"
	"github.com/buzz-IT/provider-databricks/config/namespaced/group"
	"github.com/buzz-IT/provider-databricks/config/namespaced/group_instance_profile"
	"github.com/buzz-IT/provider-databricks/config/namespaced/group_member"
	"github.com/buzz-IT/provider-databricks/config/namespaced/group_role"
	"github.com/buzz-IT/provider-databricks/config/namespaced/instance_pool"
	"github.com/buzz-IT/provider-databricks/config/namespaced/instance_profile"
	"github.com/buzz-IT/provider-databricks/config/namespaced/ip_access_list"
	"github.com/buzz-IT/provider-databricks/config/namespaced/job"
	"github.com/buzz-IT/provider-databricks/config/namespaced/knowledge_assistant"
	"github.com/buzz-IT/provider-databricks/config/namespaced/knowledge_assistant_knowledge_source"
	"github.com/buzz-IT/provider-databricks/config/namespaced/lakehouse_monitor"
	"github.com/buzz-IT/provider-databricks/config/namespaced/library"
	"github.com/buzz-IT/provider-databricks/config/namespaced/materialized_features_feature_tag"
	"github.com/buzz-IT/provider-databricks/config/namespaced/metastore"
	"github.com/buzz-IT/provider-databricks/config/namespaced/metastore_assignment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/metastore_data_access"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mlflow_experiment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mlflow_model"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mlflow_webhook"
	"github.com/buzz-IT/provider-databricks/config/namespaced/model_serving"
	"github.com/buzz-IT/provider-databricks/config/namespaced/model_serving_provisioned_throughput"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mount"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_credentials"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_customer_managed_keys"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_log_delivery"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_ncc_binding"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_ncc_private_endpoint_rule"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_network_connectivity_config"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_networks"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_permission_assignment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_private_access_settings"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_storage_configurations"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_vpc_endpoint"
	"github.com/buzz-IT/provider-databricks/config/namespaced/mws_workspaces"
	"github.com/buzz-IT/provider-databricks/config/namespaced/notebook"
	"github.com/buzz-IT/provider-databricks/config/namespaced/notification_destination"
	"github.com/buzz-IT/provider-databricks/config/namespaced/obo_token"
	"github.com/buzz-IT/provider-databricks/config/namespaced/online_store"
	"github.com/buzz-IT/provider-databricks/config/namespaced/online_table"
	"github.com/buzz-IT/provider-databricks/config/namespaced/permission_assignment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/permissions"
	"github.com/buzz-IT/provider-databricks/config/namespaced/pipeline"
	"github.com/buzz-IT/provider-databricks/config/namespaced/policy_info"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_branch"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_catalog"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_cdf_config"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_data_api"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_database"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_endpoint"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_project"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_role"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_snapshot_schedule"
	"github.com/buzz-IT/provider-databricks/config/namespaced/postgres_synced_table"
	"github.com/buzz-IT/provider-databricks/config/namespaced/provider"
	"github.com/buzz-IT/provider-databricks/config/namespaced/quality_monitor"
	"github.com/buzz-IT/provider-databricks/config/namespaced/quality_monitor_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/query"
	"github.com/buzz-IT/provider-databricks/config/namespaced/recipient"
	"github.com/buzz-IT/provider-databricks/config/namespaced/registered_model"
	"github.com/buzz-IT/provider-databricks/config/namespaced/repo"
	"github.com/buzz-IT/provider-databricks/config/namespaced/restrict_workspace_admins_setting"
	"github.com/buzz-IT/provider-databricks/config/namespaced/rfa_access_request_destinations"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sandbox"
	"github.com/buzz-IT/provider-databricks/config/namespaced/schema"
	"github.com/buzz-IT/provider-databricks/config/namespaced/secret"
	"github.com/buzz-IT/provider-databricks/config/namespaced/secret_acl"
	"github.com/buzz-IT/provider-databricks/config/namespaced/secret_scope"
	"github.com/buzz-IT/provider-databricks/config/namespaced/secret_uc"
	"github.com/buzz-IT/provider-databricks/config/namespaced/service_principal"
	"github.com/buzz-IT/provider-databricks/config/namespaced/service_principal_federation_policy"
	"github.com/buzz-IT/provider-databricks/config/namespaced/service_principal_role"
	"github.com/buzz-IT/provider-databricks/config/namespaced/service_principal_secret"
	"github.com/buzz-IT/provider-databricks/config/namespaced/share"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_alert"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_dashboard"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_endpoint"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_global_config"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_permissions"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_query"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_table"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_visualization"
	"github.com/buzz-IT/provider-databricks/config/namespaced/sql_widget"
	"github.com/buzz-IT/provider-databricks/config/namespaced/storage_credential"
	"github.com/buzz-IT/provider-databricks/config/namespaced/supervisor_agent"
	"github.com/buzz-IT/provider-databricks/config/namespaced/supervisor_agent_tool"
	"github.com/buzz-IT/provider-databricks/config/namespaced/system_schema"
	"github.com/buzz-IT/provider-databricks/config/namespaced/table"
	"github.com/buzz-IT/provider-databricks/config/namespaced/tag_policy"
	"github.com/buzz-IT/provider-databricks/config/namespaced/token"
	"github.com/buzz-IT/provider-databricks/config/namespaced/user"
	"github.com/buzz-IT/provider-databricks/config/namespaced/user_instance_profile"
	"github.com/buzz-IT/provider-databricks/config/namespaced/user_role"
	"github.com/buzz-IT/provider-databricks/config/namespaced/vector_search_endpoint"
	"github.com/buzz-IT/provider-databricks/config/namespaced/vector_search_index"
	"github.com/buzz-IT/provider-databricks/config/namespaced/volume"
	"github.com/buzz-IT/provider-databricks/config/namespaced/warehouses_default_warehouse_override"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_binding"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_conf"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_entity_tag_assignment"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_file"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_iam_direct_group_member_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_iam_group_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_iam_service_principal_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_iam_user_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_iam_workspace_assignment_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_iam_workspace_identity_detail_v2"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_network_option"
	"github.com/buzz-IT/provider-databricks/config/namespaced/workspace_setting_v2"
)

func init() {
	ProviderConfiguration.AddConfig(access_control_rule_set.Configure)
	ProviderConfiguration.AddConfig(account_federation_policy.Configure)
	ProviderConfiguration.AddConfig(account_iam_direct_group_member_v2.Configure)
	ProviderConfiguration.AddConfig(account_iam_group_v2.Configure)
	ProviderConfiguration.AddConfig(account_iam_service_principal_v2.Configure)
	ProviderConfiguration.AddConfig(account_iam_user_v2.Configure)
	ProviderConfiguration.AddConfig(account_iam_workspace_assignment_v2.Configure)
	ProviderConfiguration.AddConfig(account_network_policy.Configure)
	ProviderConfiguration.AddConfig(account_setting_user_preference_v2.Configure)
	ProviderConfiguration.AddConfig(account_setting_v2.Configure)
	ProviderConfiguration.AddConfig(ai_gateway_mcp_service.Configure)
	ProviderConfiguration.AddConfig(ai_gateway_model_provider_service.Configure)
	ProviderConfiguration.AddConfig(ai_gateway_model_service.Configure)
	ProviderConfiguration.AddConfig(ai_search_endpoint.Configure)
	ProviderConfiguration.AddConfig(ai_search_index.Configure)
	ProviderConfiguration.AddConfig(aibi_dashboard_embedding_access_policy_setting.Configure)
	ProviderConfiguration.AddConfig(aibi_dashboard_embedding_approved_domains_setting.Configure)
	ProviderConfiguration.AddConfig(alert.Configure)
	ProviderConfiguration.AddConfig(alert_v2.Configure)
	ProviderConfiguration.AddConfig(app.Configure)
	ProviderConfiguration.AddConfig(app_space.Configure)
	ProviderConfiguration.AddConfig(apps_settings_custom_template.Configure)
	ProviderConfiguration.AddConfig(artifact_allowlist.Configure)
	ProviderConfiguration.AddConfig(automatic_cluster_update_setting.Configure)
	ProviderConfiguration.AddConfig(automatic_cluster_update_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(aws_s3_mount.Configure)
	ProviderConfiguration.AddConfig(azure_adls_gen1_mount.Configure)
	ProviderConfiguration.AddConfig(azure_adls_gen2_mount.Configure)
	ProviderConfiguration.AddConfig(azure_blob_mount.Configure)
	ProviderConfiguration.AddConfig(budget.Configure)
	ProviderConfiguration.AddConfig(budget_policy.Configure)
	ProviderConfiguration.AddConfig(catalog.Configure)
	ProviderConfiguration.AddConfig(catalog_workspace_binding.Configure)
	ProviderConfiguration.AddConfig(cluster.Configure)
	ProviderConfiguration.AddConfig(cluster_policy.Configure)
	ProviderConfiguration.AddConfig(compliance_security_profile_setting.Configure)
	ProviderConfiguration.AddConfig(compliance_security_profile_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(connection.Configure)
	ProviderConfiguration.AddConfig(credential.Configure)
	ProviderConfiguration.AddConfig(custom_app_integration.Configure)
	ProviderConfiguration.AddConfig(dashboard.Configure)
	ProviderConfiguration.AddConfig(data_classification_catalog_config.Configure)
	ProviderConfiguration.AddConfig(data_quality_monitor.Configure)
	ProviderConfiguration.AddConfig(data_quality_refresh.Configure)
	ProviderConfiguration.AddConfig(database_database_catalog.Configure)
	ProviderConfiguration.AddConfig(database_instance.Configure)
	ProviderConfiguration.AddConfig(database_synced_database_table.Configure)
	ProviderConfiguration.AddConfig(dbfs_file.Configure)
	ProviderConfiguration.AddConfig(default_namespace_setting.Configure)
	ProviderConfiguration.AddConfig(directory.Configure)
	ProviderConfiguration.AddConfig(disable_legacy_access_setting.Configure)
	ProviderConfiguration.AddConfig(disable_legacy_dbfs_setting.Configure)
	ProviderConfiguration.AddConfig(disable_legacy_features_setting.Configure)
	ProviderConfiguration.AddConfig(disaster_recovery_failover_group.Configure)
	ProviderConfiguration.AddConfig(disaster_recovery_stable_url.Configure)
	ProviderConfiguration.AddConfig(domain.Configure)
	ProviderConfiguration.AddConfig(endpoint.Configure)
	ProviderConfiguration.AddConfig(enhanced_security_monitoring_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(entitlements.Configure)
	ProviderConfiguration.AddConfig(entity_tag_assignment.Configure)
	ProviderConfiguration.AddConfig(environments_default_workspace_base_environment.Configure)
	ProviderConfiguration.AddConfig(environments_workspace_base_environment.Configure)
	ProviderConfiguration.AddConfig(external_location.Configure)
	ProviderConfiguration.AddConfig(external_metadata.Configure)
	ProviderConfiguration.AddConfig(feature_engineering_feature.Configure)
	ProviderConfiguration.AddConfig(feature_engineering_kafka_config.Configure)
	ProviderConfiguration.AddConfig(feature_engineering_materialized_feature.Configure)
	ProviderConfiguration.AddConfig(file.Configure)
	ProviderConfiguration.AddConfig(git_credential.Configure)
	ProviderConfiguration.AddConfig(global_init_script.Configure)
	ProviderConfiguration.AddConfig(grant.Configure)
	ProviderConfiguration.AddConfig(grants.Configure)
	ProviderConfiguration.AddConfig(group.Configure)
	ProviderConfiguration.AddConfig(group_instance_profile.Configure)
	ProviderConfiguration.AddConfig(group_member.Configure)
	ProviderConfiguration.AddConfig(group_role.Configure)
	ProviderConfiguration.AddConfig(instance_pool.Configure)
	ProviderConfiguration.AddConfig(instance_profile.Configure)
	ProviderConfiguration.AddConfig(ip_access_list.Configure)
	ProviderConfiguration.AddConfig(job.Configure)
	ProviderConfiguration.AddConfig(knowledge_assistant.Configure)
	ProviderConfiguration.AddConfig(knowledge_assistant_knowledge_source.Configure)
	ProviderConfiguration.AddConfig(lakehouse_monitor.Configure)
	ProviderConfiguration.AddConfig(library.Configure)
	ProviderConfiguration.AddConfig(materialized_features_feature_tag.Configure)
	ProviderConfiguration.AddConfig(metastore.Configure)
	ProviderConfiguration.AddConfig(metastore_assignment.Configure)
	ProviderConfiguration.AddConfig(metastore_data_access.Configure)
	ProviderConfiguration.AddConfig(mlflow_experiment.Configure)
	ProviderConfiguration.AddConfig(mlflow_model.Configure)
	ProviderConfiguration.AddConfig(mlflow_webhook.Configure)
	ProviderConfiguration.AddConfig(model_serving.Configure)
	ProviderConfiguration.AddConfig(model_serving_provisioned_throughput.Configure)
	ProviderConfiguration.AddConfig(mount.Configure)
	ProviderConfiguration.AddConfig(mws_credentials.Configure)
	ProviderConfiguration.AddConfig(mws_customer_managed_keys.Configure)
	ProviderConfiguration.AddConfig(mws_log_delivery.Configure)
	ProviderConfiguration.AddConfig(mws_ncc_binding.Configure)
	ProviderConfiguration.AddConfig(mws_ncc_private_endpoint_rule.Configure)
	ProviderConfiguration.AddConfig(mws_network_connectivity_config.Configure)
	ProviderConfiguration.AddConfig(mws_networks.Configure)
	ProviderConfiguration.AddConfig(mws_permission_assignment.Configure)
	ProviderConfiguration.AddConfig(mws_private_access_settings.Configure)
	ProviderConfiguration.AddConfig(mws_storage_configurations.Configure)
	ProviderConfiguration.AddConfig(mws_vpc_endpoint.Configure)
	ProviderConfiguration.AddConfig(mws_workspaces.Configure)
	ProviderConfiguration.AddConfig(notebook.Configure)
	ProviderConfiguration.AddConfig(notification_destination.Configure)
	ProviderConfiguration.AddConfig(obo_token.Configure)
	ProviderConfiguration.AddConfig(online_store.Configure)
	ProviderConfiguration.AddConfig(online_table.Configure)
	ProviderConfiguration.AddConfig(permission_assignment.Configure)
	ProviderConfiguration.AddConfig(permissions.Configure)
	ProviderConfiguration.AddConfig(pipeline.Configure)
	ProviderConfiguration.AddConfig(policy_info.Configure)
	ProviderConfiguration.AddConfig(postgres_branch.Configure)
	ProviderConfiguration.AddConfig(postgres_catalog.Configure)
	ProviderConfiguration.AddConfig(postgres_cdf_config.Configure)
	ProviderConfiguration.AddConfig(postgres_data_api.Configure)
	ProviderConfiguration.AddConfig(postgres_database.Configure)
	ProviderConfiguration.AddConfig(postgres_endpoint.Configure)
	ProviderConfiguration.AddConfig(postgres_project.Configure)
	ProviderConfiguration.AddConfig(postgres_role.Configure)
	ProviderConfiguration.AddConfig(postgres_snapshot_schedule.Configure)
	ProviderConfiguration.AddConfig(postgres_synced_table.Configure)
	ProviderConfiguration.AddConfig(provider.Configure)
	ProviderConfiguration.AddConfig(quality_monitor.Configure)
	ProviderConfiguration.AddConfig(quality_monitor_v2.Configure)
	ProviderConfiguration.AddConfig(query.Configure)
	ProviderConfiguration.AddConfig(recipient.Configure)
	ProviderConfiguration.AddConfig(registered_model.Configure)
	ProviderConfiguration.AddConfig(repo.Configure)
	ProviderConfiguration.AddConfig(restrict_workspace_admins_setting.Configure)
	ProviderConfiguration.AddConfig(rfa_access_request_destinations.Configure)
	ProviderConfiguration.AddConfig(sandbox.Configure)
	ProviderConfiguration.AddConfig(schema.Configure)
	ProviderConfiguration.AddConfig(secret.Configure)
	ProviderConfiguration.AddConfig(secret_acl.Configure)
	ProviderConfiguration.AddConfig(secret_scope.Configure)
	ProviderConfiguration.AddConfig(secret_uc.Configure)
	ProviderConfiguration.AddConfig(service_principal.Configure)
	ProviderConfiguration.AddConfig(service_principal_federation_policy.Configure)
	ProviderConfiguration.AddConfig(service_principal_role.Configure)
	ProviderConfiguration.AddConfig(service_principal_secret.Configure)
	ProviderConfiguration.AddConfig(share.Configure)
	ProviderConfiguration.AddConfig(sql_alert.Configure)
	ProviderConfiguration.AddConfig(sql_dashboard.Configure)
	ProviderConfiguration.AddConfig(sql_endpoint.Configure)
	ProviderConfiguration.AddConfig(sql_global_config.Configure)
	ProviderConfiguration.AddConfig(sql_permissions.Configure)
	ProviderConfiguration.AddConfig(sql_query.Configure)
	ProviderConfiguration.AddConfig(sql_table.Configure)
	ProviderConfiguration.AddConfig(sql_visualization.Configure)
	ProviderConfiguration.AddConfig(sql_widget.Configure)
	ProviderConfiguration.AddConfig(storage_credential.Configure)
	ProviderConfiguration.AddConfig(supervisor_agent.Configure)
	ProviderConfiguration.AddConfig(supervisor_agent_tool.Configure)
	ProviderConfiguration.AddConfig(system_schema.Configure)
	ProviderConfiguration.AddConfig(table.Configure)
	ProviderConfiguration.AddConfig(tag_policy.Configure)
	ProviderConfiguration.AddConfig(token.Configure)
	ProviderConfiguration.AddConfig(user.Configure)
	ProviderConfiguration.AddConfig(user_instance_profile.Configure)
	ProviderConfiguration.AddConfig(user_role.Configure)
	ProviderConfiguration.AddConfig(vector_search_endpoint.Configure)
	ProviderConfiguration.AddConfig(vector_search_index.Configure)
	ProviderConfiguration.AddConfig(volume.Configure)
	ProviderConfiguration.AddConfig(warehouses_default_warehouse_override.Configure)
	ProviderConfiguration.AddConfig(workspace_binding.Configure)
	ProviderConfiguration.AddConfig(workspace_conf.Configure)
	ProviderConfiguration.AddConfig(workspace_entity_tag_assignment.Configure)
	ProviderConfiguration.AddConfig(workspace_file.Configure)
	ProviderConfiguration.AddConfig(workspace_iam_direct_group_member_v2.Configure)
	ProviderConfiguration.AddConfig(workspace_iam_group_v2.Configure)
	ProviderConfiguration.AddConfig(workspace_iam_service_principal_v2.Configure)
	ProviderConfiguration.AddConfig(workspace_iam_user_v2.Configure)
	ProviderConfiguration.AddConfig(workspace_iam_workspace_assignment_v2.Configure)
	ProviderConfiguration.AddConfig(workspace_iam_workspace_identity_detail_v2.Configure)
	ProviderConfiguration.AddConfig(workspace_network_option.Configure)
	ProviderConfiguration.AddConfig(workspace_setting_v2.Configure)
}
