// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AIGatewayMcpServiceInitParameters struct {

	// User-provided description
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Connection, tool selectors, and rate limits. Required on Create. On Update,
	// provide this field when update_mask contains config or one of its
	// subpaths
	Config *ConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// Name for the MCP service, e.g. "my_mcp_service"
	McpServiceID *string `json:"mcpServiceId,omitempty" tf:"mcp_service_id,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type AIGatewayMcpServiceObservation struct {

	// User-provided description
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Connection, tool selectors, and rate limits. Required on Create. On Update,
	// provide this field when update_mask contains config or one of its
	// subpaths
	Config *ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// Time the MCP service was created
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Creator identity
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Owner of the MCP service
	EffectiveOwner *string `json:"effectiveOwner,omitempty" tf:"effective_owner,omitempty"`

	// Optimistic concurrency token returned on every read. To make an Update or
	// Delete conditional, pass the last-read value in that request's etag
	// field. In REST responses, this value is a base64 string; URL-encode it when
	// setting the etag query parameter
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name for the MCP service, e.g. "my_mcp_service"
	McpServiceID *string `json:"mcpServiceId,omitempty" tf:"mcp_service_id,omitempty"`

	// Metastore hosting the MCP service
	MetastoreID *string `json:"metastoreId,omitempty" tf:"metastore_id,omitempty"`

	// Resource name of the Unity Catalog connection used to access the MCP
	// server, in the form connections/{catalog}.{schema}.{connection}
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Time the MCP service was last modified
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`

	// Identity of the last updater
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`
}

type AIGatewayMcpServiceParameters struct {

	// User-provided description
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Connection, tool selectors, and rate limits. Required on Create. On Update,
	// provide this field when update_mask contains config or one of its
	// subpaths
	// +kubebuilder:validation:Optional
	Config *ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// Name for the MCP service, e.g. "my_mcp_service"
	// +kubebuilder:validation:Optional
	McpServiceID *string `json:"mcpServiceId,omitempty" tf:"mcp_service_id,omitempty"`

	// Name of the parent schema.
	// Format: schemas/{catalog}.{schema}.
	// Each {...} component is capped at 255 characters individually
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type ConfigInitParameters struct {

	// Tool names or prefix patterns to expose from the MCP server. Use exact
	// tool names or prefix patterns such as read_*. An empty list exposes all
	// tools. At most 1,024 selectors are allowed, and each selector can contain
	// at most 256 characters
	IncludeToolSelectors []*string `json:"includeToolSelectors,omitempty" tf:"include_tool_selectors,omitempty"`

	// Rate limits for tool invocations. Supported scopes are user, group, service
	// principal, the service as a whole, and each user by default. Request and
	// token limits are supported. Empty when no rate limit is configured
	RateLimits []RateLimitsInitParameters `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Unity Catalog connection referencing the MCP server. Required on Create
	SourceConnection *SourceConnectionInitParameters `json:"sourceConnection,omitempty" tf:"source_connection,omitempty"`
}

type ConfigObservation struct {

	// Tool names or prefix patterns to expose from the MCP server. Use exact
	// tool names or prefix patterns such as read_*. An empty list exposes all
	// tools. At most 1,024 selectors are allowed, and each selector can contain
	// at most 256 characters
	IncludeToolSelectors []*string `json:"includeToolSelectors,omitempty" tf:"include_tool_selectors,omitempty"`

	// Rate limits for tool invocations. Supported scopes are user, group, service
	// principal, the service as a whole, and each user by default. Request and
	// token limits are supported. Empty when no rate limit is configured
	RateLimits []RateLimitsObservation `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Unity Catalog connection referencing the MCP server. Required on Create
	SourceConnection *SourceConnectionObservation `json:"sourceConnection,omitempty" tf:"source_connection,omitempty"`
}

type ConfigParameters struct {

	// Tool names or prefix patterns to expose from the MCP server. Use exact
	// tool names or prefix patterns such as read_*. An empty list exposes all
	// tools. At most 1,024 selectors are allowed, and each selector can contain
	// at most 256 characters
	// +kubebuilder:validation:Optional
	IncludeToolSelectors []*string `json:"includeToolSelectors,omitempty" tf:"include_tool_selectors,omitempty"`

	// Rate limits for tool invocations. Supported scopes are user, group, service
	// principal, the service as a whole, and each user by default. Request and
	// token limits are supported. Empty when no rate limit is configured
	// +kubebuilder:validation:Optional
	RateLimits []RateLimitsParameters `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Unity Catalog connection referencing the MCP server. Required on Create
	// +kubebuilder:validation:Optional
	SourceConnection *SourceConnectionParameters `json:"sourceConnection,omitempty" tf:"source_connection,omitempty"`
}

type ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type RateLimitsInitParameters struct {

	// Scope of the rate limit. Depending on this value, the limit applies to a
	// principal, the service as a whole, or each user by default. Possible values are: RATE_LIMIT_KEY_SERVICE, RATE_LIMIT_KEY_SERVICE_PRINCIPAL, RATE_LIMIT_KEY_USER, RATE_LIMIT_KEY_USER_DEFAULT, RATE_LIMIT_KEY_USER_GROUP
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Principal this limit applies to: user email, group name, or service
	// principal application ID. Required when key applies to a user, group, or
	// service principal; otherwise it must be unset
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Renewal period. Possible values are: RATE_LIMIT_RENEWAL_PERIOD_HOUR, RATE_LIMIT_RENEWAL_PERIOD_MINUTE
	RenewalPeriod *string `json:"renewalPeriod,omitempty" tf:"renewal_period,omitempty"`

	// Maximum requests allowed in one renewal period. Leave unset for no request
	// limit. Set to 0 to deny all requests
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`

	// Maximum tokens allowed in one renewal period. Leave unset for no token
	// limit. Set to 0 to deny all requests
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type RateLimitsObservation struct {

	// Scope of the rate limit. Depending on this value, the limit applies to a
	// principal, the service as a whole, or each user by default. Possible values are: RATE_LIMIT_KEY_SERVICE, RATE_LIMIT_KEY_SERVICE_PRINCIPAL, RATE_LIMIT_KEY_USER, RATE_LIMIT_KEY_USER_DEFAULT, RATE_LIMIT_KEY_USER_GROUP
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Principal this limit applies to: user email, group name, or service
	// principal application ID. Required when key applies to a user, group, or
	// service principal; otherwise it must be unset
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Renewal period. Possible values are: RATE_LIMIT_RENEWAL_PERIOD_HOUR, RATE_LIMIT_RENEWAL_PERIOD_MINUTE
	RenewalPeriod *string `json:"renewalPeriod,omitempty" tf:"renewal_period,omitempty"`

	// Maximum requests allowed in one renewal period. Leave unset for no request
	// limit. Set to 0 to deny all requests
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`

	// Maximum tokens allowed in one renewal period. Leave unset for no token
	// limit. Set to 0 to deny all requests
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type RateLimitsParameters struct {

	// Scope of the rate limit. Depending on this value, the limit applies to a
	// principal, the service as a whole, or each user by default. Possible values are: RATE_LIMIT_KEY_SERVICE, RATE_LIMIT_KEY_SERVICE_PRINCIPAL, RATE_LIMIT_KEY_USER, RATE_LIMIT_KEY_USER_DEFAULT, RATE_LIMIT_KEY_USER_GROUP
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// Principal this limit applies to: user email, group name, or service
	// principal application ID. Required when key applies to a user, group, or
	// service principal; otherwise it must be unset
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Renewal period. Possible values are: RATE_LIMIT_RENEWAL_PERIOD_HOUR, RATE_LIMIT_RENEWAL_PERIOD_MINUTE
	// +kubebuilder:validation:Optional
	RenewalPeriod *string `json:"renewalPeriod" tf:"renewal_period,omitempty"`

	// Maximum requests allowed in one renewal period. Leave unset for no request
	// limit. Set to 0 to deny all requests
	// +kubebuilder:validation:Optional
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`

	// Maximum tokens allowed in one renewal period. Leave unset for no token
	// limit. Set to 0 to deny all requests
	// +kubebuilder:validation:Optional
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type SourceConnectionInitParameters struct {

	// Resource name of the Unity Catalog connection used to access the MCP
	// server, in the form connections/{catalog}.{schema}.{connection}
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourceConnectionObservation struct {

	// Whether the referenced connection has been deleted. The MCP service keeps
	// the reference so callers can identify the broken dependency; tool
	// invocation fails until the source connection is updated
	IsDeleted *bool `json:"isDeleted,omitempty" tf:"is_deleted,omitempty"`

	// Resource name of the Unity Catalog connection used to access the MCP
	// server, in the form connections/{catalog}.{schema}.{connection}
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourceConnectionParameters struct {

	// Resource name of the Unity Catalog connection used to access the MCP
	// server, in the form connections/{catalog}.{schema}.{connection}
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

// AIGatewayMcpServiceSpec defines the desired state of AIGatewayMcpService
type AIGatewayMcpServiceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AIGatewayMcpServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AIGatewayMcpServiceInitParameters `json:"initProvider,omitempty"`
}

// AIGatewayMcpServiceStatus defines the observed state of AIGatewayMcpService.
type AIGatewayMcpServiceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AIGatewayMcpServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AIGatewayMcpService is the Schema for the AIGatewayMcpServices API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type AIGatewayMcpService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mcpServiceId) || (has(self.initProvider) && has(self.initProvider.mcpServiceId))",message="spec.forProvider.mcpServiceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parent) || (has(self.initProvider) && has(self.initProvider.parent))",message="spec.forProvider.parent is a required parameter"
	Spec   AIGatewayMcpServiceSpec   `json:"spec"`
	Status AIGatewayMcpServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AIGatewayMcpServiceList contains a list of AIGatewayMcpServices
type AIGatewayMcpServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIGatewayMcpService `json:"items"`
}

// Repository type metadata.
var (
	AIGatewayMcpService_Kind             = "AIGatewayMcpService"
	AIGatewayMcpService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AIGatewayMcpService_Kind}.String()
	AIGatewayMcpService_KindAPIVersion   = AIGatewayMcpService_Kind + "." + CRDGroupVersion.String()
	AIGatewayMcpService_GroupVersionKind = CRDGroupVersion.WithKind(AIGatewayMcpService_Kind)
)

func init() {
	SchemeBuilder.Register(&AIGatewayMcpService{}, &AIGatewayMcpServiceList{})
}
