# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: apps.databricks.m.crossplane.io/v1beta1
kind: AppsSettingsCustomTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: apps/v1beta1/appssettingscustomtemplate
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    description: A sample custom app template
    gitProvider: github
    gitRepo: https://github.com/example/repo.git
    manifest:
      name: my-custom-app
      version: 1
    name: my-custom-template
    path: path-to-template
