// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccountIAMServicePrincipalV2InitParameters struct {

	// The activity status of a service principal in a Databricks account. Possible values are: ACTIVE, INACTIVE
	AccountSpStatus *string `json:"accountSpStatus,omitempty" tf:"account_sp_status,omitempty"`

	// Application ID of the service principal. Set at creation time and cannot be changed
	// afterwards; when omitted, the server generates one
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Display name of the service principal
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// ExternalId of the service principal in the customer's IdP
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`
}

type AccountIAMServicePrincipalV2Observation struct {

	// The parent account ID for the service principal in Databricks
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The activity status of a service principal in a Databricks account. Possible values are: ACTIVE, INACTIVE
	AccountSpStatus *string `json:"accountSpStatus,omitempty" tf:"account_sp_status,omitempty"`

	// Application ID of the service principal. Set at creation time and cannot be changed
	// afterwards; when omitted, the server generates one
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Display name of the service principal
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// ExternalId of the service principal in the customer's IdP
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Internal service principal ID of the service principal in Databricks
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`
}

type AccountIAMServicePrincipalV2Parameters struct {

	// The activity status of a service principal in a Databricks account. Possible values are: ACTIVE, INACTIVE
	// +kubebuilder:validation:Optional
	AccountSpStatus *string `json:"accountSpStatus,omitempty" tf:"account_sp_status,omitempty"`

	// Application ID of the service principal. Set at creation time and cannot be changed
	// afterwards; when omitted, the server generates one
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Display name of the service principal
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// ExternalId of the service principal in the customer's IdP
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`
}

// AccountIAMServicePrincipalV2Spec defines the desired state of AccountIAMServicePrincipalV2
type AccountIAMServicePrincipalV2Spec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AccountIAMServicePrincipalV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountIAMServicePrincipalV2InitParameters `json:"initProvider,omitempty"`
}

// AccountIAMServicePrincipalV2Status defines the observed state of AccountIAMServicePrincipalV2.
type AccountIAMServicePrincipalV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AccountIAMServicePrincipalV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountIAMServicePrincipalV2 is the Schema for the AccountIAMServicePrincipalV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type AccountIAMServicePrincipalV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountSpStatus) || (has(self.initProvider) && has(self.initProvider.accountSpStatus))",message="spec.forProvider.accountSpStatus is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   AccountIAMServicePrincipalV2Spec   `json:"spec"`
	Status AccountIAMServicePrincipalV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountIAMServicePrincipalV2List contains a list of AccountIAMServicePrincipalV2s
type AccountIAMServicePrincipalV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountIAMServicePrincipalV2 `json:"items"`
}

// Repository type metadata.
var (
	AccountIAMServicePrincipalV2_Kind             = "AccountIAMServicePrincipalV2"
	AccountIAMServicePrincipalV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountIAMServicePrincipalV2_Kind}.String()
	AccountIAMServicePrincipalV2_KindAPIVersion   = AccountIAMServicePrincipalV2_Kind + "." + CRDGroupVersion.String()
	AccountIAMServicePrincipalV2_GroupVersionKind = CRDGroupVersion.WithKind(AccountIAMServicePrincipalV2_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountIAMServicePrincipalV2{}, &AccountIAMServicePrincipalV2List{})
}
