// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WorkspaceIAMGroupV2InitParameters struct {

	// ExternalId of the group in the customer's IdP
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Display name of the group
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMGroupV2ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type WorkspaceIAMGroupV2Observation struct {

	// The parent account ID for group in Databricks
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// ExternalId of the group in the customer's IdP
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Internal group ID of the group in Databricks
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Display name of the group
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMGroupV2ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type WorkspaceIAMGroupV2Parameters struct {

	// ExternalId of the group in the customer's IdP
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// Display name of the group
	// +kubebuilder:validation:Optional
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *WorkspaceIAMGroupV2ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type WorkspaceIAMGroupV2ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMGroupV2ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMGroupV2ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

// WorkspaceIAMGroupV2Spec defines the desired state of WorkspaceIAMGroupV2
type WorkspaceIAMGroupV2Spec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   WorkspaceIAMGroupV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceIAMGroupV2InitParameters `json:"initProvider,omitempty"`
}

// WorkspaceIAMGroupV2Status defines the observed state of WorkspaceIAMGroupV2.
type WorkspaceIAMGroupV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WorkspaceIAMGroupV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceIAMGroupV2 is the Schema for the WorkspaceIAMGroupV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type WorkspaceIAMGroupV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkspaceIAMGroupV2Spec   `json:"spec"`
	Status            WorkspaceIAMGroupV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceIAMGroupV2List contains a list of WorkspaceIAMGroupV2s
type WorkspaceIAMGroupV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceIAMGroupV2 `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceIAMGroupV2_Kind             = "WorkspaceIAMGroupV2"
	WorkspaceIAMGroupV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceIAMGroupV2_Kind}.String()
	WorkspaceIAMGroupV2_KindAPIVersion   = WorkspaceIAMGroupV2_Kind + "." + CRDGroupVersion.String()
	WorkspaceIAMGroupV2_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceIAMGroupV2_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceIAMGroupV2{}, &WorkspaceIAMGroupV2List{})
}
