// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WarehousesDefaultWarehouseOverrideInitParameters struct {

	// The ID component of the resource name (user ID)
	DefaultWarehouseOverrideID *string `json:"defaultWarehouseOverrideId,omitempty" tf:"default_warehouse_override_id,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WarehousesDefaultWarehouseOverrideProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// The type of override behavior. Possible values are: CUSTOM, LAST_SELECTED
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The specific warehouse ID when type is CUSTOM.
	// Not set for LAST_SELECTED type
	// +crossplane:generate:reference:type=github.com/buzz-IT/provider-databricks/apis/namespaced/sql/v1beta1.SQLEndpoint
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	WarehouseID *string `json:"warehouseId,omitempty" tf:"warehouse_id,omitempty"`

	// Reference to a SQLEndpoint in sql to populate warehouseId.
	// +kubebuilder:validation:Optional
	WarehouseIDRef *v2.NamespacedReference `json:"warehouseIdRef,omitempty" tf:"-"`

	// Selector for a SQLEndpoint in sql to populate warehouseId.
	// +kubebuilder:validation:Optional
	WarehouseIDSelector *v2.NamespacedSelector `json:"warehouseIdSelector,omitempty" tf:"-"`
}

type WarehousesDefaultWarehouseOverrideObservation struct {

	// The ID component of the resource name (user ID)
	DefaultWarehouseOverrideID *string `json:"defaultWarehouseOverrideId,omitempty" tf:"default_warehouse_override_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The resource name of the default warehouse override.
	// Format: default-warehouse-overrides/{default_warehouse_override_id}
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WarehousesDefaultWarehouseOverrideProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// The type of override behavior. Possible values are: CUSTOM, LAST_SELECTED
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The specific warehouse ID when type is CUSTOM.
	// Not set for LAST_SELECTED type
	WarehouseID *string `json:"warehouseId,omitempty" tf:"warehouse_id,omitempty"`
}

type WarehousesDefaultWarehouseOverrideParameters struct {

	// The ID component of the resource name (user ID)
	// +kubebuilder:validation:Optional
	DefaultWarehouseOverrideID *string `json:"defaultWarehouseOverrideId,omitempty" tf:"default_warehouse_override_id,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *WarehousesDefaultWarehouseOverrideProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// The type of override behavior. Possible values are: CUSTOM, LAST_SELECTED
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The specific warehouse ID when type is CUSTOM.
	// Not set for LAST_SELECTED type
	// +crossplane:generate:reference:type=github.com/buzz-IT/provider-databricks/apis/namespaced/sql/v1beta1.SQLEndpoint
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	WarehouseID *string `json:"warehouseId,omitempty" tf:"warehouse_id,omitempty"`

	// Reference to a SQLEndpoint in sql to populate warehouseId.
	// +kubebuilder:validation:Optional
	WarehouseIDRef *v2.NamespacedReference `json:"warehouseIdRef,omitempty" tf:"-"`

	// Selector for a SQLEndpoint in sql to populate warehouseId.
	// +kubebuilder:validation:Optional
	WarehouseIDSelector *v2.NamespacedSelector `json:"warehouseIdSelector,omitempty" tf:"-"`
}

type WarehousesDefaultWarehouseOverrideProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WarehousesDefaultWarehouseOverrideProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WarehousesDefaultWarehouseOverrideProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

// WarehousesDefaultWarehouseOverrideSpec defines the desired state of WarehousesDefaultWarehouseOverride
type WarehousesDefaultWarehouseOverrideSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WarehousesDefaultWarehouseOverrideParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WarehousesDefaultWarehouseOverrideInitParameters `json:"initProvider,omitempty"`
}

// WarehousesDefaultWarehouseOverrideStatus defines the observed state of WarehousesDefaultWarehouseOverride.
type WarehousesDefaultWarehouseOverrideStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WarehousesDefaultWarehouseOverrideObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WarehousesDefaultWarehouseOverride is the Schema for the WarehousesDefaultWarehouseOverrides API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type WarehousesDefaultWarehouseOverride struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.defaultWarehouseOverrideId) || (has(self.initProvider) && has(self.initProvider.defaultWarehouseOverrideId))",message="spec.forProvider.defaultWarehouseOverrideId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   WarehousesDefaultWarehouseOverrideSpec   `json:"spec"`
	Status WarehousesDefaultWarehouseOverrideStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WarehousesDefaultWarehouseOverrideList contains a list of WarehousesDefaultWarehouseOverrides
type WarehousesDefaultWarehouseOverrideList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WarehousesDefaultWarehouseOverride `json:"items"`
}

// Repository type metadata.
var (
	WarehousesDefaultWarehouseOverride_Kind             = "WarehousesDefaultWarehouseOverride"
	WarehousesDefaultWarehouseOverride_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WarehousesDefaultWarehouseOverride_Kind}.String()
	WarehousesDefaultWarehouseOverride_KindAPIVersion   = WarehousesDefaultWarehouseOverride_Kind + "." + CRDGroupVersion.String()
	WarehousesDefaultWarehouseOverride_GroupVersionKind = CRDGroupVersion.WithKind(WarehousesDefaultWarehouseOverride_Kind)
)

func init() {
	SchemeBuilder.Register(&WarehousesDefaultWarehouseOverride{}, &WarehousesDefaultWarehouseOverrideList{})
}
