# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: workspace.databricks.m.crossplane.io/v1beta1
kind: Directory
metadata:
  annotations:
    meta.upbound.io/example-id: e2e/namespaced/directory
    uptest.upbound.io/timeout: "1200"
  labels:
    testing.upbound.io/example-name: e2e-ns-directory
  name: e2e-ns-directory
  namespace: upbound-system
spec:
  forProvider:
    path: ${data.directoryPath}/ns-${Rand.RFC1123Subdomain}
