# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: security.databricks.m.crossplane.io/v1beta1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: e2e/namespaced/secretscope
    uptest.upbound.io/timeout: "1200"
  labels:
    testing.upbound.io/example-name: e2e-ns-secretscope
  name: e2e-ns-secretscope
  namespace: upbound-system
spec:
  forProvider:
    name: e2ens-${Rand.RFC1123Subdomain}
