// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SandboxInitParameters struct {

	// Human-readable display label for the sandbox. At most 256 bytes
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *SandboxProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Client-supplied ID that becomes the final path segment of the resource name
	SandboxID *string `json:"sandboxId,omitempty" tf:"sandbox_id,omitempty"`

	// The desired configuration of the sandbox, supplied by the caller at creation time
	Spec *SandboxSpecInitParameters `json:"spec,omitempty" tf:"spec,omitempty"`
}

type SandboxObservation struct {

	// Output only. The creation time of the sandbox
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Human-readable display label for the sandbox. At most 256 bytes
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The AIP-compliant resource name, such as "sandboxes/my-sandbox"
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *SandboxProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Client-supplied ID that becomes the final path segment of the resource name
	SandboxID *string `json:"sandboxId,omitempty" tf:"sandbox_id,omitempty"`

	// The desired configuration of the sandbox, supplied by the caller at creation time
	Spec *SandboxSpecObservation `json:"spec,omitempty" tf:"spec,omitempty"`

	// The observed runtime state of the sandbox, populated by the server
	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// Output only. The last update time of the sandbox metadata and spec
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type SandboxParameters struct {

	// Human-readable display label for the sandbox. At most 256 bytes
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *SandboxProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Client-supplied ID that becomes the final path segment of the resource name
	// +kubebuilder:validation:Optional
	SandboxID *string `json:"sandboxId,omitempty" tf:"sandbox_id,omitempty"`

	// The desired configuration of the sandbox, supplied by the caller at creation time
	// +kubebuilder:validation:Optional
	Spec *SandboxSpecParameters `json:"spec,omitempty" tf:"spec,omitempty"`
}

type SandboxProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type SandboxProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type SandboxProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type SandboxSpecInitParameters struct {

	// Compute configuration (size, inactivity timeout) requested for the sandbox
	Compute *SpecComputeInitParameters `json:"compute,omitempty" tf:"compute,omitempty"`
}

type SandboxSpecObservation struct {

	// Compute configuration (size, inactivity timeout) requested for the sandbox
	Compute *SpecComputeObservation `json:"compute,omitempty" tf:"compute,omitempty"`
}

type SandboxSpecParameters struct {

	// Compute configuration (size, inactivity timeout) requested for the sandbox
	// +kubebuilder:validation:Optional
	Compute *SpecComputeParameters `json:"compute,omitempty" tf:"compute,omitempty"`
}

type SpecComputeInitParameters struct {

	// Idle duration after which the sandbox is automatically terminated
	InactivityTimeout *string `json:"inactivityTimeout,omitempty" tf:"inactivity_timeout,omitempty"`
}

type SpecComputeObservation struct {

	// Idle duration after which the sandbox is automatically terminated
	InactivityTimeout *string `json:"inactivityTimeout,omitempty" tf:"inactivity_timeout,omitempty"`
}

type SpecComputeParameters struct {

	// Idle duration after which the sandbox is automatically terminated
	// +kubebuilder:validation:Optional
	InactivityTimeout *string `json:"inactivityTimeout,omitempty" tf:"inactivity_timeout,omitempty"`
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// Lifecycle state of the sandbox. Possible values are: SANDBOX_STATE_PENDING, SANDBOX_STATE_RUNNING, SANDBOX_STATE_STOPPED, SANDBOX_STATE_STOPPING
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type StatusParameters struct {
}

// SandboxSpec defines the desired state of Sandbox
type SandboxSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SandboxParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SandboxInitParameters `json:"initProvider,omitempty"`
}

// SandboxStatus defines the observed state of Sandbox.
type SandboxStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SandboxObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Sandbox is the Schema for the Sandboxs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type Sandbox struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sandboxId) || (has(self.initProvider) && has(self.initProvider.sandboxId))",message="spec.forProvider.sandboxId is a required parameter"
	Spec   SandboxSpec   `json:"spec"`
	Status SandboxStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SandboxList contains a list of Sandboxs
type SandboxList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Sandbox `json:"items"`
}

// Repository type metadata.
var (
	Sandbox_Kind             = "Sandbox"
	Sandbox_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Sandbox_Kind}.String()
	Sandbox_KindAPIVersion   = Sandbox_Kind + "." + CRDGroupVersion.String()
	Sandbox_GroupVersionKind = CRDGroupVersion.WithKind(Sandbox_Kind)
)

func init() {
	SchemeBuilder.Register(&Sandbox{}, &SandboxList{})
}
