# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: serving.databricks.m.crossplane.io/v1beta1
kind: ModelServingProvisionedThroughput
metadata:
  annotations:
    meta.upbound.io/example-id: serving/v1beta1/modelservingprovisionedthroughput
  labels:
    testing.upbound.io/example-name: llama
  name: llama
  namespace: upbound-system
spec:
  forProvider:
    aiGateway:
      usageTrackingConfig:
        enabled: true
    config:
      servedEntities:
      - entityName: system.ai.llama-4-maverick
        entityVersion: "1"
        provisionedModelUnits: 100
