#!/usr/bin/env bash
# Build the uptest datasource YAML from env/vars.
set -euo pipefail

out="${UPTEST_DATASOURCE_PATH:-.work/uptest-datasource.yaml}"
mkdir -p "$(dirname "${out}")"

python3 - <<'PY'
import os
from pathlib import Path

out = os.environ.get("UPTEST_DATASOURCE_PATH", ".work/uptest-datasource.yaml")

def val(*names, default=""):
    for name in names:
        v = os.environ.get(name, "").strip()
        if v:
            return v
    return default

data = {
    "nodeTypeId": val("DATABRICKS_NODE_TYPE_ID", default="Standard_DS3_v2"),
    "sparkVersion": val("DATABRICKS_SPARK_VERSION", default="15.4.x-scala2.12"),
    "catalogName": val("DATABRICKS_CATALOG_NAME", default="uptest_e2e"),
    "schemaName": val("DATABRICKS_SCHEMA_NAME", default="uptest"),
    "directoryPath": val("DATABRICKS_DIRECTORY_PATH", default="/uptest-e2e"),
    "sqlEndpointSize": val("DATABRICKS_SQL_ENDPOINT_SIZE", default="2X-Small"),
    "groupDisplayName": val("DATABRICKS_GROUP_DISPLAY_NAME", default="uptest-e2e-group"),
}

lines = ["# Generated by cluster/test/render-datasource.sh", "# Do not commit."]
for k, v in data.items():
    # YAML double-quoted string; escape backslash and quote.
    escaped = v.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'{k}: "{escaped}"')

path = Path(out)
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text("\n".join(lines) + "\n")
print(path)
PY
