//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildInstanceRefsInitParameters) DeepCopyInto(out *ChildInstanceRefsInitParameters) {
	*out = *in
	if in.BranchTime != nil {
		in, out := &in.BranchTime, &out.BranchTime
		*out = new(string)
		**out = **in
	}
	if in.Lsn != nil {
		in, out := &in.Lsn, &out.Lsn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildInstanceRefsInitParameters.
func (in *ChildInstanceRefsInitParameters) DeepCopy() *ChildInstanceRefsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ChildInstanceRefsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildInstanceRefsObservation) DeepCopyInto(out *ChildInstanceRefsObservation) {
	*out = *in
	if in.BranchTime != nil {
		in, out := &in.BranchTime, &out.BranchTime
		*out = new(string)
		**out = **in
	}
	if in.EffectiveLsn != nil {
		in, out := &in.EffectiveLsn, &out.EffectiveLsn
		*out = new(string)
		**out = **in
	}
	if in.Lsn != nil {
		in, out := &in.Lsn, &out.Lsn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildInstanceRefsObservation.
func (in *ChildInstanceRefsObservation) DeepCopy() *ChildInstanceRefsObservation {
	if in == nil {
		return nil
	}
	out := new(ChildInstanceRefsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildInstanceRefsParameters) DeepCopyInto(out *ChildInstanceRefsParameters) {
	*out = *in
	if in.BranchTime != nil {
		in, out := &in.BranchTime, &out.BranchTime
		*out = new(string)
		**out = **in
	}
	if in.Lsn != nil {
		in, out := &in.Lsn, &out.Lsn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildInstanceRefsParameters.
func (in *ChildInstanceRefsParameters) DeepCopy() *ChildInstanceRefsParameters {
	if in == nil {
		return nil
	}
	out := new(ChildInstanceRefsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousUpdateStatusInitParameters) DeepCopyInto(out *ContinuousUpdateStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousUpdateStatusInitParameters.
func (in *ContinuousUpdateStatusInitParameters) DeepCopy() *ContinuousUpdateStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(ContinuousUpdateStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousUpdateStatusObservation) DeepCopyInto(out *ContinuousUpdateStatusObservation) {
	*out = *in
	if in.InitialPipelineSyncProgress != nil {
		in, out := &in.InitialPipelineSyncProgress, &out.InitialPipelineSyncProgress
		*out = new(InitialPipelineSyncProgressObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastProcessedCommitVersion != nil {
		in, out := &in.LastProcessedCommitVersion, &out.LastProcessedCommitVersion
		*out = new(float64)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousUpdateStatusObservation.
func (in *ContinuousUpdateStatusObservation) DeepCopy() *ContinuousUpdateStatusObservation {
	if in == nil {
		return nil
	}
	out := new(ContinuousUpdateStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousUpdateStatusParameters) DeepCopyInto(out *ContinuousUpdateStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousUpdateStatusParameters.
func (in *ContinuousUpdateStatusParameters) DeepCopy() *ContinuousUpdateStatusParameters {
	if in == nil {
		return nil
	}
	out := new(ContinuousUpdateStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomTagsInitParameters) DeepCopyInto(out *CustomTagsInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomTagsInitParameters.
func (in *CustomTagsInitParameters) DeepCopy() *CustomTagsInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomTagsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomTagsObservation) DeepCopyInto(out *CustomTagsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomTagsObservation.
func (in *CustomTagsObservation) DeepCopy() *CustomTagsObservation {
	if in == nil {
		return nil
	}
	out := new(CustomTagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomTagsParameters) DeepCopyInto(out *CustomTagsParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomTagsParameters.
func (in *CustomTagsParameters) DeepCopy() *CustomTagsParameters {
	if in == nil {
		return nil
	}
	out := new(CustomTagsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSynchronizationStatusInitParameters) DeepCopyInto(out *DataSynchronizationStatusInitParameters) {
	*out = *in
	if in.ContinuousUpdateStatus != nil {
		in, out := &in.ContinuousUpdateStatus, &out.ContinuousUpdateStatus
		*out = new(ContinuousUpdateStatusInitParameters)
		**out = **in
	}
	if in.FailedStatus != nil {
		in, out := &in.FailedStatus, &out.FailedStatus
		*out = new(FailedStatusInitParameters)
		**out = **in
	}
	if in.ProvisioningStatus != nil {
		in, out := &in.ProvisioningStatus, &out.ProvisioningStatus
		*out = new(ProvisioningStatusInitParameters)
		**out = **in
	}
	if in.TriggeredUpdateStatus != nil {
		in, out := &in.TriggeredUpdateStatus, &out.TriggeredUpdateStatus
		*out = new(TriggeredUpdateStatusInitParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSynchronizationStatusInitParameters.
func (in *DataSynchronizationStatusInitParameters) DeepCopy() *DataSynchronizationStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(DataSynchronizationStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSynchronizationStatusObservation) DeepCopyInto(out *DataSynchronizationStatusObservation) {
	*out = *in
	if in.ContinuousUpdateStatus != nil {
		in, out := &in.ContinuousUpdateStatus, &out.ContinuousUpdateStatus
		*out = new(ContinuousUpdateStatusObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.DetailedState != nil {
		in, out := &in.DetailedState, &out.DetailedState
		*out = new(string)
		**out = **in
	}
	if in.FailedStatus != nil {
		in, out := &in.FailedStatus, &out.FailedStatus
		*out = new(FailedStatusObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = new(LastSyncObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.PipelineID != nil {
		in, out := &in.PipelineID, &out.PipelineID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningStatus != nil {
		in, out := &in.ProvisioningStatus, &out.ProvisioningStatus
		*out = new(ProvisioningStatusObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.TriggeredUpdateStatus != nil {
		in, out := &in.TriggeredUpdateStatus, &out.TriggeredUpdateStatus
		*out = new(TriggeredUpdateStatusObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSynchronizationStatusObservation.
func (in *DataSynchronizationStatusObservation) DeepCopy() *DataSynchronizationStatusObservation {
	if in == nil {
		return nil
	}
	out := new(DataSynchronizationStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSynchronizationStatusParameters) DeepCopyInto(out *DataSynchronizationStatusParameters) {
	*out = *in
	if in.ContinuousUpdateStatus != nil {
		in, out := &in.ContinuousUpdateStatus, &out.ContinuousUpdateStatus
		*out = new(ContinuousUpdateStatusParameters)
		**out = **in
	}
	if in.FailedStatus != nil {
		in, out := &in.FailedStatus, &out.FailedStatus
		*out = new(FailedStatusParameters)
		**out = **in
	}
	if in.ProvisioningStatus != nil {
		in, out := &in.ProvisioningStatus, &out.ProvisioningStatus
		*out = new(ProvisioningStatusParameters)
		**out = **in
	}
	if in.TriggeredUpdateStatus != nil {
		in, out := &in.TriggeredUpdateStatus, &out.TriggeredUpdateStatus
		*out = new(TriggeredUpdateStatusParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSynchronizationStatusParameters.
func (in *DataSynchronizationStatusParameters) DeepCopy() *DataSynchronizationStatusParameters {
	if in == nil {
		return nil
	}
	out := new(DataSynchronizationStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalog) DeepCopyInto(out *DatabaseDatabaseCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalog.
func (in *DatabaseDatabaseCatalog) DeepCopy() *DatabaseDatabaseCatalog {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseDatabaseCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalogInitParameters) DeepCopyInto(out *DatabaseDatabaseCatalogInitParameters) {
	*out = *in
	if in.CreateDatabaseIfNotExists != nil {
		in, out := &in.CreateDatabaseIfNotExists, &out.CreateDatabaseIfNotExists
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseInstanceName != nil {
		in, out := &in.DatabaseInstanceName, &out.DatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseInstanceNameRef != nil {
		in, out := &in.DatabaseInstanceNameRef, &out.DatabaseInstanceNameRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseInstanceNameSelector != nil {
		in, out := &in.DatabaseInstanceNameSelector, &out.DatabaseInstanceNameSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalogInitParameters.
func (in *DatabaseDatabaseCatalogInitParameters) DeepCopy() *DatabaseDatabaseCatalogInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalogInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalogList) DeepCopyInto(out *DatabaseDatabaseCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseDatabaseCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalogList.
func (in *DatabaseDatabaseCatalogList) DeepCopy() *DatabaseDatabaseCatalogList {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseDatabaseCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalogObservation) DeepCopyInto(out *DatabaseDatabaseCatalogObservation) {
	*out = *in
	if in.CreateDatabaseIfNotExists != nil {
		in, out := &in.CreateDatabaseIfNotExists, &out.CreateDatabaseIfNotExists
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseInstanceName != nil {
		in, out := &in.DatabaseInstanceName, &out.DatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalogObservation.
func (in *DatabaseDatabaseCatalogObservation) DeepCopy() *DatabaseDatabaseCatalogObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalogParameters) DeepCopyInto(out *DatabaseDatabaseCatalogParameters) {
	*out = *in
	if in.CreateDatabaseIfNotExists != nil {
		in, out := &in.CreateDatabaseIfNotExists, &out.CreateDatabaseIfNotExists
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseInstanceName != nil {
		in, out := &in.DatabaseInstanceName, &out.DatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseInstanceNameRef != nil {
		in, out := &in.DatabaseInstanceNameRef, &out.DatabaseInstanceNameRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseInstanceNameSelector != nil {
		in, out := &in.DatabaseInstanceNameSelector, &out.DatabaseInstanceNameSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalogParameters.
func (in *DatabaseDatabaseCatalogParameters) DeepCopy() *DatabaseDatabaseCatalogParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalogSpec) DeepCopyInto(out *DatabaseDatabaseCatalogSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalogSpec.
func (in *DatabaseDatabaseCatalogSpec) DeepCopy() *DatabaseDatabaseCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDatabaseCatalogStatus) DeepCopyInto(out *DatabaseDatabaseCatalogStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDatabaseCatalogStatus.
func (in *DatabaseDatabaseCatalogStatus) DeepCopy() *DatabaseDatabaseCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseDatabaseCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstance) DeepCopyInto(out *DatabaseInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstance.
func (in *DatabaseInstance) DeepCopy() *DatabaseInstance {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceInitParameters) DeepCopyInto(out *DatabaseInstanceInitParameters) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(string)
		**out = **in
	}
	if in.CustomTags != nil {
		in, out := &in.CustomTags, &out.CustomTags
		*out = make([]CustomTagsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnablePgNativeLogin != nil {
		in, out := &in.EnablePgNativeLogin, &out.EnablePgNativeLogin
		*out = new(bool)
		**out = **in
	}
	if in.EnableReadableSecondaries != nil {
		in, out := &in.EnableReadableSecondaries, &out.EnableReadableSecondaries
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(float64)
		**out = **in
	}
	if in.ParentInstanceRef != nil {
		in, out := &in.ParentInstanceRef, &out.ParentInstanceRef
		*out = new(ParentInstanceRefInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(DatabaseInstanceProviderConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PurgeOnDelete != nil {
		in, out := &in.PurgeOnDelete, &out.PurgeOnDelete
		*out = new(bool)
		**out = **in
	}
	if in.RetentionWindowInDays != nil {
		in, out := &in.RetentionWindowInDays, &out.RetentionWindowInDays
		*out = new(float64)
		**out = **in
	}
	if in.Stopped != nil {
		in, out := &in.Stopped, &out.Stopped
		*out = new(bool)
		**out = **in
	}
	if in.UsagePolicyID != nil {
		in, out := &in.UsagePolicyID, &out.UsagePolicyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceInitParameters.
func (in *DatabaseInstanceInitParameters) DeepCopy() *DatabaseInstanceInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceList) DeepCopyInto(out *DatabaseInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceList.
func (in *DatabaseInstanceList) DeepCopy() *DatabaseInstanceList {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceObservation) DeepCopyInto(out *DatabaseInstanceObservation) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(string)
		**out = **in
	}
	if in.ChildInstanceRefs != nil {
		in, out := &in.ChildInstanceRefs, &out.ChildInstanceRefs
		*out = make([]ChildInstanceRefsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.CustomTags != nil {
		in, out := &in.CustomTags, &out.CustomTags
		*out = make([]CustomTagsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EffectiveCapacity != nil {
		in, out := &in.EffectiveCapacity, &out.EffectiveCapacity
		*out = new(string)
		**out = **in
	}
	if in.EffectiveCustomTags != nil {
		in, out := &in.EffectiveCustomTags, &out.EffectiveCustomTags
		*out = make([]EffectiveCustomTagsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EffectiveEnablePgNativeLogin != nil {
		in, out := &in.EffectiveEnablePgNativeLogin, &out.EffectiveEnablePgNativeLogin
		*out = new(bool)
		**out = **in
	}
	if in.EffectiveEnableReadableSecondaries != nil {
		in, out := &in.EffectiveEnableReadableSecondaries, &out.EffectiveEnableReadableSecondaries
		*out = new(bool)
		**out = **in
	}
	if in.EffectiveNodeCount != nil {
		in, out := &in.EffectiveNodeCount, &out.EffectiveNodeCount
		*out = new(float64)
		**out = **in
	}
	if in.EffectiveRetentionWindowInDays != nil {
		in, out := &in.EffectiveRetentionWindowInDays, &out.EffectiveRetentionWindowInDays
		*out = new(float64)
		**out = **in
	}
	if in.EffectiveStopped != nil {
		in, out := &in.EffectiveStopped, &out.EffectiveStopped
		*out = new(bool)
		**out = **in
	}
	if in.EffectiveUsagePolicyID != nil {
		in, out := &in.EffectiveUsagePolicyID, &out.EffectiveUsagePolicyID
		*out = new(string)
		**out = **in
	}
	if in.EnablePgNativeLogin != nil {
		in, out := &in.EnablePgNativeLogin, &out.EnablePgNativeLogin
		*out = new(bool)
		**out = **in
	}
	if in.EnableReadableSecondaries != nil {
		in, out := &in.EnableReadableSecondaries, &out.EnableReadableSecondaries
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(float64)
		**out = **in
	}
	if in.ParentInstanceRef != nil {
		in, out := &in.ParentInstanceRef, &out.ParentInstanceRef
		*out = new(ParentInstanceRefObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.PgVersion != nil {
		in, out := &in.PgVersion, &out.PgVersion
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(DatabaseInstanceProviderConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.PurgeOnDelete != nil {
		in, out := &in.PurgeOnDelete, &out.PurgeOnDelete
		*out = new(bool)
		**out = **in
	}
	if in.ReadOnlyDNS != nil {
		in, out := &in.ReadOnlyDNS, &out.ReadOnlyDNS
		*out = new(string)
		**out = **in
	}
	if in.ReadWriteDNS != nil {
		in, out := &in.ReadWriteDNS, &out.ReadWriteDNS
		*out = new(string)
		**out = **in
	}
	if in.RetentionWindowInDays != nil {
		in, out := &in.RetentionWindowInDays, &out.RetentionWindowInDays
		*out = new(float64)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Stopped != nil {
		in, out := &in.Stopped, &out.Stopped
		*out = new(bool)
		**out = **in
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(string)
		**out = **in
	}
	if in.UsagePolicyID != nil {
		in, out := &in.UsagePolicyID, &out.UsagePolicyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceObservation.
func (in *DatabaseInstanceObservation) DeepCopy() *DatabaseInstanceObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceParameters) DeepCopyInto(out *DatabaseInstanceParameters) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(string)
		**out = **in
	}
	if in.CustomTags != nil {
		in, out := &in.CustomTags, &out.CustomTags
		*out = make([]CustomTagsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnablePgNativeLogin != nil {
		in, out := &in.EnablePgNativeLogin, &out.EnablePgNativeLogin
		*out = new(bool)
		**out = **in
	}
	if in.EnableReadableSecondaries != nil {
		in, out := &in.EnableReadableSecondaries, &out.EnableReadableSecondaries
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(float64)
		**out = **in
	}
	if in.ParentInstanceRef != nil {
		in, out := &in.ParentInstanceRef, &out.ParentInstanceRef
		*out = new(ParentInstanceRefParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(DatabaseInstanceProviderConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PurgeOnDelete != nil {
		in, out := &in.PurgeOnDelete, &out.PurgeOnDelete
		*out = new(bool)
		**out = **in
	}
	if in.RetentionWindowInDays != nil {
		in, out := &in.RetentionWindowInDays, &out.RetentionWindowInDays
		*out = new(float64)
		**out = **in
	}
	if in.Stopped != nil {
		in, out := &in.Stopped, &out.Stopped
		*out = new(bool)
		**out = **in
	}
	if in.UsagePolicyID != nil {
		in, out := &in.UsagePolicyID, &out.UsagePolicyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceParameters.
func (in *DatabaseInstanceParameters) DeepCopy() *DatabaseInstanceParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceProviderConfigInitParameters) DeepCopyInto(out *DatabaseInstanceProviderConfigInitParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceProviderConfigInitParameters.
func (in *DatabaseInstanceProviderConfigInitParameters) DeepCopy() *DatabaseInstanceProviderConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceProviderConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceProviderConfigObservation) DeepCopyInto(out *DatabaseInstanceProviderConfigObservation) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceProviderConfigObservation.
func (in *DatabaseInstanceProviderConfigObservation) DeepCopy() *DatabaseInstanceProviderConfigObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceProviderConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceProviderConfigParameters) DeepCopyInto(out *DatabaseInstanceProviderConfigParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceProviderConfigParameters.
func (in *DatabaseInstanceProviderConfigParameters) DeepCopy() *DatabaseInstanceProviderConfigParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceProviderConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceSpec) DeepCopyInto(out *DatabaseInstanceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceSpec.
func (in *DatabaseInstanceSpec) DeepCopy() *DatabaseInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInstanceStatus) DeepCopyInto(out *DatabaseInstanceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInstanceStatus.
func (in *DatabaseInstanceStatus) DeepCopy() *DatabaseInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTable) DeepCopyInto(out *DatabaseSyncedDatabaseTable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTable.
func (in *DatabaseSyncedDatabaseTable) DeepCopy() *DatabaseSyncedDatabaseTable {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseSyncedDatabaseTable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableInitParameters) DeepCopyInto(out *DatabaseSyncedDatabaseTableInitParameters) {
	*out = *in
	if in.DatabaseInstanceName != nil {
		in, out := &in.DatabaseInstanceName, &out.DatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseInstanceNameRef != nil {
		in, out := &in.DatabaseInstanceNameRef, &out.DatabaseInstanceNameRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseInstanceNameSelector != nil {
		in, out := &in.DatabaseInstanceNameSelector, &out.DatabaseInstanceNameSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LogicalDatabaseName != nil {
		in, out := &in.LogicalDatabaseName, &out.LogicalDatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(DatabaseSyncedDatabaseTableProviderConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SpecInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableInitParameters.
func (in *DatabaseSyncedDatabaseTableInitParameters) DeepCopy() *DatabaseSyncedDatabaseTableInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableList) DeepCopyInto(out *DatabaseSyncedDatabaseTableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseSyncedDatabaseTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableList.
func (in *DatabaseSyncedDatabaseTableList) DeepCopy() *DatabaseSyncedDatabaseTableList {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseSyncedDatabaseTableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableObservation) DeepCopyInto(out *DatabaseSyncedDatabaseTableObservation) {
	*out = *in
	if in.DataSynchronizationStatus != nil {
		in, out := &in.DataSynchronizationStatus, &out.DataSynchronizationStatus
		*out = new(DataSynchronizationStatusObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseInstanceName != nil {
		in, out := &in.DatabaseInstanceName, &out.DatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.EffectiveDatabaseInstanceName != nil {
		in, out := &in.EffectiveDatabaseInstanceName, &out.EffectiveDatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.EffectiveLogicalDatabaseName != nil {
		in, out := &in.EffectiveLogicalDatabaseName, &out.EffectiveLogicalDatabaseName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogicalDatabaseName != nil {
		in, out := &in.LogicalDatabaseName, &out.LogicalDatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(DatabaseSyncedDatabaseTableProviderConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SpecObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.UnityCatalogProvisioningState != nil {
		in, out := &in.UnityCatalogProvisioningState, &out.UnityCatalogProvisioningState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableObservation.
func (in *DatabaseSyncedDatabaseTableObservation) DeepCopy() *DatabaseSyncedDatabaseTableObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableParameters) DeepCopyInto(out *DatabaseSyncedDatabaseTableParameters) {
	*out = *in
	if in.DatabaseInstanceName != nil {
		in, out := &in.DatabaseInstanceName, &out.DatabaseInstanceName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseInstanceNameRef != nil {
		in, out := &in.DatabaseInstanceNameRef, &out.DatabaseInstanceNameRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseInstanceNameSelector != nil {
		in, out := &in.DatabaseInstanceNameSelector, &out.DatabaseInstanceNameSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LogicalDatabaseName != nil {
		in, out := &in.LogicalDatabaseName, &out.LogicalDatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(DatabaseSyncedDatabaseTableProviderConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SpecParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableParameters.
func (in *DatabaseSyncedDatabaseTableParameters) DeepCopy() *DatabaseSyncedDatabaseTableParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableProviderConfigInitParameters) DeepCopyInto(out *DatabaseSyncedDatabaseTableProviderConfigInitParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableProviderConfigInitParameters.
func (in *DatabaseSyncedDatabaseTableProviderConfigInitParameters) DeepCopy() *DatabaseSyncedDatabaseTableProviderConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableProviderConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableProviderConfigObservation) DeepCopyInto(out *DatabaseSyncedDatabaseTableProviderConfigObservation) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableProviderConfigObservation.
func (in *DatabaseSyncedDatabaseTableProviderConfigObservation) DeepCopy() *DatabaseSyncedDatabaseTableProviderConfigObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableProviderConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableProviderConfigParameters) DeepCopyInto(out *DatabaseSyncedDatabaseTableProviderConfigParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableProviderConfigParameters.
func (in *DatabaseSyncedDatabaseTableProviderConfigParameters) DeepCopy() *DatabaseSyncedDatabaseTableProviderConfigParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableProviderConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableSpec) DeepCopyInto(out *DatabaseSyncedDatabaseTableSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableSpec.
func (in *DatabaseSyncedDatabaseTableSpec) DeepCopy() *DatabaseSyncedDatabaseTableSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSyncedDatabaseTableStatus) DeepCopyInto(out *DatabaseSyncedDatabaseTableStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSyncedDatabaseTableStatus.
func (in *DatabaseSyncedDatabaseTableStatus) DeepCopy() *DatabaseSyncedDatabaseTableStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseSyncedDatabaseTableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeltaTableSyncInfoInitParameters) DeepCopyInto(out *DeltaTableSyncInfoInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaTableSyncInfoInitParameters.
func (in *DeltaTableSyncInfoInitParameters) DeepCopy() *DeltaTableSyncInfoInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeltaTableSyncInfoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeltaTableSyncInfoObservation) DeepCopyInto(out *DeltaTableSyncInfoObservation) {
	*out = *in
	if in.DeltaCommitTimestamp != nil {
		in, out := &in.DeltaCommitTimestamp, &out.DeltaCommitTimestamp
		*out = new(string)
		**out = **in
	}
	if in.DeltaCommitVersion != nil {
		in, out := &in.DeltaCommitVersion, &out.DeltaCommitVersion
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaTableSyncInfoObservation.
func (in *DeltaTableSyncInfoObservation) DeepCopy() *DeltaTableSyncInfoObservation {
	if in == nil {
		return nil
	}
	out := new(DeltaTableSyncInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeltaTableSyncInfoParameters) DeepCopyInto(out *DeltaTableSyncInfoParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaTableSyncInfoParameters.
func (in *DeltaTableSyncInfoParameters) DeepCopy() *DeltaTableSyncInfoParameters {
	if in == nil {
		return nil
	}
	out := new(DeltaTableSyncInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveCustomTagsInitParameters) DeepCopyInto(out *EffectiveCustomTagsInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveCustomTagsInitParameters.
func (in *EffectiveCustomTagsInitParameters) DeepCopy() *EffectiveCustomTagsInitParameters {
	if in == nil {
		return nil
	}
	out := new(EffectiveCustomTagsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveCustomTagsObservation) DeepCopyInto(out *EffectiveCustomTagsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveCustomTagsObservation.
func (in *EffectiveCustomTagsObservation) DeepCopy() *EffectiveCustomTagsObservation {
	if in == nil {
		return nil
	}
	out := new(EffectiveCustomTagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveCustomTagsParameters) DeepCopyInto(out *EffectiveCustomTagsParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveCustomTagsParameters.
func (in *EffectiveCustomTagsParameters) DeepCopy() *EffectiveCustomTagsParameters {
	if in == nil {
		return nil
	}
	out := new(EffectiveCustomTagsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedStatusInitParameters) DeepCopyInto(out *FailedStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedStatusInitParameters.
func (in *FailedStatusInitParameters) DeepCopy() *FailedStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(FailedStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedStatusObservation) DeepCopyInto(out *FailedStatusObservation) {
	*out = *in
	if in.LastProcessedCommitVersion != nil {
		in, out := &in.LastProcessedCommitVersion, &out.LastProcessedCommitVersion
		*out = new(float64)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedStatusObservation.
func (in *FailedStatusObservation) DeepCopy() *FailedStatusObservation {
	if in == nil {
		return nil
	}
	out := new(FailedStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedStatusParameters) DeepCopyInto(out *FailedStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedStatusParameters.
func (in *FailedStatusParameters) DeepCopy() *FailedStatusParameters {
	if in == nil {
		return nil
	}
	out := new(FailedStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialPipelineSyncProgressInitParameters) DeepCopyInto(out *InitialPipelineSyncProgressInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialPipelineSyncProgressInitParameters.
func (in *InitialPipelineSyncProgressInitParameters) DeepCopy() *InitialPipelineSyncProgressInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitialPipelineSyncProgressInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialPipelineSyncProgressObservation) DeepCopyInto(out *InitialPipelineSyncProgressObservation) {
	*out = *in
	if in.EstimatedCompletionTimeSeconds != nil {
		in, out := &in.EstimatedCompletionTimeSeconds, &out.EstimatedCompletionTimeSeconds
		*out = new(float64)
		**out = **in
	}
	if in.LatestVersionCurrentlyProcessing != nil {
		in, out := &in.LatestVersionCurrentlyProcessing, &out.LatestVersionCurrentlyProcessing
		*out = new(float64)
		**out = **in
	}
	if in.ProvisioningPhase != nil {
		in, out := &in.ProvisioningPhase, &out.ProvisioningPhase
		*out = new(string)
		**out = **in
	}
	if in.SyncProgressCompletion != nil {
		in, out := &in.SyncProgressCompletion, &out.SyncProgressCompletion
		*out = new(float64)
		**out = **in
	}
	if in.SyncedRowCount != nil {
		in, out := &in.SyncedRowCount, &out.SyncedRowCount
		*out = new(float64)
		**out = **in
	}
	if in.TotalRowCount != nil {
		in, out := &in.TotalRowCount, &out.TotalRowCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialPipelineSyncProgressObservation.
func (in *InitialPipelineSyncProgressObservation) DeepCopy() *InitialPipelineSyncProgressObservation {
	if in == nil {
		return nil
	}
	out := new(InitialPipelineSyncProgressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialPipelineSyncProgressParameters) DeepCopyInto(out *InitialPipelineSyncProgressParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialPipelineSyncProgressParameters.
func (in *InitialPipelineSyncProgressParameters) DeepCopy() *InitialPipelineSyncProgressParameters {
	if in == nil {
		return nil
	}
	out := new(InitialPipelineSyncProgressParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastSyncInitParameters) DeepCopyInto(out *LastSyncInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastSyncInitParameters.
func (in *LastSyncInitParameters) DeepCopy() *LastSyncInitParameters {
	if in == nil {
		return nil
	}
	out := new(LastSyncInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastSyncObservation) DeepCopyInto(out *LastSyncObservation) {
	*out = *in
	if in.DeltaTableSyncInfo != nil {
		in, out := &in.DeltaTableSyncInfo, &out.DeltaTableSyncInfo
		*out = new(DeltaTableSyncInfoObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.SyncEndTimestamp != nil {
		in, out := &in.SyncEndTimestamp, &out.SyncEndTimestamp
		*out = new(string)
		**out = **in
	}
	if in.SyncStartTimestamp != nil {
		in, out := &in.SyncStartTimestamp, &out.SyncStartTimestamp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastSyncObservation.
func (in *LastSyncObservation) DeepCopy() *LastSyncObservation {
	if in == nil {
		return nil
	}
	out := new(LastSyncObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastSyncParameters) DeepCopyInto(out *LastSyncParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastSyncParameters.
func (in *LastSyncParameters) DeepCopy() *LastSyncParameters {
	if in == nil {
		return nil
	}
	out := new(LastSyncParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewPipelineSpecInitParameters) DeepCopyInto(out *NewPipelineSpecInitParameters) {
	*out = *in
	if in.BudgetPolicyID != nil {
		in, out := &in.BudgetPolicyID, &out.BudgetPolicyID
		*out = new(string)
		**out = **in
	}
	if in.StorageCatalog != nil {
		in, out := &in.StorageCatalog, &out.StorageCatalog
		*out = new(string)
		**out = **in
	}
	if in.StorageSchema != nil {
		in, out := &in.StorageSchema, &out.StorageSchema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewPipelineSpecInitParameters.
func (in *NewPipelineSpecInitParameters) DeepCopy() *NewPipelineSpecInitParameters {
	if in == nil {
		return nil
	}
	out := new(NewPipelineSpecInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewPipelineSpecObservation) DeepCopyInto(out *NewPipelineSpecObservation) {
	*out = *in
	if in.BudgetPolicyID != nil {
		in, out := &in.BudgetPolicyID, &out.BudgetPolicyID
		*out = new(string)
		**out = **in
	}
	if in.StorageCatalog != nil {
		in, out := &in.StorageCatalog, &out.StorageCatalog
		*out = new(string)
		**out = **in
	}
	if in.StorageSchema != nil {
		in, out := &in.StorageSchema, &out.StorageSchema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewPipelineSpecObservation.
func (in *NewPipelineSpecObservation) DeepCopy() *NewPipelineSpecObservation {
	if in == nil {
		return nil
	}
	out := new(NewPipelineSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewPipelineSpecParameters) DeepCopyInto(out *NewPipelineSpecParameters) {
	*out = *in
	if in.BudgetPolicyID != nil {
		in, out := &in.BudgetPolicyID, &out.BudgetPolicyID
		*out = new(string)
		**out = **in
	}
	if in.StorageCatalog != nil {
		in, out := &in.StorageCatalog, &out.StorageCatalog
		*out = new(string)
		**out = **in
	}
	if in.StorageSchema != nil {
		in, out := &in.StorageSchema, &out.StorageSchema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewPipelineSpecParameters.
func (in *NewPipelineSpecParameters) DeepCopy() *NewPipelineSpecParameters {
	if in == nil {
		return nil
	}
	out := new(NewPipelineSpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentInstanceRefInitParameters) DeepCopyInto(out *ParentInstanceRefInitParameters) {
	*out = *in
	if in.BranchTime != nil {
		in, out := &in.BranchTime, &out.BranchTime
		*out = new(string)
		**out = **in
	}
	if in.Lsn != nil {
		in, out := &in.Lsn, &out.Lsn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentInstanceRefInitParameters.
func (in *ParentInstanceRefInitParameters) DeepCopy() *ParentInstanceRefInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParentInstanceRefInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentInstanceRefObservation) DeepCopyInto(out *ParentInstanceRefObservation) {
	*out = *in
	if in.BranchTime != nil {
		in, out := &in.BranchTime, &out.BranchTime
		*out = new(string)
		**out = **in
	}
	if in.EffectiveLsn != nil {
		in, out := &in.EffectiveLsn, &out.EffectiveLsn
		*out = new(string)
		**out = **in
	}
	if in.Lsn != nil {
		in, out := &in.Lsn, &out.Lsn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UID != nil {
		in, out := &in.UID, &out.UID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentInstanceRefObservation.
func (in *ParentInstanceRefObservation) DeepCopy() *ParentInstanceRefObservation {
	if in == nil {
		return nil
	}
	out := new(ParentInstanceRefObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentInstanceRefParameters) DeepCopyInto(out *ParentInstanceRefParameters) {
	*out = *in
	if in.BranchTime != nil {
		in, out := &in.BranchTime, &out.BranchTime
		*out = new(string)
		**out = **in
	}
	if in.Lsn != nil {
		in, out := &in.Lsn, &out.Lsn
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentInstanceRefParameters.
func (in *ParentInstanceRefParameters) DeepCopy() *ParentInstanceRefParameters {
	if in == nil {
		return nil
	}
	out := new(ParentInstanceRefParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigInitParameters) DeepCopyInto(out *ProviderConfigInitParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigInitParameters.
func (in *ProviderConfigInitParameters) DeepCopy() *ProviderConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigObservation) DeepCopyInto(out *ProviderConfigObservation) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigObservation.
func (in *ProviderConfigObservation) DeepCopy() *ProviderConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigParameters) DeepCopyInto(out *ProviderConfigParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigParameters.
func (in *ProviderConfigParameters) DeepCopy() *ProviderConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatusInitParameters) DeepCopyInto(out *ProvisioningStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatusInitParameters.
func (in *ProvisioningStatusInitParameters) DeepCopy() *ProvisioningStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatusInitialPipelineSyncProgressInitParameters) DeepCopyInto(out *ProvisioningStatusInitialPipelineSyncProgressInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatusInitialPipelineSyncProgressInitParameters.
func (in *ProvisioningStatusInitialPipelineSyncProgressInitParameters) DeepCopy() *ProvisioningStatusInitialPipelineSyncProgressInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatusInitialPipelineSyncProgressInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatusInitialPipelineSyncProgressObservation) DeepCopyInto(out *ProvisioningStatusInitialPipelineSyncProgressObservation) {
	*out = *in
	if in.EstimatedCompletionTimeSeconds != nil {
		in, out := &in.EstimatedCompletionTimeSeconds, &out.EstimatedCompletionTimeSeconds
		*out = new(float64)
		**out = **in
	}
	if in.LatestVersionCurrentlyProcessing != nil {
		in, out := &in.LatestVersionCurrentlyProcessing, &out.LatestVersionCurrentlyProcessing
		*out = new(float64)
		**out = **in
	}
	if in.ProvisioningPhase != nil {
		in, out := &in.ProvisioningPhase, &out.ProvisioningPhase
		*out = new(string)
		**out = **in
	}
	if in.SyncProgressCompletion != nil {
		in, out := &in.SyncProgressCompletion, &out.SyncProgressCompletion
		*out = new(float64)
		**out = **in
	}
	if in.SyncedRowCount != nil {
		in, out := &in.SyncedRowCount, &out.SyncedRowCount
		*out = new(float64)
		**out = **in
	}
	if in.TotalRowCount != nil {
		in, out := &in.TotalRowCount, &out.TotalRowCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatusInitialPipelineSyncProgressObservation.
func (in *ProvisioningStatusInitialPipelineSyncProgressObservation) DeepCopy() *ProvisioningStatusInitialPipelineSyncProgressObservation {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatusInitialPipelineSyncProgressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatusInitialPipelineSyncProgressParameters) DeepCopyInto(out *ProvisioningStatusInitialPipelineSyncProgressParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatusInitialPipelineSyncProgressParameters.
func (in *ProvisioningStatusInitialPipelineSyncProgressParameters) DeepCopy() *ProvisioningStatusInitialPipelineSyncProgressParameters {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatusInitialPipelineSyncProgressParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatusObservation) DeepCopyInto(out *ProvisioningStatusObservation) {
	*out = *in
	if in.InitialPipelineSyncProgress != nil {
		in, out := &in.InitialPipelineSyncProgress, &out.InitialPipelineSyncProgress
		*out = new(ProvisioningStatusInitialPipelineSyncProgressObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatusObservation.
func (in *ProvisioningStatusObservation) DeepCopy() *ProvisioningStatusObservation {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatusParameters) DeepCopyInto(out *ProvisioningStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatusParameters.
func (in *ProvisioningStatusParameters) DeepCopy() *ProvisioningStatusParameters {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecInitParameters) DeepCopyInto(out *SpecInitParameters) {
	*out = *in
	if in.AcceleratedSync != nil {
		in, out := &in.AcceleratedSync, &out.AcceleratedSync
		*out = new(bool)
		**out = **in
	}
	if in.CreateDatabaseObjectsIfMissing != nil {
		in, out := &in.CreateDatabaseObjectsIfMissing, &out.CreateDatabaseObjectsIfMissing
		*out = new(bool)
		**out = **in
	}
	if in.ExistingPipelineID != nil {
		in, out := &in.ExistingPipelineID, &out.ExistingPipelineID
		*out = new(string)
		**out = **in
	}
	if in.NewPipelineSpec != nil {
		in, out := &in.NewPipelineSpec, &out.NewPipelineSpec
		*out = new(NewPipelineSpecInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PrimaryKeyColumns != nil {
		in, out := &in.PrimaryKeyColumns, &out.PrimaryKeyColumns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SchedulingPolicy != nil {
		in, out := &in.SchedulingPolicy, &out.SchedulingPolicy
		*out = new(string)
		**out = **in
	}
	if in.SourceTableFullName != nil {
		in, out := &in.SourceTableFullName, &out.SourceTableFullName
		*out = new(string)
		**out = **in
	}
	if in.TimeseriesKey != nil {
		in, out := &in.TimeseriesKey, &out.TimeseriesKey
		*out = new(string)
		**out = **in
	}
	if in.TypeOverrides != nil {
		in, out := &in.TypeOverrides, &out.TypeOverrides
		*out = make([]TypeOverridesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecInitParameters.
func (in *SpecInitParameters) DeepCopy() *SpecInitParameters {
	if in == nil {
		return nil
	}
	out := new(SpecInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecObservation) DeepCopyInto(out *SpecObservation) {
	*out = *in
	if in.AcceleratedSync != nil {
		in, out := &in.AcceleratedSync, &out.AcceleratedSync
		*out = new(bool)
		**out = **in
	}
	if in.CreateDatabaseObjectsIfMissing != nil {
		in, out := &in.CreateDatabaseObjectsIfMissing, &out.CreateDatabaseObjectsIfMissing
		*out = new(bool)
		**out = **in
	}
	if in.ExistingPipelineID != nil {
		in, out := &in.ExistingPipelineID, &out.ExistingPipelineID
		*out = new(string)
		**out = **in
	}
	if in.NewPipelineSpec != nil {
		in, out := &in.NewPipelineSpec, &out.NewPipelineSpec
		*out = new(NewPipelineSpecObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.PrimaryKeyColumns != nil {
		in, out := &in.PrimaryKeyColumns, &out.PrimaryKeyColumns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SchedulingPolicy != nil {
		in, out := &in.SchedulingPolicy, &out.SchedulingPolicy
		*out = new(string)
		**out = **in
	}
	if in.SourceTableFullName != nil {
		in, out := &in.SourceTableFullName, &out.SourceTableFullName
		*out = new(string)
		**out = **in
	}
	if in.TimeseriesKey != nil {
		in, out := &in.TimeseriesKey, &out.TimeseriesKey
		*out = new(string)
		**out = **in
	}
	if in.TypeOverrides != nil {
		in, out := &in.TypeOverrides, &out.TypeOverrides
		*out = make([]TypeOverridesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecObservation.
func (in *SpecObservation) DeepCopy() *SpecObservation {
	if in == nil {
		return nil
	}
	out := new(SpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecParameters) DeepCopyInto(out *SpecParameters) {
	*out = *in
	if in.AcceleratedSync != nil {
		in, out := &in.AcceleratedSync, &out.AcceleratedSync
		*out = new(bool)
		**out = **in
	}
	if in.CreateDatabaseObjectsIfMissing != nil {
		in, out := &in.CreateDatabaseObjectsIfMissing, &out.CreateDatabaseObjectsIfMissing
		*out = new(bool)
		**out = **in
	}
	if in.ExistingPipelineID != nil {
		in, out := &in.ExistingPipelineID, &out.ExistingPipelineID
		*out = new(string)
		**out = **in
	}
	if in.NewPipelineSpec != nil {
		in, out := &in.NewPipelineSpec, &out.NewPipelineSpec
		*out = new(NewPipelineSpecParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PrimaryKeyColumns != nil {
		in, out := &in.PrimaryKeyColumns, &out.PrimaryKeyColumns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SchedulingPolicy != nil {
		in, out := &in.SchedulingPolicy, &out.SchedulingPolicy
		*out = new(string)
		**out = **in
	}
	if in.SourceTableFullName != nil {
		in, out := &in.SourceTableFullName, &out.SourceTableFullName
		*out = new(string)
		**out = **in
	}
	if in.TimeseriesKey != nil {
		in, out := &in.TimeseriesKey, &out.TimeseriesKey
		*out = new(string)
		**out = **in
	}
	if in.TypeOverrides != nil {
		in, out := &in.TypeOverrides, &out.TypeOverrides
		*out = make([]TypeOverridesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecParameters.
func (in *SpecParameters) DeepCopy() *SpecParameters {
	if in == nil {
		return nil
	}
	out := new(SpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggeredUpdateProgressInitParameters) DeepCopyInto(out *TriggeredUpdateProgressInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggeredUpdateProgressInitParameters.
func (in *TriggeredUpdateProgressInitParameters) DeepCopy() *TriggeredUpdateProgressInitParameters {
	if in == nil {
		return nil
	}
	out := new(TriggeredUpdateProgressInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggeredUpdateProgressObservation) DeepCopyInto(out *TriggeredUpdateProgressObservation) {
	*out = *in
	if in.EstimatedCompletionTimeSeconds != nil {
		in, out := &in.EstimatedCompletionTimeSeconds, &out.EstimatedCompletionTimeSeconds
		*out = new(float64)
		**out = **in
	}
	if in.LatestVersionCurrentlyProcessing != nil {
		in, out := &in.LatestVersionCurrentlyProcessing, &out.LatestVersionCurrentlyProcessing
		*out = new(float64)
		**out = **in
	}
	if in.ProvisioningPhase != nil {
		in, out := &in.ProvisioningPhase, &out.ProvisioningPhase
		*out = new(string)
		**out = **in
	}
	if in.SyncProgressCompletion != nil {
		in, out := &in.SyncProgressCompletion, &out.SyncProgressCompletion
		*out = new(float64)
		**out = **in
	}
	if in.SyncedRowCount != nil {
		in, out := &in.SyncedRowCount, &out.SyncedRowCount
		*out = new(float64)
		**out = **in
	}
	if in.TotalRowCount != nil {
		in, out := &in.TotalRowCount, &out.TotalRowCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggeredUpdateProgressObservation.
func (in *TriggeredUpdateProgressObservation) DeepCopy() *TriggeredUpdateProgressObservation {
	if in == nil {
		return nil
	}
	out := new(TriggeredUpdateProgressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggeredUpdateProgressParameters) DeepCopyInto(out *TriggeredUpdateProgressParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggeredUpdateProgressParameters.
func (in *TriggeredUpdateProgressParameters) DeepCopy() *TriggeredUpdateProgressParameters {
	if in == nil {
		return nil
	}
	out := new(TriggeredUpdateProgressParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggeredUpdateStatusInitParameters) DeepCopyInto(out *TriggeredUpdateStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggeredUpdateStatusInitParameters.
func (in *TriggeredUpdateStatusInitParameters) DeepCopy() *TriggeredUpdateStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(TriggeredUpdateStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggeredUpdateStatusObservation) DeepCopyInto(out *TriggeredUpdateStatusObservation) {
	*out = *in
	if in.LastProcessedCommitVersion != nil {
		in, out := &in.LastProcessedCommitVersion, &out.LastProcessedCommitVersion
		*out = new(float64)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
	if in.TriggeredUpdateProgress != nil {
		in, out := &in.TriggeredUpdateProgress, &out.TriggeredUpdateProgress
		*out = new(TriggeredUpdateProgressObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggeredUpdateStatusObservation.
func (in *TriggeredUpdateStatusObservation) DeepCopy() *TriggeredUpdateStatusObservation {
	if in == nil {
		return nil
	}
	out := new(TriggeredUpdateStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggeredUpdateStatusParameters) DeepCopyInto(out *TriggeredUpdateStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggeredUpdateStatusParameters.
func (in *TriggeredUpdateStatusParameters) DeepCopy() *TriggeredUpdateStatusParameters {
	if in == nil {
		return nil
	}
	out := new(TriggeredUpdateStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeOverridesInitParameters) DeepCopyInto(out *TypeOverridesInitParameters) {
	*out = *in
	if in.ColumnName != nil {
		in, out := &in.ColumnName, &out.ColumnName
		*out = new(string)
		**out = **in
	}
	if in.PgType != nil {
		in, out := &in.PgType, &out.PgType
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeOverridesInitParameters.
func (in *TypeOverridesInitParameters) DeepCopy() *TypeOverridesInitParameters {
	if in == nil {
		return nil
	}
	out := new(TypeOverridesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeOverridesObservation) DeepCopyInto(out *TypeOverridesObservation) {
	*out = *in
	if in.ColumnName != nil {
		in, out := &in.ColumnName, &out.ColumnName
		*out = new(string)
		**out = **in
	}
	if in.PgType != nil {
		in, out := &in.PgType, &out.PgType
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeOverridesObservation.
func (in *TypeOverridesObservation) DeepCopy() *TypeOverridesObservation {
	if in == nil {
		return nil
	}
	out := new(TypeOverridesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeOverridesParameters) DeepCopyInto(out *TypeOverridesParameters) {
	*out = *in
	if in.ColumnName != nil {
		in, out := &in.ColumnName, &out.ColumnName
		*out = new(string)
		**out = **in
	}
	if in.PgType != nil {
		in, out := &in.PgType, &out.PgType
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeOverridesParameters.
func (in *TypeOverridesParameters) DeepCopy() *TypeOverridesParameters {
	if in == nil {
		return nil
	}
	out := new(TypeOverridesParameters)
	in.DeepCopyInto(out)
	return out
}
