// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DailyScheduleInitParameters struct {
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type DailyScheduleObservation struct {
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type DailyScheduleParameters struct {

	// +kubebuilder:validation:Optional
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type MonthlyScheduleInitParameters struct {
	Day *float64 `json:"day,omitempty" tf:"day,omitempty"`

	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type MonthlyScheduleObservation struct {
	Day *float64 `json:"day,omitempty" tf:"day,omitempty"`

	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type MonthlyScheduleParameters struct {

	// +kubebuilder:validation:Optional
	Day *float64 `json:"day" tf:"day,omitempty"`

	// +kubebuilder:validation:Optional
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type PostgresSnapshotScheduleInitParameters struct {
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	ProviderConfig *PostgresSnapshotScheduleProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	Schedule []ScheduleInitParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type PostgresSnapshotScheduleObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	ProviderConfig *PostgresSnapshotScheduleProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	Schedule []ScheduleObservation `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type PostgresSnapshotScheduleParameters struct {

	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// +kubebuilder:validation:Optional
	ProviderConfig *PostgresSnapshotScheduleProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// +kubebuilder:validation:Optional
	Schedule []ScheduleParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type PostgresSnapshotScheduleProviderConfigInitParameters struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type PostgresSnapshotScheduleProviderConfigObservation struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type PostgresSnapshotScheduleProviderConfigParameters struct {

	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ScheduleInitParameters struct {
	DailySchedule *DailyScheduleInitParameters `json:"dailySchedule,omitempty" tf:"daily_schedule,omitempty"`

	MonthlySchedule *MonthlyScheduleInitParameters `json:"monthlySchedule,omitempty" tf:"monthly_schedule,omitempty"`

	Retention *string `json:"retention,omitempty" tf:"retention,omitempty"`

	WeeklySchedule *WeeklyScheduleInitParameters `json:"weeklySchedule,omitempty" tf:"weekly_schedule,omitempty"`
}

type ScheduleObservation struct {
	DailySchedule *DailyScheduleObservation `json:"dailySchedule,omitempty" tf:"daily_schedule,omitempty"`

	MonthlySchedule *MonthlyScheduleObservation `json:"monthlySchedule,omitempty" tf:"monthly_schedule,omitempty"`

	Retention *string `json:"retention,omitempty" tf:"retention,omitempty"`

	WeeklySchedule *WeeklyScheduleObservation `json:"weeklySchedule,omitempty" tf:"weekly_schedule,omitempty"`
}

type ScheduleParameters struct {

	// +kubebuilder:validation:Optional
	DailySchedule *DailyScheduleParameters `json:"dailySchedule,omitempty" tf:"daily_schedule,omitempty"`

	// +kubebuilder:validation:Optional
	MonthlySchedule *MonthlyScheduleParameters `json:"monthlySchedule,omitempty" tf:"monthly_schedule,omitempty"`

	// +kubebuilder:validation:Optional
	Retention *string `json:"retention" tf:"retention,omitempty"`

	// +kubebuilder:validation:Optional
	WeeklySchedule *WeeklyScheduleParameters `json:"weeklySchedule,omitempty" tf:"weekly_schedule,omitempty"`
}

type WeeklyScheduleInitParameters struct {
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type WeeklyScheduleObservation struct {
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

type WeeklyScheduleParameters struct {

	// +kubebuilder:validation:Optional
	DayOfWeek *string `json:"dayOfWeek" tf:"day_of_week,omitempty"`

	// +kubebuilder:validation:Optional
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`
}

// PostgresSnapshotScheduleSpec defines the desired state of PostgresSnapshotSchedule
type PostgresSnapshotScheduleSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PostgresSnapshotScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PostgresSnapshotScheduleInitParameters `json:"initProvider,omitempty"`
}

// PostgresSnapshotScheduleStatus defines the observed state of PostgresSnapshotSchedule.
type PostgresSnapshotScheduleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PostgresSnapshotScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PostgresSnapshotSchedule is the Schema for the PostgresSnapshotSchedules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type PostgresSnapshotSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parent) || (has(self.initProvider) && has(self.initProvider.parent))",message="spec.forProvider.parent is a required parameter"
	Spec   PostgresSnapshotScheduleSpec   `json:"spec"`
	Status PostgresSnapshotScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PostgresSnapshotScheduleList contains a list of PostgresSnapshotSchedules
type PostgresSnapshotScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PostgresSnapshotSchedule `json:"items"`
}

// Repository type metadata.
var (
	PostgresSnapshotSchedule_Kind             = "PostgresSnapshotSchedule"
	PostgresSnapshotSchedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PostgresSnapshotSchedule_Kind}.String()
	PostgresSnapshotSchedule_KindAPIVersion   = PostgresSnapshotSchedule_Kind + "." + CRDGroupVersion.String()
	PostgresSnapshotSchedule_GroupVersionKind = CRDGroupVersion.WithKind(PostgresSnapshotSchedule_Kind)
)

func init() {
	SchemeBuilder.Register(&PostgresSnapshotSchedule{}, &PostgresSnapshotScheduleList{})
}
