// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AggregationFunctionInitParameters struct {
	ApproxCountDistinct *ApproxCountDistinctInitParameters `json:"approxCountDistinct,omitempty" tf:"approx_count_distinct,omitempty"`

	ApproxPercentile *ApproxPercentileInitParameters `json:"approxPercentile,omitempty" tf:"approx_percentile,omitempty"`

	Avg *AvgInitParameters `json:"avg,omitempty" tf:"avg,omitempty"`

	CountFunction *CountFunctionInitParameters `json:"countFunction,omitempty" tf:"count_function,omitempty"`

	First *FirstInitParameters `json:"first,omitempty" tf:"first,omitempty"`

	FirstDistinct *FirstDistinctInitParameters `json:"firstDistinct,omitempty" tf:"first_distinct,omitempty"`

	FirstN *FirstNInitParameters `json:"firstN,omitempty" tf:"first_n,omitempty"`

	Last *LastInitParameters `json:"last,omitempty" tf:"last,omitempty"`

	LastDistinct *LastDistinctInitParameters `json:"lastDistinct,omitempty" tf:"last_distinct,omitempty"`

	LastN *LastNInitParameters `json:"lastN,omitempty" tf:"last_n,omitempty"`

	Max *MaxInitParameters `json:"max,omitempty" tf:"max,omitempty"`

	Min *MinInitParameters `json:"min,omitempty" tf:"min,omitempty"`

	StddevPop *StddevPopInitParameters `json:"stddevPop,omitempty" tf:"stddev_pop,omitempty"`

	StddevSamp *StddevSampInitParameters `json:"stddevSamp,omitempty" tf:"stddev_samp,omitempty"`

	Sum *SumInitParameters `json:"sum,omitempty" tf:"sum,omitempty"`

	TimeWindow *TimeWindowInitParameters `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	VarPop *VarPopInitParameters `json:"varPop,omitempty" tf:"var_pop,omitempty"`

	VarSamp *VarSampInitParameters `json:"varSamp,omitempty" tf:"var_samp,omitempty"`
}

type AggregationFunctionObservation struct {
	ApproxCountDistinct *ApproxCountDistinctObservation `json:"approxCountDistinct,omitempty" tf:"approx_count_distinct,omitempty"`

	ApproxPercentile *ApproxPercentileObservation `json:"approxPercentile,omitempty" tf:"approx_percentile,omitempty"`

	Avg *AvgObservation `json:"avg,omitempty" tf:"avg,omitempty"`

	CountFunction *CountFunctionObservation `json:"countFunction,omitempty" tf:"count_function,omitempty"`

	First *FirstObservation `json:"first,omitempty" tf:"first,omitempty"`

	FirstDistinct *FirstDistinctObservation `json:"firstDistinct,omitempty" tf:"first_distinct,omitempty"`

	FirstN *FirstNObservation `json:"firstN,omitempty" tf:"first_n,omitempty"`

	Last *LastObservation `json:"last,omitempty" tf:"last,omitempty"`

	LastDistinct *LastDistinctObservation `json:"lastDistinct,omitempty" tf:"last_distinct,omitempty"`

	LastN *LastNObservation `json:"lastN,omitempty" tf:"last_n,omitempty"`

	Max *MaxObservation `json:"max,omitempty" tf:"max,omitempty"`

	Min *MinObservation `json:"min,omitempty" tf:"min,omitempty"`

	StddevPop *StddevPopObservation `json:"stddevPop,omitempty" tf:"stddev_pop,omitempty"`

	StddevSamp *StddevSampObservation `json:"stddevSamp,omitempty" tf:"stddev_samp,omitempty"`

	Sum *SumObservation `json:"sum,omitempty" tf:"sum,omitempty"`

	TimeWindow *TimeWindowObservation `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	VarPop *VarPopObservation `json:"varPop,omitempty" tf:"var_pop,omitempty"`

	VarSamp *VarSampObservation `json:"varSamp,omitempty" tf:"var_samp,omitempty"`
}

type AggregationFunctionParameters struct {

	// +kubebuilder:validation:Optional
	ApproxCountDistinct *ApproxCountDistinctParameters `json:"approxCountDistinct,omitempty" tf:"approx_count_distinct,omitempty"`

	// +kubebuilder:validation:Optional
	ApproxPercentile *ApproxPercentileParameters `json:"approxPercentile,omitempty" tf:"approx_percentile,omitempty"`

	// +kubebuilder:validation:Optional
	Avg *AvgParameters `json:"avg,omitempty" tf:"avg,omitempty"`

	// +kubebuilder:validation:Optional
	CountFunction *CountFunctionParameters `json:"countFunction,omitempty" tf:"count_function,omitempty"`

	// +kubebuilder:validation:Optional
	First *FirstParameters `json:"first,omitempty" tf:"first,omitempty"`

	// +kubebuilder:validation:Optional
	FirstDistinct *FirstDistinctParameters `json:"firstDistinct,omitempty" tf:"first_distinct,omitempty"`

	// +kubebuilder:validation:Optional
	FirstN *FirstNParameters `json:"firstN,omitempty" tf:"first_n,omitempty"`

	// +kubebuilder:validation:Optional
	Last *LastParameters `json:"last,omitempty" tf:"last,omitempty"`

	// +kubebuilder:validation:Optional
	LastDistinct *LastDistinctParameters `json:"lastDistinct,omitempty" tf:"last_distinct,omitempty"`

	// +kubebuilder:validation:Optional
	LastN *LastNParameters `json:"lastN,omitempty" tf:"last_n,omitempty"`

	// +kubebuilder:validation:Optional
	Max *MaxParameters `json:"max,omitempty" tf:"max,omitempty"`

	// +kubebuilder:validation:Optional
	Min *MinParameters `json:"min,omitempty" tf:"min,omitempty"`

	// +kubebuilder:validation:Optional
	StddevPop *StddevPopParameters `json:"stddevPop,omitempty" tf:"stddev_pop,omitempty"`

	// +kubebuilder:validation:Optional
	StddevSamp *StddevSampParameters `json:"stddevSamp,omitempty" tf:"stddev_samp,omitempty"`

	// +kubebuilder:validation:Optional
	Sum *SumParameters `json:"sum,omitempty" tf:"sum,omitempty"`

	// +kubebuilder:validation:Optional
	TimeWindow *TimeWindowParameters `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	// +kubebuilder:validation:Optional
	VarPop *VarPopParameters `json:"varPop,omitempty" tf:"var_pop,omitempty"`

	// +kubebuilder:validation:Optional
	VarSamp *VarSampParameters `json:"varSamp,omitempty" tf:"var_samp,omitempty"`
}

type ApproxCountDistinctInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	RelativeSd *float64 `json:"relativeSd,omitempty" tf:"relative_sd,omitempty"`
}

type ApproxCountDistinctObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	RelativeSd *float64 `json:"relativeSd,omitempty" tf:"relative_sd,omitempty"`
}

type ApproxCountDistinctParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`

	// +kubebuilder:validation:Optional
	RelativeSd *float64 `json:"relativeSd,omitempty" tf:"relative_sd,omitempty"`
}

type ApproxPercentileInitParameters struct {
	Accuracy *float64 `json:"accuracy,omitempty" tf:"accuracy,omitempty"`

	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	Percentile *float64 `json:"percentile,omitempty" tf:"percentile,omitempty"`
}

type ApproxPercentileObservation struct {
	Accuracy *float64 `json:"accuracy,omitempty" tf:"accuracy,omitempty"`

	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	Percentile *float64 `json:"percentile,omitempty" tf:"percentile,omitempty"`
}

type ApproxPercentileParameters struct {

	// +kubebuilder:validation:Optional
	Accuracy *float64 `json:"accuracy,omitempty" tf:"accuracy,omitempty"`

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`

	// +kubebuilder:validation:Optional
	Percentile *float64 `json:"percentile" tf:"percentile,omitempty"`
}

type AvgInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type AvgObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type AvgParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type ColumnSelectionInitParameters struct {
	Column *string `json:"column,omitempty" tf:"column,omitempty"`
}

type ColumnSelectionObservation struct {
	Column *string `json:"column,omitempty" tf:"column,omitempty"`
}

type ColumnSelectionParameters struct {

	// +kubebuilder:validation:Optional
	Column *string `json:"column" tf:"column,omitempty"`
}

type ContinuousInitParameters struct {
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type ContinuousObservation struct {
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type ContinuousParameters struct {

	// +kubebuilder:validation:Optional
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration" tf:"window_duration,omitempty"`
}

type CountFunctionInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type CountFunctionObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type CountFunctionParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type CustomUdfInitParameters struct {
	FunctionPath *string `json:"functionPath,omitempty" tf:"function_path,omitempty"`

	InputBindings []InputBindingsInitParameters `json:"inputBindings,omitempty" tf:"input_bindings,omitempty"`
}

type CustomUdfObservation struct {
	FunctionPath *string `json:"functionPath,omitempty" tf:"function_path,omitempty"`

	InputBindings []InputBindingsObservation `json:"inputBindings,omitempty" tf:"input_bindings,omitempty"`
}

type CustomUdfParameters struct {

	// +kubebuilder:validation:Optional
	FunctionPath *string `json:"functionPath" tf:"function_path,omitempty"`

	// +kubebuilder:validation:Optional
	InputBindings []InputBindingsParameters `json:"inputBindings,omitempty" tf:"input_bindings,omitempty"`
}

type DeltaTableSourceInitParameters struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type DeltaTableSourceObservation struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type DeltaTableSourceParameters struct {

	// +kubebuilder:validation:Optional
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	// +kubebuilder:validation:Optional
	EntityColumns []*string `json:"entityColumns,omitempty" tf:"entity_columns,omitempty"`

	// +kubebuilder:validation:Optional
	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName" tf:"full_name,omitempty"`

	// +kubebuilder:validation:Optional
	TimeseriesColumn *string `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`

	// +kubebuilder:validation:Optional
	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type EntitiesInitParameters struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EntitiesObservation struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EntitiesParameters struct {

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type EntityColumnIdentifiersInitParameters struct {
	VariantExprPath *string `json:"variantExprPath,omitempty" tf:"variant_expr_path,omitempty"`
}

type EntityColumnIdentifiersObservation struct {
	VariantExprPath *string `json:"variantExprPath,omitempty" tf:"variant_expr_path,omitempty"`
}

type EntityColumnIdentifiersParameters struct {

	// +kubebuilder:validation:Optional
	VariantExprPath *string `json:"variantExprPath" tf:"variant_expr_path,omitempty"`
}

type ExtraParametersInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ExtraParametersObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ExtraParametersParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type FeatureEngineeringFeatureInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Entities []EntitiesInitParameters `json:"entities,omitempty" tf:"entities,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	Function *FunctionInitParameters `json:"function,omitempty" tf:"function,omitempty"`

	Inputs []*string `json:"inputs,omitempty" tf:"inputs,omitempty"`

	LineageContext *LineageContextInitParameters `json:"lineageContext,omitempty" tf:"lineage_context,omitempty"`

	ProviderConfig *ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	Source *SourceInitParameters `json:"source,omitempty" tf:"source,omitempty"`

	TimeWindow *FeatureEngineeringFeatureTimeWindowInitParameters `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	TimeseriesColumn *TimeseriesColumnInitParameters `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`
}

type FeatureEngineeringFeatureObservation struct {
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Entities []EntitiesObservation `json:"entities,omitempty" tf:"entities,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	Function *FunctionObservation `json:"function,omitempty" tf:"function,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Inputs []*string `json:"inputs,omitempty" tf:"inputs,omitempty"`

	LineageContext *LineageContextObservation `json:"lineageContext,omitempty" tf:"lineage_context,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ProviderConfig *ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	Source *SourceObservation `json:"source,omitempty" tf:"source,omitempty"`

	TimeWindow *FeatureEngineeringFeatureTimeWindowObservation `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	TimeseriesColumn *TimeseriesColumnObservation `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`
}

type FeatureEngineeringFeatureParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Entities []EntitiesParameters `json:"entities,omitempty" tf:"entities,omitempty"`

	// +kubebuilder:validation:Optional
	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// +kubebuilder:validation:Optional
	Function *FunctionParameters `json:"function,omitempty" tf:"function,omitempty"`

	// +kubebuilder:validation:Optional
	Inputs []*string `json:"inputs,omitempty" tf:"inputs,omitempty"`

	// +kubebuilder:validation:Optional
	LineageContext *LineageContextParameters `json:"lineageContext,omitempty" tf:"lineage_context,omitempty"`

	// +kubebuilder:validation:Optional
	ProviderConfig *ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// +kubebuilder:validation:Optional
	Source *SourceParameters `json:"source,omitempty" tf:"source,omitempty"`

	// +kubebuilder:validation:Optional
	TimeWindow *FeatureEngineeringFeatureTimeWindowParameters `json:"timeWindow,omitempty" tf:"time_window,omitempty"`

	// +kubebuilder:validation:Optional
	TimeseriesColumn *TimeseriesColumnParameters `json:"timeseriesColumn,omitempty" tf:"timeseries_column,omitempty"`
}

type FeatureEngineeringFeatureTimeWindowInitParameters struct {
	Continuous *TimeWindowContinuousInitParameters `json:"continuous,omitempty" tf:"continuous,omitempty"`

	Rolling *TimeWindowRollingInitParameters `json:"rolling,omitempty" tf:"rolling,omitempty"`

	Sawtooth *TimeWindowSawtoothInitParameters `json:"sawtooth,omitempty" tf:"sawtooth,omitempty"`

	Sliding *TimeWindowSlidingInitParameters `json:"sliding,omitempty" tf:"sliding,omitempty"`

	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	Tumbling *TimeWindowTumblingInitParameters `json:"tumbling,omitempty" tf:"tumbling,omitempty"`
}

type FeatureEngineeringFeatureTimeWindowObservation struct {
	Continuous *TimeWindowContinuousObservation `json:"continuous,omitempty" tf:"continuous,omitempty"`

	Rolling *TimeWindowRollingObservation `json:"rolling,omitempty" tf:"rolling,omitempty"`

	Sawtooth *TimeWindowSawtoothObservation `json:"sawtooth,omitempty" tf:"sawtooth,omitempty"`

	Sliding *TimeWindowSlidingObservation `json:"sliding,omitempty" tf:"sliding,omitempty"`

	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	Tumbling *TimeWindowTumblingObservation `json:"tumbling,omitempty" tf:"tumbling,omitempty"`
}

type FeatureEngineeringFeatureTimeWindowParameters struct {

	// +kubebuilder:validation:Optional
	Continuous *TimeWindowContinuousParameters `json:"continuous,omitempty" tf:"continuous,omitempty"`

	// +kubebuilder:validation:Optional
	Rolling *TimeWindowRollingParameters `json:"rolling,omitempty" tf:"rolling,omitempty"`

	// +kubebuilder:validation:Optional
	Sawtooth *TimeWindowSawtoothParameters `json:"sawtooth,omitempty" tf:"sawtooth,omitempty"`

	// +kubebuilder:validation:Optional
	Sliding *TimeWindowSlidingParameters `json:"sliding,omitempty" tf:"sliding,omitempty"`

	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// +kubebuilder:validation:Optional
	Tumbling *TimeWindowTumblingParameters `json:"tumbling,omitempty" tf:"tumbling,omitempty"`
}

type FieldsInitParameters struct {
	DataType *string `json:"dataType,omitempty" tf:"data_type,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FieldsObservation struct {
	DataType *string `json:"dataType,omitempty" tf:"data_type,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FieldsParameters struct {

	// +kubebuilder:validation:Optional
	DataType *string `json:"dataType" tf:"data_type,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type FirstDistinctInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type FirstDistinctObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type FirstDistinctParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`

	// +kubebuilder:validation:Optional
	N *float64 `json:"n" tf:"n,omitempty"`
}

type FirstInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type FirstNInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type FirstNObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type FirstNParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`

	// +kubebuilder:validation:Optional
	N *float64 `json:"n" tf:"n,omitempty"`
}

type FirstObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type FirstParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type FlatSchemaInitParameters struct {
	Fields []FieldsInitParameters `json:"fields,omitempty" tf:"fields,omitempty"`
}

type FlatSchemaObservation struct {
	Fields []FieldsObservation `json:"fields,omitempty" tf:"fields,omitempty"`
}

type FlatSchemaParameters struct {

	// +kubebuilder:validation:Optional
	Fields []FieldsParameters `json:"fields" tf:"fields,omitempty"`
}

type FunctionInitParameters struct {
	AggregationFunction *AggregationFunctionInitParameters `json:"aggregationFunction,omitempty" tf:"aggregation_function,omitempty"`

	ColumnSelection *ColumnSelectionInitParameters `json:"columnSelection,omitempty" tf:"column_selection,omitempty"`

	CustomUdf *CustomUdfInitParameters `json:"customUdf,omitempty" tf:"custom_udf,omitempty"`

	ExtraParameters []ExtraParametersInitParameters `json:"extraParameters,omitempty" tf:"extra_parameters,omitempty"`

	FunctionType *string `json:"functionType,omitempty" tf:"function_type,omitempty"`
}

type FunctionObservation struct {
	AggregationFunction *AggregationFunctionObservation `json:"aggregationFunction,omitempty" tf:"aggregation_function,omitempty"`

	ColumnSelection *ColumnSelectionObservation `json:"columnSelection,omitempty" tf:"column_selection,omitempty"`

	CustomUdf *CustomUdfObservation `json:"customUdf,omitempty" tf:"custom_udf,omitempty"`

	ExtraParameters []ExtraParametersObservation `json:"extraParameters,omitempty" tf:"extra_parameters,omitempty"`

	FunctionType *string `json:"functionType,omitempty" tf:"function_type,omitempty"`
}

type FunctionParameters struct {

	// +kubebuilder:validation:Optional
	AggregationFunction *AggregationFunctionParameters `json:"aggregationFunction,omitempty" tf:"aggregation_function,omitempty"`

	// +kubebuilder:validation:Optional
	ColumnSelection *ColumnSelectionParameters `json:"columnSelection,omitempty" tf:"column_selection,omitempty"`

	// +kubebuilder:validation:Optional
	CustomUdf *CustomUdfParameters `json:"customUdf,omitempty" tf:"custom_udf,omitempty"`

	// +kubebuilder:validation:Optional
	ExtraParameters []ExtraParametersParameters `json:"extraParameters,omitempty" tf:"extra_parameters,omitempty"`

	// +kubebuilder:validation:Optional
	FunctionType *string `json:"functionType,omitempty" tf:"function_type,omitempty"`
}

type InputBindingsInitParameters struct {
	Column *string `json:"column,omitempty" tf:"column,omitempty"`

	Parameter *string `json:"parameter,omitempty" tf:"parameter,omitempty"`
}

type InputBindingsObservation struct {
	Column *string `json:"column,omitempty" tf:"column,omitempty"`

	Parameter *string `json:"parameter,omitempty" tf:"parameter,omitempty"`
}

type InputBindingsParameters struct {

	// +kubebuilder:validation:Optional
	Column *string `json:"column" tf:"column,omitempty"`

	// +kubebuilder:validation:Optional
	Parameter *string `json:"parameter" tf:"parameter,omitempty"`
}

type JobContextInitParameters struct {
	JobID *float64 `json:"jobId,omitempty" tf:"job_id,omitempty"`

	JobRunID *float64 `json:"jobRunId,omitempty" tf:"job_run_id,omitempty"`
}

type JobContextObservation struct {
	JobID *float64 `json:"jobId,omitempty" tf:"job_id,omitempty"`

	JobRunID *float64 `json:"jobRunId,omitempty" tf:"job_run_id,omitempty"`
}

type JobContextParameters struct {

	// +kubebuilder:validation:Optional
	JobID *float64 `json:"jobId,omitempty" tf:"job_id,omitempty"`

	// +kubebuilder:validation:Optional
	JobRunID *float64 `json:"jobRunId,omitempty" tf:"job_run_id,omitempty"`
}

type KafkaSourceInitParameters struct {
	EntityColumnIdentifiers []EntityColumnIdentifiersInitParameters `json:"entityColumnIdentifiers,omitempty" tf:"entity_column_identifiers,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	TimeseriesColumnIdentifier *TimeseriesColumnIdentifierInitParameters `json:"timeseriesColumnIdentifier,omitempty" tf:"timeseries_column_identifier,omitempty"`
}

type KafkaSourceObservation struct {
	EntityColumnIdentifiers []EntityColumnIdentifiersObservation `json:"entityColumnIdentifiers,omitempty" tf:"entity_column_identifiers,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	TimeseriesColumnIdentifier *TimeseriesColumnIdentifierObservation `json:"timeseriesColumnIdentifier,omitempty" tf:"timeseries_column_identifier,omitempty"`
}

type KafkaSourceParameters struct {

	// +kubebuilder:validation:Optional
	EntityColumnIdentifiers []EntityColumnIdentifiersParameters `json:"entityColumnIdentifiers,omitempty" tf:"entity_column_identifiers,omitempty"`

	// +kubebuilder:validation:Optional
	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	TimeseriesColumnIdentifier *TimeseriesColumnIdentifierParameters `json:"timeseriesColumnIdentifier,omitempty" tf:"timeseries_column_identifier,omitempty"`
}

type LastDistinctInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type LastDistinctObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type LastDistinctParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`

	// +kubebuilder:validation:Optional
	N *float64 `json:"n" tf:"n,omitempty"`
}

type LastInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type LastNInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type LastNObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`

	N *float64 `json:"n,omitempty" tf:"n,omitempty"`
}

type LastNParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`

	// +kubebuilder:validation:Optional
	N *float64 `json:"n" tf:"n,omitempty"`
}

type LastObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type LastParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type LatenessInitParameters struct {
	SettlingDelay *string `json:"settlingDelay,omitempty" tf:"settling_delay,omitempty"`
}

type LatenessObservation struct {
	SettlingDelay *string `json:"settlingDelay,omitempty" tf:"settling_delay,omitempty"`
}

type LatenessParameters struct {

	// +kubebuilder:validation:Optional
	SettlingDelay *string `json:"settlingDelay,omitempty" tf:"settling_delay,omitempty"`
}

type LineageContextInitParameters struct {
	JobContext *JobContextInitParameters `json:"jobContext,omitempty" tf:"job_context,omitempty"`

	NotebookID *float64 `json:"notebookId,omitempty" tf:"notebook_id,omitempty"`
}

type LineageContextObservation struct {
	JobContext *JobContextObservation `json:"jobContext,omitempty" tf:"job_context,omitempty"`

	NotebookID *float64 `json:"notebookId,omitempty" tf:"notebook_id,omitempty"`
}

type LineageContextParameters struct {

	// +kubebuilder:validation:Optional
	JobContext *JobContextParameters `json:"jobContext,omitempty" tf:"job_context,omitempty"`

	// +kubebuilder:validation:Optional
	NotebookID *float64 `json:"notebookId,omitempty" tf:"notebook_id,omitempty"`
}

type MaxInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type MaxObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type MaxParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type MinInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type MinObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type MinParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type ProviderConfigInitParameters struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ProviderConfigObservation struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ProviderConfigParameters struct {

	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type RequestSourceInitParameters struct {
	FlatSchema *FlatSchemaInitParameters `json:"flatSchema,omitempty" tf:"flat_schema,omitempty"`
}

type RequestSourceObservation struct {
	FlatSchema *FlatSchemaObservation `json:"flatSchema,omitempty" tf:"flat_schema,omitempty"`
}

type RequestSourceParameters struct {

	// +kubebuilder:validation:Optional
	FlatSchema *FlatSchemaParameters `json:"flatSchema,omitempty" tf:"flat_schema,omitempty"`
}

type RollingInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type RollingObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type RollingParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SawtoothInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SawtoothObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SawtoothParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SlidingInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	SlideDuration *string `json:"slideDuration,omitempty" tf:"slide_duration,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SlidingObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	SlideDuration *string `json:"slideDuration,omitempty" tf:"slide_duration,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SlidingParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	// +kubebuilder:validation:Optional
	SlideDuration *string `json:"slideDuration" tf:"slide_duration,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type SourceInitParameters struct {
	DeltaTableSource *DeltaTableSourceInitParameters `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`

	KafkaSource *KafkaSourceInitParameters `json:"kafkaSource,omitempty" tf:"kafka_source,omitempty"`

	Lateness *LatenessInitParameters `json:"lateness,omitempty" tf:"lateness,omitempty"`

	RequestSource *RequestSourceInitParameters `json:"requestSource,omitempty" tf:"request_source,omitempty"`

	StreamSource *StreamSourceInitParameters `json:"streamSource,omitempty" tf:"stream_source,omitempty"`
}

type SourceObservation struct {
	DeltaTableSource *DeltaTableSourceObservation `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`

	KafkaSource *KafkaSourceObservation `json:"kafkaSource,omitempty" tf:"kafka_source,omitempty"`

	Lateness *LatenessObservation `json:"lateness,omitempty" tf:"lateness,omitempty"`

	RequestSource *RequestSourceObservation `json:"requestSource,omitempty" tf:"request_source,omitempty"`

	StreamSource *StreamSourceObservation `json:"streamSource,omitempty" tf:"stream_source,omitempty"`
}

type SourceParameters struct {

	// +kubebuilder:validation:Optional
	DeltaTableSource *DeltaTableSourceParameters `json:"deltaTableSource,omitempty" tf:"delta_table_source,omitempty"`

	// +kubebuilder:validation:Optional
	KafkaSource *KafkaSourceParameters `json:"kafkaSource,omitempty" tf:"kafka_source,omitempty"`

	// +kubebuilder:validation:Optional
	Lateness *LatenessParameters `json:"lateness,omitempty" tf:"lateness,omitempty"`

	// +kubebuilder:validation:Optional
	RequestSource *RequestSourceParameters `json:"requestSource,omitempty" tf:"request_source,omitempty"`

	// +kubebuilder:validation:Optional
	StreamSource *StreamSourceParameters `json:"streamSource,omitempty" tf:"stream_source,omitempty"`
}

type StddevPopInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type StddevPopObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type StddevPopParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type StddevSampInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type StddevSampObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type StddevSampParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type StreamSourceInitParameters struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type StreamSourceObservation struct {
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type StreamSourceParameters struct {

	// +kubebuilder:validation:Optional
	DataframeSchema *string `json:"dataframeSchema,omitempty" tf:"dataframe_schema,omitempty"`

	// +kubebuilder:validation:Optional
	FilterCondition *string `json:"filterCondition,omitempty" tf:"filter_condition,omitempty"`

	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName" tf:"full_name,omitempty"`

	// +kubebuilder:validation:Optional
	TransformationSQL *string `json:"transformationSql,omitempty" tf:"transformation_sql,omitempty"`
}

type SumInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type SumObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type SumParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type TimeWindowContinuousInitParameters struct {
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowContinuousObservation struct {
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowContinuousParameters struct {

	// +kubebuilder:validation:Optional
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration" tf:"window_duration,omitempty"`
}

type TimeWindowInitParameters struct {
	Continuous *ContinuousInitParameters `json:"continuous,omitempty" tf:"continuous,omitempty"`

	Rolling *RollingInitParameters `json:"rolling,omitempty" tf:"rolling,omitempty"`

	Sawtooth *SawtoothInitParameters `json:"sawtooth,omitempty" tf:"sawtooth,omitempty"`

	Sliding *SlidingInitParameters `json:"sliding,omitempty" tf:"sliding,omitempty"`

	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	Tumbling *TumblingInitParameters `json:"tumbling,omitempty" tf:"tumbling,omitempty"`
}

type TimeWindowObservation struct {
	Continuous *ContinuousObservation `json:"continuous,omitempty" tf:"continuous,omitempty"`

	Rolling *RollingObservation `json:"rolling,omitempty" tf:"rolling,omitempty"`

	Sawtooth *SawtoothObservation `json:"sawtooth,omitempty" tf:"sawtooth,omitempty"`

	Sliding *SlidingObservation `json:"sliding,omitempty" tf:"sliding,omitempty"`

	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	Tumbling *TumblingObservation `json:"tumbling,omitempty" tf:"tumbling,omitempty"`
}

type TimeWindowParameters struct {

	// +kubebuilder:validation:Optional
	Continuous *ContinuousParameters `json:"continuous,omitempty" tf:"continuous,omitempty"`

	// +kubebuilder:validation:Optional
	Rolling *RollingParameters `json:"rolling,omitempty" tf:"rolling,omitempty"`

	// +kubebuilder:validation:Optional
	Sawtooth *SawtoothParameters `json:"sawtooth,omitempty" tf:"sawtooth,omitempty"`

	// +kubebuilder:validation:Optional
	Sliding *SlidingParameters `json:"sliding,omitempty" tf:"sliding,omitempty"`

	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// +kubebuilder:validation:Optional
	Tumbling *TumblingParameters `json:"tumbling,omitempty" tf:"tumbling,omitempty"`
}

type TimeWindowRollingInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowRollingObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowRollingParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowSawtoothInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowSawtoothObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowSawtoothParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowSlidingInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	SlideDuration *string `json:"slideDuration,omitempty" tf:"slide_duration,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowSlidingObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	SlideDuration *string `json:"slideDuration,omitempty" tf:"slide_duration,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowSlidingParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	// +kubebuilder:validation:Optional
	SlideDuration *string `json:"slideDuration" tf:"slide_duration,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowTumblingInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowTumblingObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TimeWindowTumblingParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration" tf:"window_duration,omitempty"`
}

type TimeseriesColumnIdentifierInitParameters struct {
	VariantExprPath *string `json:"variantExprPath,omitempty" tf:"variant_expr_path,omitempty"`
}

type TimeseriesColumnIdentifierObservation struct {
	VariantExprPath *string `json:"variantExprPath,omitempty" tf:"variant_expr_path,omitempty"`
}

type TimeseriesColumnIdentifierParameters struct {

	// +kubebuilder:validation:Optional
	VariantExprPath *string `json:"variantExprPath" tf:"variant_expr_path,omitempty"`
}

type TimeseriesColumnInitParameters struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TimeseriesColumnObservation struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TimeseriesColumnParameters struct {

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type TumblingInitParameters struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TumblingObservation struct {
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	WindowDuration *string `json:"windowDuration,omitempty" tf:"window_duration,omitempty"`
}

type TumblingParameters struct {

	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// +kubebuilder:validation:Optional
	Offset *string `json:"offset,omitempty" tf:"offset,omitempty"`

	// +kubebuilder:validation:Optional
	WindowDuration *string `json:"windowDuration" tf:"window_duration,omitempty"`
}

type VarPopInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type VarPopObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type VarPopParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

type VarSampInitParameters struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type VarSampObservation struct {
	Input *string `json:"input,omitempty" tf:"input,omitempty"`
}

type VarSampParameters struct {

	// +kubebuilder:validation:Optional
	Input *string `json:"input" tf:"input,omitempty"`
}

// FeatureEngineeringFeatureSpec defines the desired state of FeatureEngineeringFeature
type FeatureEngineeringFeatureSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FeatureEngineeringFeatureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureEngineeringFeatureInitParameters `json:"initProvider,omitempty"`
}

// FeatureEngineeringFeatureStatus defines the observed state of FeatureEngineeringFeature.
type FeatureEngineeringFeatureStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FeatureEngineeringFeatureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureEngineeringFeature is the Schema for the FeatureEngineeringFeatures API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type FeatureEngineeringFeature struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fullName) || (has(self.initProvider) && has(self.initProvider.fullName))",message="spec.forProvider.fullName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__function__) || (has(self.initProvider) && has(self.initProvider.__function__))",message="spec.forProvider.function is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.source) || (has(self.initProvider) && has(self.initProvider.source))",message="spec.forProvider.source is a required parameter"
	Spec   FeatureEngineeringFeatureSpec   `json:"spec"`
	Status FeatureEngineeringFeatureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureEngineeringFeatureList contains a list of FeatureEngineeringFeatures
type FeatureEngineeringFeatureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureEngineeringFeature `json:"items"`
}

// Repository type metadata.
var (
	FeatureEngineeringFeature_Kind             = "FeatureEngineeringFeature"
	FeatureEngineeringFeature_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureEngineeringFeature_Kind}.String()
	FeatureEngineeringFeature_KindAPIVersion   = FeatureEngineeringFeature_Kind + "." + CRDGroupVersion.String()
	FeatureEngineeringFeature_GroupVersionKind = CRDGroupVersion.WithKind(FeatureEngineeringFeature_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureEngineeringFeature{}, &FeatureEngineeringFeatureList{})
}
