// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CronScheduleTriggerInitParameters struct {
	CronExpression *string `json:"cronExpression,omitempty" tf:"cron_expression,omitempty"`

	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type CronScheduleTriggerObservation struct {
	CronExpression *string `json:"cronExpression,omitempty" tf:"cron_expression,omitempty"`

	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type CronScheduleTriggerParameters struct {

	// +kubebuilder:validation:Optional
	CronExpression *string `json:"cronExpression,omitempty" tf:"cron_expression,omitempty"`

	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type FeatureEngineeringMaterializedFeatureInitParameters struct {
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	CronScheduleTrigger *CronScheduleTriggerInitParameters `json:"cronScheduleTrigger,omitempty" tf:"cron_schedule_trigger,omitempty"`

	FeatureName *string `json:"featureName,omitempty" tf:"feature_name,omitempty"`

	OfflineStoreConfig *OfflineStoreConfigInitParameters `json:"offlineStoreConfig,omitempty" tf:"offline_store_config,omitempty"`

	OnlineStoreConfig *OnlineStoreConfigInitParameters `json:"onlineStoreConfig,omitempty" tf:"online_store_config,omitempty"`

	PipelineScheduleState *string `json:"pipelineScheduleState,omitempty" tf:"pipeline_schedule_state,omitempty"`

	ProviderConfig *FeatureEngineeringMaterializedFeatureProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	StreamingMode *StreamingModeInitParameters `json:"streamingMode,omitempty" tf:"streaming_mode,omitempty"`

	TableTrigger *TableTriggerInitParameters `json:"tableTrigger,omitempty" tf:"table_trigger,omitempty"`

	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FeatureEngineeringMaterializedFeatureObservation struct {
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	CronScheduleTrigger *CronScheduleTriggerObservation `json:"cronScheduleTrigger,omitempty" tf:"cron_schedule_trigger,omitempty"`

	FeatureName *string `json:"featureName,omitempty" tf:"feature_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IsOnline *bool `json:"isOnline,omitempty" tf:"is_online,omitempty"`

	LastMaterializationTime *string `json:"lastMaterializationTime,omitempty" tf:"last_materialization_time,omitempty"`

	LatestBackfillOperation *string `json:"latestBackfillOperation,omitempty" tf:"latest_backfill_operation,omitempty"`

	MaterializedFeatureID *string `json:"materializedFeatureId,omitempty" tf:"materialized_feature_id,omitempty"`

	OfflineStoreConfig *OfflineStoreConfigObservation `json:"offlineStoreConfig,omitempty" tf:"offline_store_config,omitempty"`

	OnlineStoreConfig *OnlineStoreConfigObservation `json:"onlineStoreConfig,omitempty" tf:"online_store_config,omitempty"`

	PipelineScheduleState *string `json:"pipelineScheduleState,omitempty" tf:"pipeline_schedule_state,omitempty"`

	ProviderConfig *FeatureEngineeringMaterializedFeatureProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	StreamingMode *StreamingModeObservation `json:"streamingMode,omitempty" tf:"streaming_mode,omitempty"`

	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`

	TableTrigger *TableTriggerParameters `json:"tableTrigger,omitempty" tf:"table_trigger,omitempty"`

	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FeatureEngineeringMaterializedFeatureParameters struct {

	// +kubebuilder:validation:Optional
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	// +kubebuilder:validation:Optional
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// +kubebuilder:validation:Optional
	CronScheduleTrigger *CronScheduleTriggerParameters `json:"cronScheduleTrigger,omitempty" tf:"cron_schedule_trigger,omitempty"`

	// +kubebuilder:validation:Optional
	FeatureName *string `json:"featureName,omitempty" tf:"feature_name,omitempty"`

	// +kubebuilder:validation:Optional
	OfflineStoreConfig *OfflineStoreConfigParameters `json:"offlineStoreConfig,omitempty" tf:"offline_store_config,omitempty"`

	// +kubebuilder:validation:Optional
	OnlineStoreConfig *OnlineStoreConfigParameters `json:"onlineStoreConfig,omitempty" tf:"online_store_config,omitempty"`

	// +kubebuilder:validation:Optional
	PipelineScheduleState *string `json:"pipelineScheduleState,omitempty" tf:"pipeline_schedule_state,omitempty"`

	// +kubebuilder:validation:Optional
	ProviderConfig *FeatureEngineeringMaterializedFeatureProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// +kubebuilder:validation:Optional
	StreamingMode *StreamingModeParameters `json:"streamingMode,omitempty" tf:"streaming_mode,omitempty"`

	// +kubebuilder:validation:Optional
	TableTrigger *TableTriggerParameters `json:"tableTrigger,omitempty" tf:"table_trigger,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FeatureEngineeringMaterializedFeatureProviderConfigInitParameters struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type FeatureEngineeringMaterializedFeatureProviderConfigObservation struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type FeatureEngineeringMaterializedFeatureProviderConfigParameters struct {

	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type OfflineStoreConfigInitParameters struct {
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type OfflineStoreConfigObservation struct {
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type OfflineStoreConfigParameters struct {

	// +kubebuilder:validation:Optional
	CatalogName *string `json:"catalogName" tf:"catalog_name,omitempty"`

	// +kubebuilder:validation:Optional
	SchemaName *string `json:"schemaName" tf:"schema_name,omitempty"`

	// +kubebuilder:validation:Optional
	TableNamePrefix *string `json:"tableNamePrefix" tf:"table_name_prefix,omitempty"`
}

type OnlineStoreConfigInitParameters struct {
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	OnlineStoreName *string `json:"onlineStoreName,omitempty" tf:"online_store_name,omitempty"`

	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type OnlineStoreConfigObservation struct {
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	OnlineStoreName *string `json:"onlineStoreName,omitempty" tf:"online_store_name,omitempty"`

	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type OnlineStoreConfigParameters struct {

	// +kubebuilder:validation:Optional
	CatalogName *string `json:"catalogName" tf:"catalog_name,omitempty"`

	// +kubebuilder:validation:Optional
	OnlineStoreName *string `json:"onlineStoreName" tf:"online_store_name,omitempty"`

	// +kubebuilder:validation:Optional
	SchemaName *string `json:"schemaName" tf:"schema_name,omitempty"`

	// +kubebuilder:validation:Optional
	TableNamePrefix *string `json:"tableNamePrefix" tf:"table_name_prefix,omitempty"`
}

type StreamingModeInitParameters struct {
	FreshnessTarget *string `json:"freshnessTarget,omitempty" tf:"freshness_target,omitempty"`

	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type StreamingModeObservation struct {
	FreshnessTarget *string `json:"freshnessTarget,omitempty" tf:"freshness_target,omitempty"`

	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type StreamingModeParameters struct {

	// +kubebuilder:validation:Optional
	FreshnessTarget *string `json:"freshnessTarget,omitempty" tf:"freshness_target,omitempty"`

	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type TableTriggerInitParameters struct {
}

type TableTriggerObservation struct {
}

type TableTriggerParameters struct {
}

// FeatureEngineeringMaterializedFeatureSpec defines the desired state of FeatureEngineeringMaterializedFeature
type FeatureEngineeringMaterializedFeatureSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FeatureEngineeringMaterializedFeatureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureEngineeringMaterializedFeatureInitParameters `json:"initProvider,omitempty"`
}

// FeatureEngineeringMaterializedFeatureStatus defines the observed state of FeatureEngineeringMaterializedFeature.
type FeatureEngineeringMaterializedFeatureStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FeatureEngineeringMaterializedFeatureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureEngineeringMaterializedFeature is the Schema for the FeatureEngineeringMaterializedFeatures API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type FeatureEngineeringMaterializedFeature struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.featureName) || (has(self.initProvider) && has(self.initProvider.featureName))",message="spec.forProvider.featureName is a required parameter"
	Spec   FeatureEngineeringMaterializedFeatureSpec   `json:"spec"`
	Status FeatureEngineeringMaterializedFeatureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureEngineeringMaterializedFeatureList contains a list of FeatureEngineeringMaterializedFeatures
type FeatureEngineeringMaterializedFeatureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureEngineeringMaterializedFeature `json:"items"`
}

// Repository type metadata.
var (
	FeatureEngineeringMaterializedFeature_Kind             = "FeatureEngineeringMaterializedFeature"
	FeatureEngineeringMaterializedFeature_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureEngineeringMaterializedFeature_Kind}.String()
	FeatureEngineeringMaterializedFeature_KindAPIVersion   = FeatureEngineeringMaterializedFeature_Kind + "." + CRDGroupVersion.String()
	FeatureEngineeringMaterializedFeature_GroupVersionKind = CRDGroupVersion.WithKind(FeatureEngineeringMaterializedFeature_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureEngineeringMaterializedFeature{}, &FeatureEngineeringMaterializedFeatureList{})
}
