# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: settings.databricks.m.crossplane.io/v1beta1
kind: AccountSettingUserPreferenceV2
metadata:
  annotations:
    meta.upbound.io/example-id: settings/v1beta1/accountsettinguserpreferencev2
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider: {}
