// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *AwsS3Mount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AzureAdlsGen1Mount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AzureAdlsGen2Mount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AzureBlobMount) Hub() {}
