# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: unity.databricks.crossplane.io/v1beta1
kind: QualityMonitorV2
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1beta1/qualitymonitorv2
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    objectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: this
    objectType: schema

---

apiVersion: unity.databricks.crossplane.io/v1beta1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1beta1/qualitymonitorv2
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    catalogNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: my_schema
