// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *AccountIAMDirectGroupMemberV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountIAMGroupV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountIAMServicePrincipalV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountIAMUserV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountIAMWorkspaceAssignmentV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceIAMDirectGroupMemberV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceIAMGroupV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceIAMServicePrincipalV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceIAMUserV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceIAMWorkspaceAssignmentV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceIAMWorkspaceIdentityDetailV2) Hub() {}
