// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WorkspaceIAMUserV2FullNameInitParameters struct {

	// (string, optional)
	FamilyName *string `json:"familyName,omitempty" tf:"family_name,omitempty"`

	// (string, optional)
	GivenName *string `json:"givenName,omitempty" tf:"given_name,omitempty"`
}

type WorkspaceIAMUserV2FullNameObservation struct {

	// (string, optional)
	FamilyName *string `json:"familyName,omitempty" tf:"family_name,omitempty"`

	// (string, optional)
	GivenName *string `json:"givenName,omitempty" tf:"given_name,omitempty"`
}

type WorkspaceIAMUserV2FullNameParameters struct {

	// (string, optional)
	// +kubebuilder:validation:Optional
	FamilyName *string `json:"familyName,omitempty" tf:"family_name,omitempty"`

	// (string, optional)
	// +kubebuilder:validation:Optional
	GivenName *string `json:"givenName,omitempty" tf:"given_name,omitempty"`
}

type WorkspaceIAMUserV2InitParameters struct {

	// The activity status of a user in a Databricks account. Possible values are: ACTIVE, INACTIVE
	AccountUserStatus *string `json:"accountUserStatus,omitempty" tf:"account_user_status,omitempty"`

	// ExternalId of the user in the customer's IdP
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (UserFullName, required)
	FullName *WorkspaceIAMUserV2FullNameInitParameters `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMUserV2ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Username/email of the user
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type WorkspaceIAMUserV2Observation struct {

	// The accountId parent of the user in Databricks
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// The activity status of a user in a Databricks account. Possible values are: ACTIVE, INACTIVE
	AccountUserStatus *string `json:"accountUserStatus,omitempty" tf:"account_user_status,omitempty"`

	// ExternalId of the user in the customer's IdP
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (UserFullName, required)
	FullName *WorkspaceIAMUserV2FullNameObservation `json:"fullName,omitempty" tf:"full_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMUserV2ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Internal userId of the user in Databricks
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Username/email of the user
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type WorkspaceIAMUserV2Parameters struct {

	// The activity status of a user in a Databricks account. Possible values are: ACTIVE, INACTIVE
	// +kubebuilder:validation:Optional
	AccountUserStatus *string `json:"accountUserStatus,omitempty" tf:"account_user_status,omitempty"`

	// ExternalId of the user in the customer's IdP
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (UserFullName, required)
	// +kubebuilder:validation:Optional
	FullName *WorkspaceIAMUserV2FullNameParameters `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *WorkspaceIAMUserV2ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Username/email of the user
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type WorkspaceIAMUserV2ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMUserV2ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMUserV2ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

// WorkspaceIAMUserV2Spec defines the desired state of WorkspaceIAMUserV2
type WorkspaceIAMUserV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkspaceIAMUserV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceIAMUserV2InitParameters `json:"initProvider,omitempty"`
}

// WorkspaceIAMUserV2Status defines the observed state of WorkspaceIAMUserV2.
type WorkspaceIAMUserV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WorkspaceIAMUserV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceIAMUserV2 is the Schema for the WorkspaceIAMUserV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type WorkspaceIAMUserV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountUserStatus) || (has(self.initProvider) && has(self.initProvider.accountUserStatus))",message="spec.forProvider.accountUserStatus is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fullName) || (has(self.initProvider) && has(self.initProvider.fullName))",message="spec.forProvider.fullName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   WorkspaceIAMUserV2Spec   `json:"spec"`
	Status WorkspaceIAMUserV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceIAMUserV2List contains a list of WorkspaceIAMUserV2s
type WorkspaceIAMUserV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceIAMUserV2 `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceIAMUserV2_Kind             = "WorkspaceIAMUserV2"
	WorkspaceIAMUserV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceIAMUserV2_Kind}.String()
	WorkspaceIAMUserV2_KindAPIVersion   = WorkspaceIAMUserV2_Kind + "." + CRDGroupVersion.String()
	WorkspaceIAMUserV2_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceIAMUserV2_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceIAMUserV2{}, &WorkspaceIAMUserV2List{})
}
