// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WorkspaceIAMWorkspaceIdentityDetailV2InitParameters struct {

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMWorkspaceIdentityDetailV2ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// The activity status of an identity in a Databricks workspace. Possible values are: ACTIVE, INACTIVE
	WorkspaceIdentityStatus *string `json:"workspaceIdentityStatus,omitempty" tf:"workspace_identity_status,omitempty"`
}

type WorkspaceIAMWorkspaceIdentityDetailV2Observation struct {

	// The type of assignment the principal has to the workspace (direct or indirect). Possible values are: DIRECT, INDIRECT
	AssignmentType *string `json:"assignmentType,omitempty" tf:"assignment_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The internal ID of the principal (user/sp/group) in Databricks
	PrincipalID *float64 `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// The type of the principal (user/service principal/group). Possible values are: GROUP, SERVICE_PRINCIPAL, USER
	PrincipalType *string `json:"principalType,omitempty" tf:"principal_type,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMWorkspaceIdentityDetailV2ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// The activity status of an identity in a Databricks workspace. Possible values are: ACTIVE, INACTIVE
	WorkspaceIdentityStatus *string `json:"workspaceIdentityStatus,omitempty" tf:"workspace_identity_status,omitempty"`
}

type WorkspaceIAMWorkspaceIdentityDetailV2Parameters struct {

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *WorkspaceIAMWorkspaceIdentityDetailV2ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// The activity status of an identity in a Databricks workspace. Possible values are: ACTIVE, INACTIVE
	// +kubebuilder:validation:Optional
	WorkspaceIdentityStatus *string `json:"workspaceIdentityStatus,omitempty" tf:"workspace_identity_status,omitempty"`
}

type WorkspaceIAMWorkspaceIdentityDetailV2ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceIdentityDetailV2ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceIdentityDetailV2ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

// WorkspaceIAMWorkspaceIdentityDetailV2Spec defines the desired state of WorkspaceIAMWorkspaceIdentityDetailV2
type WorkspaceIAMWorkspaceIdentityDetailV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkspaceIAMWorkspaceIdentityDetailV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceIAMWorkspaceIdentityDetailV2InitParameters `json:"initProvider,omitempty"`
}

// WorkspaceIAMWorkspaceIdentityDetailV2Status defines the observed state of WorkspaceIAMWorkspaceIdentityDetailV2.
type WorkspaceIAMWorkspaceIdentityDetailV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WorkspaceIAMWorkspaceIdentityDetailV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceIAMWorkspaceIdentityDetailV2 is the Schema for the WorkspaceIAMWorkspaceIdentityDetailV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type WorkspaceIAMWorkspaceIdentityDetailV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkspaceIAMWorkspaceIdentityDetailV2Spec   `json:"spec"`
	Status            WorkspaceIAMWorkspaceIdentityDetailV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceIAMWorkspaceIdentityDetailV2List contains a list of WorkspaceIAMWorkspaceIdentityDetailV2s
type WorkspaceIAMWorkspaceIdentityDetailV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceIAMWorkspaceIdentityDetailV2 `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceIAMWorkspaceIdentityDetailV2_Kind             = "WorkspaceIAMWorkspaceIdentityDetailV2"
	WorkspaceIAMWorkspaceIdentityDetailV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceIAMWorkspaceIdentityDetailV2_Kind}.String()
	WorkspaceIAMWorkspaceIdentityDetailV2_KindAPIVersion   = WorkspaceIAMWorkspaceIdentityDetailV2_Kind + "." + CRDGroupVersion.String()
	WorkspaceIAMWorkspaceIdentityDetailV2_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceIAMWorkspaceIdentityDetailV2_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceIAMWorkspaceIdentityDetailV2{}, &WorkspaceIAMWorkspaceIdentityDetailV2List{})
}
