// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WorkspaceIAMWorkspaceAssignmentV2InitParameters struct {

	// Entitlements granted directly to the principal on this workspace. This is the only
	// client-settable field. Create and update manage exactly this set, including entitlements the
	// principal also holds through a group.
	// List responses leave this field empty. Get a single principal to read its entitlements
	// +listType=set
	Entitlements []*string `json:"entitlements,omitempty" tf:"entitlements,omitempty"`

	// The internal ID of the principal (user/sp/group) in Databricks
	PrincipalID *float64 `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMWorkspaceAssignmentV2ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *float64 `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceAssignmentV2Observation struct {

	// The account ID parent of the workspace where the principal is assigned
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Every entitlement the principal holds in this workspace, whether granted directly or through
	// group membership. Get responses populate this field. List responses leave it empty
	// +listType=set
	EffectiveEntitlements []*string `json:"effectiveEntitlements,omitempty" tf:"effective_entitlements,omitempty"`

	// Entitlements granted directly to the principal on this workspace. This is the only
	// client-settable field. Create and update manage exactly this set, including entitlements the
	// principal also holds through a group.
	// List responses leave this field empty. Get a single principal to read its entitlements
	// +listType=set
	Entitlements []*string `json:"entitlements,omitempty" tf:"entitlements,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The internal ID of the principal (user/sp/group) in Databricks
	PrincipalID *float64 `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// The type of the principal (user/service principal/group) that is assigned. Possible values are: GROUP, SERVICE_PRINCIPAL, USER
	PrincipalType *string `json:"principalType,omitempty" tf:"principal_type,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceIAMWorkspaceAssignmentV2ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *float64 `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceAssignmentV2Parameters struct {

	// Entitlements granted directly to the principal on this workspace. This is the only
	// client-settable field. Create and update manage exactly this set, including entitlements the
	// principal also holds through a group.
	// List responses leave this field empty. Get a single principal to read its entitlements
	// +kubebuilder:validation:Optional
	// +listType=set
	Entitlements []*string `json:"entitlements,omitempty" tf:"entitlements,omitempty"`

	// The internal ID of the principal (user/sp/group) in Databricks
	// +kubebuilder:validation:Optional
	PrincipalID *float64 `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *WorkspaceIAMWorkspaceAssignmentV2ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *float64 `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceAssignmentV2ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceAssignmentV2ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceIAMWorkspaceAssignmentV2ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

// WorkspaceIAMWorkspaceAssignmentV2Spec defines the desired state of WorkspaceIAMWorkspaceAssignmentV2
type WorkspaceIAMWorkspaceAssignmentV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkspaceIAMWorkspaceAssignmentV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceIAMWorkspaceAssignmentV2InitParameters `json:"initProvider,omitempty"`
}

// WorkspaceIAMWorkspaceAssignmentV2Status defines the observed state of WorkspaceIAMWorkspaceAssignmentV2.
type WorkspaceIAMWorkspaceAssignmentV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WorkspaceIAMWorkspaceAssignmentV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceIAMWorkspaceAssignmentV2 is the Schema for the WorkspaceIAMWorkspaceAssignmentV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type WorkspaceIAMWorkspaceAssignmentV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.principalId) || (has(self.initProvider) && has(self.initProvider.principalId))",message="spec.forProvider.principalId is a required parameter"
	Spec   WorkspaceIAMWorkspaceAssignmentV2Spec   `json:"spec"`
	Status WorkspaceIAMWorkspaceAssignmentV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceIAMWorkspaceAssignmentV2List contains a list of WorkspaceIAMWorkspaceAssignmentV2s
type WorkspaceIAMWorkspaceAssignmentV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceIAMWorkspaceAssignmentV2 `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceIAMWorkspaceAssignmentV2_Kind             = "WorkspaceIAMWorkspaceAssignmentV2"
	WorkspaceIAMWorkspaceAssignmentV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceIAMWorkspaceAssignmentV2_Kind}.String()
	WorkspaceIAMWorkspaceAssignmentV2_KindAPIVersion   = WorkspaceIAMWorkspaceAssignmentV2_Kind + "." + CRDGroupVersion.String()
	WorkspaceIAMWorkspaceAssignmentV2_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceIAMWorkspaceAssignmentV2_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceIAMWorkspaceAssignmentV2{}, &WorkspaceIAMWorkspaceAssignmentV2List{})
}
