// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code transformed by upjet. DO NOT EDIT.

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	apisresolver "github.com/buzz-IT/provider-databricks/internal/apis"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *Budget) ResolveReferences( // ResolveReferences of this Budget.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlertConfigurations); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("security.databricks.m.crossplane.io", "v1alpha1", "Group", "GroupList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalIDRef,
					Selector:     mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalID")
			}
			mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalID = reference.ToFloatPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlertConfigurations); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("security.databricks.m.crossplane.io", "v1alpha1", "Group", "GroupList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalIDRef,
					Selector:     mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalID")
			}
			mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalID = reference.ToFloatPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.AlertConfigurations[i3].PrincipalOverrides[i4].PrincipalIDRef = rsp.ResolvedReference

		}
	}

	return nil
}
