// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AwsVPCEndpointInfoInitParameters struct {

	// The ID of the underlying VPC endpoint in AWS. Provided by the customer when
	// registering an existing AWS VPC endpoint
	AwsVPCEndpointID *string `json:"awsVpcEndpointId,omitempty" tf:"aws_vpc_endpoint_id,omitempty"`
}

type AwsVPCEndpointInfoObservation struct {

	// The AWS account ID in which this VPC endpoint lives
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the Databricks VPC endpoint service that this endpoint connects to
	AwsEndpointServiceID *string `json:"awsEndpointServiceId,omitempty" tf:"aws_endpoint_service_id,omitempty"`

	// The ID of the underlying VPC endpoint in AWS. Provided by the customer when
	// registering an existing AWS VPC endpoint
	AwsVPCEndpointID *string `json:"awsVpcEndpointId,omitempty" tf:"aws_vpc_endpoint_id,omitempty"`
}

type AwsVPCEndpointInfoParameters struct {

	// The ID of the underlying VPC endpoint in AWS. Provided by the customer when
	// registering an existing AWS VPC endpoint
	// +kubebuilder:validation:Optional
	AwsVPCEndpointID *string `json:"awsVpcEndpointId" tf:"aws_vpc_endpoint_id,omitempty"`
}

type AzurePrivateEndpointInfoInitParameters struct {

	// The name of the Private Endpoint in the Azure subscription
	PrivateEndpointName *string `json:"privateEndpointName,omitempty" tf:"private_endpoint_name,omitempty"`

	// The GUID of the Private Endpoint resource in the Azure subscription.
	// This is assigned by Azure when the user sets up the Private Endpoint
	PrivateEndpointResourceGUID *string `json:"privateEndpointResourceGuid,omitempty" tf:"private_endpoint_resource_guid,omitempty"`
}

type AzurePrivateEndpointInfoObservation struct {

	// The name of the Private Endpoint in the Azure subscription
	PrivateEndpointName *string `json:"privateEndpointName,omitempty" tf:"private_endpoint_name,omitempty"`

	// The GUID of the Private Endpoint resource in the Azure subscription.
	// This is assigned by Azure when the user sets up the Private Endpoint
	PrivateEndpointResourceGUID *string `json:"privateEndpointResourceGuid,omitempty" tf:"private_endpoint_resource_guid,omitempty"`

	// The full resource ID of the Private Endpoint
	PrivateEndpointResourceID *string `json:"privateEndpointResourceId,omitempty" tf:"private_endpoint_resource_id,omitempty"`

	// The resource ID of the Databricks Private Link Service that this Private Endpoint connects to
	PrivateLinkServiceID *string `json:"privateLinkServiceId,omitempty" tf:"private_link_service_id,omitempty"`
}

type AzurePrivateEndpointInfoParameters struct {

	// The name of the Private Endpoint in the Azure subscription
	// +kubebuilder:validation:Optional
	PrivateEndpointName *string `json:"privateEndpointName" tf:"private_endpoint_name,omitempty"`

	// The GUID of the Private Endpoint resource in the Azure subscription.
	// This is assigned by Azure when the user sets up the Private Endpoint
	// +kubebuilder:validation:Optional
	PrivateEndpointResourceGUID *string `json:"privateEndpointResourceGuid" tf:"private_endpoint_resource_guid,omitempty"`
}

type EndpointInitParameters struct {

	// Info for an AWS VPC endpoint
	AwsVPCEndpointInfo *AwsVPCEndpointInfoInitParameters `json:"awsVpcEndpointInfo,omitempty" tf:"aws_vpc_endpoint_info,omitempty"`

	// Info for an Azure private endpoint
	AzurePrivateEndpointInfo *AzurePrivateEndpointInfoInitParameters `json:"azurePrivateEndpointInfo,omitempty" tf:"azure_private_endpoint_info,omitempty"`

	// The human-readable display name of this endpoint.
	// The input should conform to RFC-1034, which restricts to letters, numbers, and hyphens,
	// with the first character a letter, the last a letter or a number, and a 63 character maximum
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Info for a GCP Private Service Connect endpoint
	GCPPscEndpointInfo *GCPPscEndpointInfoInitParameters `json:"gcpPscEndpointInfo,omitempty" tf:"gcp_psc_endpoint_info,omitempty"`

	// The parent resource name of the account under which the endpoint is created.
	// Format: accounts/{account_id}
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// The cloud provider region where this endpoint is located
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type EndpointObservation struct {

	// The Databricks Account in which the endpoint object exists
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Info for an AWS VPC endpoint
	AwsVPCEndpointInfo *AwsVPCEndpointInfoObservation `json:"awsVpcEndpointInfo,omitempty" tf:"aws_vpc_endpoint_info,omitempty"`

	// Info for an Azure private endpoint
	AzurePrivateEndpointInfo *AzurePrivateEndpointInfoObservation `json:"azurePrivateEndpointInfo,omitempty" tf:"azure_private_endpoint_info,omitempty"`

	// The timestamp when the endpoint was created. The timestamp is in RFC 3339 format in UTC timezone
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The human-readable display name of this endpoint.
	// The input should conform to RFC-1034, which restricts to letters, numbers, and hyphens,
	// with the first character a letter, the last a letter or a number, and a 63 character maximum
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The unique identifier for this endpoint under the account. This field is a UUID generated by Databricks
	EndpointID *string `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// Info for a GCP Private Service Connect endpoint
	GCPPscEndpointInfo *GCPPscEndpointInfoObservation `json:"gcpPscEndpointInfo,omitempty" tf:"gcp_psc_endpoint_info,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The resource name of the endpoint, which uniquely identifies the endpoint
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The parent resource name of the account under which the endpoint is created.
	// Format: accounts/{account_id}
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// The cloud provider region where this endpoint is located
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The state of the endpoint. The endpoint can only be used if the state is APPROVED. Possible values are: APPROVED, DISCONNECTED, FAILED, PENDING
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The use case that determines the type of network connectivity this endpoint provides.
	// This field is automatically determined based on the endpoint configuration and cloud-specific settings. Possible values are: SERVICE_DIRECT
	UseCase *string `json:"useCase,omitempty" tf:"use_case,omitempty"`
}

type EndpointParameters struct {

	// Info for an AWS VPC endpoint
	// +kubebuilder:validation:Optional
	AwsVPCEndpointInfo *AwsVPCEndpointInfoParameters `json:"awsVpcEndpointInfo,omitempty" tf:"aws_vpc_endpoint_info,omitempty"`

	// Info for an Azure private endpoint
	// +kubebuilder:validation:Optional
	AzurePrivateEndpointInfo *AzurePrivateEndpointInfoParameters `json:"azurePrivateEndpointInfo,omitempty" tf:"azure_private_endpoint_info,omitempty"`

	// The human-readable display name of this endpoint.
	// The input should conform to RFC-1034, which restricts to letters, numbers, and hyphens,
	// with the first character a letter, the last a letter or a number, and a 63 character maximum
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Info for a GCP Private Service Connect endpoint
	// +kubebuilder:validation:Optional
	GCPPscEndpointInfo *GCPPscEndpointInfoParameters `json:"gcpPscEndpointInfo,omitempty" tf:"gcp_psc_endpoint_info,omitempty"`

	// The parent resource name of the account under which the endpoint is created.
	// Format: accounts/{account_id}
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// The cloud provider region where this endpoint is located
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type GCPPscEndpointInfoInitParameters struct {

	// The GCP region of the PSC connection endpoint. Provided by the customer when registering an
	// existing PSC endpoint. GCP supports only same-region PSC, so this must match the workspace
	// region
	EndpointRegion *string `json:"endpointRegion,omitempty" tf:"endpoint_region,omitempty"`

	// The GCP consumer project ID in which this PSC endpoint is created. Provided by the customer
	// when registering an existing PSC endpoint
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The name of this PSC connection in the GCP consumer project. Provided by the customer when
	// registering an existing PSC endpoint
	PscEndpoint *string `json:"pscEndpoint,omitempty" tf:"psc_endpoint,omitempty"`
}

type GCPPscEndpointInfoObservation struct {

	// The GCP region of the PSC connection endpoint. Provided by the customer when registering an
	// existing PSC endpoint. GCP supports only same-region PSC, so this must match the workspace
	// region
	EndpointRegion *string `json:"endpointRegion,omitempty" tf:"endpoint_region,omitempty"`

	// The GCP consumer project ID in which this PSC endpoint is created. Provided by the customer
	// when registering an existing PSC endpoint
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The ID of the underlying Private Service Connect connection in the GCP consumer project,
	// assigned by GCP when the PSC connection is created
	PscConnectionID *string `json:"pscConnectionId,omitempty" tf:"psc_connection_id,omitempty"`

	// The name of this PSC connection in the GCP consumer project. Provided by the customer when
	// registering an existing PSC endpoint
	PscEndpoint *string `json:"pscEndpoint,omitempty" tf:"psc_endpoint,omitempty"`

	// The ID of the Databricks service attachment this PSC endpoint connects to
	ServiceAttachmentID *string `json:"serviceAttachmentId,omitempty" tf:"service_attachment_id,omitempty"`
}

type GCPPscEndpointInfoParameters struct {

	// The GCP region of the PSC connection endpoint. Provided by the customer when registering an
	// existing PSC endpoint. GCP supports only same-region PSC, so this must match the workspace
	// region
	// +kubebuilder:validation:Optional
	EndpointRegion *string `json:"endpointRegion" tf:"endpoint_region,omitempty"`

	// The GCP consumer project ID in which this PSC endpoint is created. Provided by the customer
	// when registering an existing PSC endpoint
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`

	// The name of this PSC connection in the GCP consumer project. Provided by the customer when
	// registering an existing PSC endpoint
	// +kubebuilder:validation:Optional
	PscEndpoint *string `json:"pscEndpoint" tf:"psc_endpoint,omitempty"`
}

// EndpointSpec defines the desired state of Endpoint
type EndpointSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   EndpointParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EndpointInitParameters `json:"initProvider,omitempty"`
}

// EndpointStatus defines the observed state of Endpoint.
type EndpointStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EndpointObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Endpoint is the Schema for the Endpoints API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type Endpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parent) || (has(self.initProvider) && has(self.initProvider.parent))",message="spec.forProvider.parent is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   EndpointSpec   `json:"spec"`
	Status EndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EndpointList contains a list of Endpoints
type EndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Endpoint `json:"items"`
}

// Repository type metadata.
var (
	Endpoint_Kind             = "Endpoint"
	Endpoint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Endpoint_Kind}.String()
	Endpoint_KindAPIVersion   = Endpoint_Kind + "." + CRDGroupVersion.String()
	Endpoint_GroupVersionKind = CRDGroupVersion.WithKind(Endpoint_Kind)
)

func init() {
	SchemeBuilder.Register(&Endpoint{}, &EndpointList{})
}
