// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AIGatewayFallbackConfigInitParameters struct {

	// boolean flag specifying if usage tracking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type AIGatewayFallbackConfigObservation struct {

	// boolean flag specifying if usage tracking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type AIGatewayFallbackConfigParameters struct {

	// boolean flag specifying if usage tracking is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`
}

type AIGatewayGuardrailsInitParameters struct {

	// A block with configuration for input guardrail filters:
	Input *GuardrailsInputInitParameters `json:"input,omitempty" tf:"input,omitempty"`

	// A block with configuration for output guardrail filters.  Has the same structure as input block.
	Output *GuardrailsOutputInitParameters `json:"output,omitempty" tf:"output,omitempty"`
}

type AIGatewayGuardrailsObservation struct {

	// A block with configuration for input guardrail filters:
	Input *GuardrailsInputObservation `json:"input,omitempty" tf:"input,omitempty"`

	// A block with configuration for output guardrail filters.  Has the same structure as input block.
	Output *GuardrailsOutputObservation `json:"output,omitempty" tf:"output,omitempty"`
}

type AIGatewayGuardrailsParameters struct {

	// A block with configuration for input guardrail filters:
	// +kubebuilder:validation:Optional
	Input *GuardrailsInputParameters `json:"input,omitempty" tf:"input,omitempty"`

	// A block with configuration for output guardrail filters.  Has the same structure as input block.
	// +kubebuilder:validation:Optional
	Output *GuardrailsOutputParameters `json:"output,omitempty" tf:"output,omitempty"`
}

type AIGatewayInferenceTableConfigInitParameters struct {

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// boolean flag specifying if usage tracking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type AIGatewayInferenceTableConfigObservation struct {

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// boolean flag specifying if usage tracking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type AIGatewayInferenceTableConfigParameters struct {

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	// +kubebuilder:validation:Optional
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// boolean flag specifying if usage tracking is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	// +kubebuilder:validation:Optional
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// +kubebuilder:validation:Optional
	TableNamePrefix *string `json:"tableNamePrefix,omitempty" tf:"table_name_prefix,omitempty"`
}

type AIGatewayRateLimitsInitParameters struct {
	Calls *float64 `json:"calls,omitempty" tf:"calls,omitempty"`

	// The key field for a tag.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	RenewalPeriod *string `json:"renewalPeriod,omitempty" tf:"renewal_period,omitempty"`

	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type AIGatewayRateLimitsObservation struct {
	Calls *float64 `json:"calls,omitempty" tf:"calls,omitempty"`

	// The key field for a tag.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	RenewalPeriod *string `json:"renewalPeriod,omitempty" tf:"renewal_period,omitempty"`

	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type AIGatewayRateLimitsParameters struct {

	// +kubebuilder:validation:Optional
	Calls *float64 `json:"calls,omitempty" tf:"calls,omitempty"`

	// The key field for a tag.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// +kubebuilder:validation:Optional
	RenewalPeriod *string `json:"renewalPeriod" tf:"renewal_period,omitempty"`

	// +kubebuilder:validation:Optional
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`
}

type AIGatewayUsageTrackingConfigInitParameters struct {

	// boolean flag specifying if usage tracking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type AIGatewayUsageTrackingConfigObservation struct {

	// boolean flag specifying if usage tracking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type AIGatewayUsageTrackingConfigParameters struct {

	// boolean flag specifying if usage tracking is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ConfigServedEntitiesInitParameters struct {

	// boolean flag specifying if usage tracking is enabled.
	BurstScalingEnabled *bool `json:"burstScalingEnabled,omitempty" tf:"burst_scaling_enabled,omitempty"`

	// The full path of the UC model to be served, given in the form of catalog_name.schema_name.model_name.
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The version of the model in UC to be served.
	EntityVersion *string `json:"entityVersion,omitempty" tf:"entity_version,omitempty"`

	// The name of a served entity. It must be unique across an endpoint. A served entity name can consist of alphanumeric characters, dashes, and underscores. If not specified for an external model, this field will be created from the entity_name and entity_version
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of model units to be provisioned.
	ProvisionedModelUnits *float64 `json:"provisionedModelUnits,omitempty" tf:"provisioned_model_units,omitempty"`
}

type ConfigServedEntitiesObservation struct {

	// boolean flag specifying if usage tracking is enabled.
	BurstScalingEnabled *bool `json:"burstScalingEnabled,omitempty" tf:"burst_scaling_enabled,omitempty"`

	// The full path of the UC model to be served, given in the form of catalog_name.schema_name.model_name.
	EntityName *string `json:"entityName,omitempty" tf:"entity_name,omitempty"`

	// The version of the model in UC to be served.
	EntityVersion *string `json:"entityVersion,omitempty" tf:"entity_version,omitempty"`

	// The name of a served entity. It must be unique across an endpoint. A served entity name can consist of alphanumeric characters, dashes, and underscores. If not specified for an external model, this field will be created from the entity_name and entity_version
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of model units to be provisioned.
	ProvisionedModelUnits *float64 `json:"provisionedModelUnits,omitempty" tf:"provisioned_model_units,omitempty"`
}

type ConfigServedEntitiesParameters struct {

	// boolean flag specifying if usage tracking is enabled.
	// +kubebuilder:validation:Optional
	BurstScalingEnabled *bool `json:"burstScalingEnabled,omitempty" tf:"burst_scaling_enabled,omitempty"`

	// The full path of the UC model to be served, given in the form of catalog_name.schema_name.model_name.
	// +kubebuilder:validation:Optional
	EntityName *string `json:"entityName" tf:"entity_name,omitempty"`

	// The version of the model in UC to be served.
	// +kubebuilder:validation:Optional
	EntityVersion *string `json:"entityVersion" tf:"entity_version,omitempty"`

	// The name of a served entity. It must be unique across an endpoint. A served entity name can consist of alphanumeric characters, dashes, and underscores. If not specified for an external model, this field will be created from the entity_name and entity_version
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of model units to be provisioned.
	// +kubebuilder:validation:Optional
	ProvisionedModelUnits *float64 `json:"provisionedModelUnits" tf:"provisioned_model_units,omitempty"`
}

type ConfigTrafficConfigInitParameters struct {

	// Each block represents a route that defines traffic to each served entity. Each served_entity block needs to have a corresponding routes block.
	Routes []TrafficConfigRoutesInitParameters `json:"routes,omitempty" tf:"routes,omitempty"`
}

type ConfigTrafficConfigObservation struct {

	// Each block represents a route that defines traffic to each served entity. Each served_entity block needs to have a corresponding routes block.
	Routes []TrafficConfigRoutesObservation `json:"routes,omitempty" tf:"routes,omitempty"`
}

type ConfigTrafficConfigParameters struct {

	// Each block represents a route that defines traffic to each served entity. Each served_entity block needs to have a corresponding routes block.
	// +kubebuilder:validation:Optional
	Routes []TrafficConfigRoutesParameters `json:"routes,omitempty" tf:"routes,omitempty"`
}

type GuardrailsInputInitParameters struct {

	// List of invalid keywords. AI guardrail uses keyword or string matching to decide if the keyword exists in the request or response content.
	InvalidKeywords []*string `json:"invalidKeywords,omitempty" tf:"invalid_keywords,omitempty"`

	// Block with configuration for guardrail PII filter:
	Pii *InputPiiInitParameters `json:"pii,omitempty" tf:"pii,omitempty"`

	// the boolean flag that indicates whether the safety filter is enabled.
	Safety *bool `json:"safety,omitempty" tf:"safety,omitempty"`

	// The list of allowed topics. Given a chat request, this guardrail flags the request if its topic is not in the allowed topics.
	ValidTopics []*string `json:"validTopics,omitempty" tf:"valid_topics,omitempty"`
}

type GuardrailsInputObservation struct {

	// List of invalid keywords. AI guardrail uses keyword or string matching to decide if the keyword exists in the request or response content.
	InvalidKeywords []*string `json:"invalidKeywords,omitempty" tf:"invalid_keywords,omitempty"`

	// Block with configuration for guardrail PII filter:
	Pii *InputPiiObservation `json:"pii,omitempty" tf:"pii,omitempty"`

	// the boolean flag that indicates whether the safety filter is enabled.
	Safety *bool `json:"safety,omitempty" tf:"safety,omitempty"`

	// The list of allowed topics. Given a chat request, this guardrail flags the request if its topic is not in the allowed topics.
	ValidTopics []*string `json:"validTopics,omitempty" tf:"valid_topics,omitempty"`
}

type GuardrailsInputParameters struct {

	// List of invalid keywords. AI guardrail uses keyword or string matching to decide if the keyword exists in the request or response content.
	// +kubebuilder:validation:Optional
	InvalidKeywords []*string `json:"invalidKeywords,omitempty" tf:"invalid_keywords,omitempty"`

	// Block with configuration for guardrail PII filter:
	// +kubebuilder:validation:Optional
	Pii *InputPiiParameters `json:"pii,omitempty" tf:"pii,omitempty"`

	// the boolean flag that indicates whether the safety filter is enabled.
	// +kubebuilder:validation:Optional
	Safety *bool `json:"safety,omitempty" tf:"safety,omitempty"`

	// The list of allowed topics. Given a chat request, this guardrail flags the request if its topic is not in the allowed topics.
	// +kubebuilder:validation:Optional
	ValidTopics []*string `json:"validTopics,omitempty" tf:"valid_topics,omitempty"`
}

type GuardrailsOutputInitParameters struct {

	// List of invalid keywords. AI guardrail uses keyword or string matching to decide if the keyword exists in the request or response content.
	InvalidKeywords []*string `json:"invalidKeywords,omitempty" tf:"invalid_keywords,omitempty"`

	// Block with configuration for guardrail PII filter:
	Pii *GuardrailsOutputPiiInitParameters `json:"pii,omitempty" tf:"pii,omitempty"`

	// the boolean flag that indicates whether the safety filter is enabled.
	Safety *bool `json:"safety,omitempty" tf:"safety,omitempty"`

	// The list of allowed topics. Given a chat request, this guardrail flags the request if its topic is not in the allowed topics.
	ValidTopics []*string `json:"validTopics,omitempty" tf:"valid_topics,omitempty"`
}

type GuardrailsOutputObservation struct {

	// List of invalid keywords. AI guardrail uses keyword or string matching to decide if the keyword exists in the request or response content.
	InvalidKeywords []*string `json:"invalidKeywords,omitempty" tf:"invalid_keywords,omitempty"`

	// Block with configuration for guardrail PII filter:
	Pii *GuardrailsOutputPiiObservation `json:"pii,omitempty" tf:"pii,omitempty"`

	// the boolean flag that indicates whether the safety filter is enabled.
	Safety *bool `json:"safety,omitempty" tf:"safety,omitempty"`

	// The list of allowed topics. Given a chat request, this guardrail flags the request if its topic is not in the allowed topics.
	ValidTopics []*string `json:"validTopics,omitempty" tf:"valid_topics,omitempty"`
}

type GuardrailsOutputParameters struct {

	// List of invalid keywords. AI guardrail uses keyword or string matching to decide if the keyword exists in the request or response content.
	// +kubebuilder:validation:Optional
	InvalidKeywords []*string `json:"invalidKeywords,omitempty" tf:"invalid_keywords,omitempty"`

	// Block with configuration for guardrail PII filter:
	// +kubebuilder:validation:Optional
	Pii *GuardrailsOutputPiiParameters `json:"pii,omitempty" tf:"pii,omitempty"`

	// the boolean flag that indicates whether the safety filter is enabled.
	// +kubebuilder:validation:Optional
	Safety *bool `json:"safety,omitempty" tf:"safety,omitempty"`

	// The list of allowed topics. Given a chat request, this guardrail flags the request if its topic is not in the allowed topics.
	// +kubebuilder:validation:Optional
	ValidTopics []*string `json:"validTopics,omitempty" tf:"valid_topics,omitempty"`
}

type GuardrailsOutputPiiInitParameters struct {

	// a string that describes the behavior for PII filter. Currently only BLOCK value is supported.
	Behavior *string `json:"behavior,omitempty" tf:"behavior,omitempty"`
}

type GuardrailsOutputPiiObservation struct {

	// a string that describes the behavior for PII filter. Currently only BLOCK value is supported.
	Behavior *string `json:"behavior,omitempty" tf:"behavior,omitempty"`
}

type GuardrailsOutputPiiParameters struct {

	// a string that describes the behavior for PII filter. Currently only BLOCK value is supported.
	// +kubebuilder:validation:Optional
	Behavior *string `json:"behavior,omitempty" tf:"behavior,omitempty"`
}

type InputPiiInitParameters struct {

	// a string that describes the behavior for PII filter. Currently only BLOCK value is supported.
	Behavior *string `json:"behavior,omitempty" tf:"behavior,omitempty"`
}

type InputPiiObservation struct {

	// a string that describes the behavior for PII filter. Currently only BLOCK value is supported.
	Behavior *string `json:"behavior,omitempty" tf:"behavior,omitempty"`
}

type InputPiiParameters struct {

	// a string that describes the behavior for PII filter. Currently only BLOCK value is supported.
	// +kubebuilder:validation:Optional
	Behavior *string `json:"behavior,omitempty" tf:"behavior,omitempty"`
}

type ModelServingProvisionedThroughputAIGatewayInitParameters struct {

	// The model serving endpoint configuration.
	FallbackConfig *AIGatewayFallbackConfigInitParameters `json:"fallbackConfig,omitempty" tf:"fallback_config,omitempty"`

	// Block with configuration for AI Guardrails to prevent unwanted data and unsafe data in requests and responses. Consists of the following attributes:
	Guardrails *AIGatewayGuardrailsInitParameters `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Block describing the configuration of usage tracking. Consists of the following attributes:
	InferenceTableConfig *AIGatewayInferenceTableConfigInitParameters `json:"inferenceTableConfig,omitempty" tf:"inference_table_config,omitempty"`

	// Block describing rate limits for AI gateway. For details see the description of rate_limits block above.
	RateLimits []AIGatewayRateLimitsInitParameters `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Block with configuration for payload logging using inference tables. For details see the description of auto_capture_config block above.
	UsageTrackingConfig *AIGatewayUsageTrackingConfigInitParameters `json:"usageTrackingConfig,omitempty" tf:"usage_tracking_config,omitempty"`
}

type ModelServingProvisionedThroughputAIGatewayObservation struct {

	// The model serving endpoint configuration.
	FallbackConfig *AIGatewayFallbackConfigObservation `json:"fallbackConfig,omitempty" tf:"fallback_config,omitempty"`

	// Block with configuration for AI Guardrails to prevent unwanted data and unsafe data in requests and responses. Consists of the following attributes:
	Guardrails *AIGatewayGuardrailsObservation `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Block describing the configuration of usage tracking. Consists of the following attributes:
	InferenceTableConfig *AIGatewayInferenceTableConfigObservation `json:"inferenceTableConfig,omitempty" tf:"inference_table_config,omitempty"`

	// Block describing rate limits for AI gateway. For details see the description of rate_limits block above.
	RateLimits []AIGatewayRateLimitsObservation `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Block with configuration for payload logging using inference tables. For details see the description of auto_capture_config block above.
	UsageTrackingConfig *AIGatewayUsageTrackingConfigObservation `json:"usageTrackingConfig,omitempty" tf:"usage_tracking_config,omitempty"`
}

type ModelServingProvisionedThroughputAIGatewayParameters struct {

	// The model serving endpoint configuration.
	// +kubebuilder:validation:Optional
	FallbackConfig *AIGatewayFallbackConfigParameters `json:"fallbackConfig,omitempty" tf:"fallback_config,omitempty"`

	// Block with configuration for AI Guardrails to prevent unwanted data and unsafe data in requests and responses. Consists of the following attributes:
	// +kubebuilder:validation:Optional
	Guardrails *AIGatewayGuardrailsParameters `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Block describing the configuration of usage tracking. Consists of the following attributes:
	// +kubebuilder:validation:Optional
	InferenceTableConfig *AIGatewayInferenceTableConfigParameters `json:"inferenceTableConfig,omitempty" tf:"inference_table_config,omitempty"`

	// Block describing rate limits for AI gateway. For details see the description of rate_limits block above.
	// +kubebuilder:validation:Optional
	RateLimits []AIGatewayRateLimitsParameters `json:"rateLimits,omitempty" tf:"rate_limits,omitempty"`

	// Block with configuration for payload logging using inference tables. For details see the description of auto_capture_config block above.
	// +kubebuilder:validation:Optional
	UsageTrackingConfig *AIGatewayUsageTrackingConfigParameters `json:"usageTrackingConfig,omitempty" tf:"usage_tracking_config,omitempty"`
}

type ModelServingProvisionedThroughputConfigInitParameters struct {

	// A list of served entities for the endpoint to serve.
	ServedEntities []ConfigServedEntitiesInitParameters `json:"servedEntities,omitempty" tf:"served_entities,omitempty"`

	// A single block represents the traffic split configuration amongst the served models.
	TrafficConfig *ConfigTrafficConfigInitParameters `json:"trafficConfig,omitempty" tf:"traffic_config,omitempty"`
}

type ModelServingProvisionedThroughputConfigObservation struct {

	// A list of served entities for the endpoint to serve.
	ServedEntities []ConfigServedEntitiesObservation `json:"servedEntities,omitempty" tf:"served_entities,omitempty"`

	// A single block represents the traffic split configuration amongst the served models.
	TrafficConfig *ConfigTrafficConfigObservation `json:"trafficConfig,omitempty" tf:"traffic_config,omitempty"`
}

type ModelServingProvisionedThroughputConfigParameters struct {

	// A list of served entities for the endpoint to serve.
	// +kubebuilder:validation:Optional
	ServedEntities []ConfigServedEntitiesParameters `json:"servedEntities,omitempty" tf:"served_entities,omitempty"`

	// A single block represents the traffic split configuration amongst the served models.
	// +kubebuilder:validation:Optional
	TrafficConfig *ConfigTrafficConfigParameters `json:"trafficConfig,omitempty" tf:"traffic_config,omitempty"`
}

type ModelServingProvisionedThroughputEmailNotificationsInitParameters struct {

	// a list of email addresses to be notified when an endpoint fails to update its configuration or state.
	OnUpdateFailure []*string `json:"onUpdateFailure,omitempty" tf:"on_update_failure,omitempty"`

	// a list of email addresses to be notified when an endpoint successfully updates its configuration or state.
	OnUpdateSuccess []*string `json:"onUpdateSuccess,omitempty" tf:"on_update_success,omitempty"`
}

type ModelServingProvisionedThroughputEmailNotificationsObservation struct {

	// a list of email addresses to be notified when an endpoint fails to update its configuration or state.
	OnUpdateFailure []*string `json:"onUpdateFailure,omitempty" tf:"on_update_failure,omitempty"`

	// a list of email addresses to be notified when an endpoint successfully updates its configuration or state.
	OnUpdateSuccess []*string `json:"onUpdateSuccess,omitempty" tf:"on_update_success,omitempty"`
}

type ModelServingProvisionedThroughputEmailNotificationsParameters struct {

	// a list of email addresses to be notified when an endpoint fails to update its configuration or state.
	// +kubebuilder:validation:Optional
	OnUpdateFailure []*string `json:"onUpdateFailure,omitempty" tf:"on_update_failure,omitempty"`

	// a list of email addresses to be notified when an endpoint successfully updates its configuration or state.
	// +kubebuilder:validation:Optional
	OnUpdateSuccess []*string `json:"onUpdateSuccess,omitempty" tf:"on_update_success,omitempty"`
}

type ModelServingProvisionedThroughputInitParameters struct {

	// A block with AI Gateway configuration for the serving endpoint. Note: only external model endpoints are supported as of now.
	AIGateway *ModelServingProvisionedThroughputAIGatewayInitParameters `json:"aiGateway,omitempty" tf:"ai_gateway,omitempty"`

	// (Optiona) The Budget Policy ID set for this serving endpoint.
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	// The model serving endpoint configuration.
	Config *ModelServingProvisionedThroughputConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// A block with Email notification setting.
	EmailNotifications *ModelServingProvisionedThroughputEmailNotificationsInitParameters `json:"emailNotifications,omitempty" tf:"email_notifications,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	ProviderConfig *ModelServingProvisionedThroughputProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Tags to be attached to the serving endpoint and automatically propagated to billing logs.
	Tags []ModelServingProvisionedThroughputTagsInitParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ModelServingProvisionedThroughputObservation struct {

	// A block with AI Gateway configuration for the serving endpoint. Note: only external model endpoints are supported as of now.
	AIGateway *ModelServingProvisionedThroughputAIGatewayObservation `json:"aiGateway,omitempty" tf:"ai_gateway,omitempty"`

	// (Optiona) The Budget Policy ID set for this serving endpoint.
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	// The model serving endpoint configuration.
	Config *ModelServingProvisionedThroughputConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// A block with Email notification setting.
	EmailNotifications *ModelServingProvisionedThroughputEmailNotificationsObservation `json:"emailNotifications,omitempty" tf:"email_notifications,omitempty"`

	// Equal to the name argument and used to identify the serving endpoint.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	ProviderConfig *ModelServingProvisionedThroughputProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Unique identifier of the serving endpoint primarily used to set permissions and refer to this instance for other operations.
	ServingEndpointID *string `json:"servingEndpointId,omitempty" tf:"serving_endpoint_id,omitempty"`

	// Tags to be attached to the serving endpoint and automatically propagated to billing logs.
	Tags []ModelServingProvisionedThroughputTagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ModelServingProvisionedThroughputParameters struct {

	// A block with AI Gateway configuration for the serving endpoint. Note: only external model endpoints are supported as of now.
	// +kubebuilder:validation:Optional
	AIGateway *ModelServingProvisionedThroughputAIGatewayParameters `json:"aiGateway,omitempty" tf:"ai_gateway,omitempty"`

	// (Optiona) The Budget Policy ID set for this serving endpoint.
	// +kubebuilder:validation:Optional
	BudgetPolicyID *string `json:"budgetPolicyId,omitempty" tf:"budget_policy_id,omitempty"`

	// The model serving endpoint configuration.
	// +kubebuilder:validation:Optional
	Config *ModelServingProvisionedThroughputConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// A block with Email notification setting.
	// +kubebuilder:validation:Optional
	EmailNotifications *ModelServingProvisionedThroughputEmailNotificationsParameters `json:"emailNotifications,omitempty" tf:"email_notifications,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	// +kubebuilder:validation:Optional
	ProviderConfig *ModelServingProvisionedThroughputProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Tags to be attached to the serving endpoint and automatically propagated to billing logs.
	// +kubebuilder:validation:Optional
	Tags []ModelServingProvisionedThroughputTagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ModelServingProvisionedThroughputProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ModelServingProvisionedThroughputProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ModelServingProvisionedThroughputProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ModelServingProvisionedThroughputTagsInitParameters struct {

	// The key field for a tag.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value field for a tag.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ModelServingProvisionedThroughputTagsObservation struct {

	// The key field for a tag.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value field for a tag.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ModelServingProvisionedThroughputTagsParameters struct {

	// The key field for a tag.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value field for a tag.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TrafficConfigRoutesInitParameters struct {

	// The name of the served entity this route configures traffic for. This needs to match the name of a served_entity block.
	ServedEntityName *string `json:"servedEntityName,omitempty" tf:"served_entity_name,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	ServedModelName *string `json:"servedModelName,omitempty" tf:"served_model_name,omitempty"`

	// The percentage of endpoint traffic to send to this route. It must be an integer between 0 and 100 inclusive.
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type TrafficConfigRoutesObservation struct {

	// The name of the served entity this route configures traffic for. This needs to match the name of a served_entity block.
	ServedEntityName *string `json:"servedEntityName,omitempty" tf:"served_entity_name,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	ServedModelName *string `json:"servedModelName,omitempty" tf:"served_model_name,omitempty"`

	// The percentage of endpoint traffic to send to this route. It must be an integer between 0 and 100 inclusive.
	TrafficPercentage *float64 `json:"trafficPercentage,omitempty" tf:"traffic_percentage,omitempty"`
}

type TrafficConfigRoutesParameters struct {

	// The name of the served entity this route configures traffic for. This needs to match the name of a served_entity block.
	// +kubebuilder:validation:Optional
	ServedEntityName *string `json:"servedEntityName,omitempty" tf:"served_entity_name,omitempty"`

	// The name of the model serving endpoint. This field is required and must be unique across a workspace. An endpoint name can consist of alphanumeric characters, dashes, and underscores. NOTE: Changing this name will delete the existing endpoint and create a new endpoint with the updated name.
	// +kubebuilder:validation:Optional
	ServedModelName *string `json:"servedModelName,omitempty" tf:"served_model_name,omitempty"`

	// The percentage of endpoint traffic to send to this route. It must be an integer between 0 and 100 inclusive.
	// +kubebuilder:validation:Optional
	TrafficPercentage *float64 `json:"trafficPercentage" tf:"traffic_percentage,omitempty"`
}

// ModelServingProvisionedThroughputSpec defines the desired state of ModelServingProvisionedThroughput
type ModelServingProvisionedThroughputSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ModelServingProvisionedThroughputParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ModelServingProvisionedThroughputInitParameters `json:"initProvider,omitempty"`
}

// ModelServingProvisionedThroughputStatus defines the observed state of ModelServingProvisionedThroughput.
type ModelServingProvisionedThroughputStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ModelServingProvisionedThroughputObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ModelServingProvisionedThroughput is the Schema for the ModelServingProvisionedThroughputs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type ModelServingProvisionedThroughput struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.config) || (has(self.initProvider) && has(self.initProvider.config))",message="spec.forProvider.config is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ModelServingProvisionedThroughputSpec   `json:"spec"`
	Status ModelServingProvisionedThroughputStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ModelServingProvisionedThroughputList contains a list of ModelServingProvisionedThroughputs
type ModelServingProvisionedThroughputList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ModelServingProvisionedThroughput `json:"items"`
}

// Repository type metadata.
var (
	ModelServingProvisionedThroughput_Kind             = "ModelServingProvisionedThroughput"
	ModelServingProvisionedThroughput_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ModelServingProvisionedThroughput_Kind}.String()
	ModelServingProvisionedThroughput_KindAPIVersion   = ModelServingProvisionedThroughput_Kind + "." + CRDGroupVersion.String()
	ModelServingProvisionedThroughput_GroupVersionKind = CRDGroupVersion.WithKind(ModelServingProvisionedThroughput_Kind)
)

func init() {
	SchemeBuilder.Register(&ModelServingProvisionedThroughput{}, &ModelServingProvisionedThroughputList{})
}
